### ISSUE TITLE
JS：用jQuery UI Widget 工厂吧。

### ISSUE THREAD

**Issue by zhangyuanwei** [allmobilize/amazeui#271]
jQuery UI Widget 工厂是一 jQuery UI 的基础工厂，用于生成jQuery的UI插件，虽然jQuery UI太大、不好用，但是 UI Widget 这套机制是设计得很好的，实现了多例、事件、成员函数、私有函数等等，很适合 AmazeUI 的场景。

[http://jqueryui.com/widget/](http://jqueryui.com/widget/)

**Comment by Minwe** [comment]
根据行业趋势及 Amaze UI 未来规划，不太可能再用这个东西，暂时关闭。谢谢！
