### ISSUE TITLE
建议弄一个Dash Docset

### ISSUE THREAD

**Issue by bruceCzK** [allmobilize/amazeui#299]
新项目准备用，但是查文档很痛苦啊，我用html2dash试了下，比较混乱，希望能出一个Docset

**Comment by Minwe** [comment]
https://github.com/amazeui/docs-generator

**Comment by bruceCzK** [comment]
赞！

**Comment by bruceCzK** [comment]
![qq20150122-1](https://cloud.githubusercontent.com/assets/8399711/5854316/850e3966-a267-11e4-88c1-27dd5aee42e5.jpg)
Dash 2.2.2/2.2.3 无效

**Comment by Minwe** [comment]
已经修复，请重新下载。谢谢。
