### ISSUE TITLE
ScrollSpy插件 不能实现列表图片动态加载

### ISSUE THREAD

**Issue by hawkcraw** [allmobilize/amazeui#307]
**问题描述**

想实现一个图文列表，图片随着滚动加载，但事件都没有被触发

**Comment by Minwe** [comment]
ScrollSpy 的事件是在 DOM Ready 的时候初始化的，动态加载的内容不会绑定默认的初始化事件，你需要内容插入以后，执行 
```js
$('selector').scrollspy({animation: 'fade'});
```

具体实例可参考 http://amazeui.github.io/echo/docs/scrollspy.html
