### ISSUE TITLE
amazeUI在手机端地图功能上能否实现百度地图的功能？

### ISSUE THREAD

**Issue by hainuo** [allmobilize/amazeui#34]
手机端访问daohang.map.baidu.com能够进行导航，amazeUI能否提供一套简单的设置（比如时候终点的地名 ），就能够直接跳转至这样的界面？

**Comment by Minwe** [comment]
一般用户都已经安装地图应用，鉴于浏览器的局限性，不再处理这个需求。

如有需要，请参考 http://developer.baidu.com/map/jsdemo-mobile.htm#i4_1
