### ISSUE TITLE
做Hybrid APP时数据交互怎么做？

### ISSUE THREAD

**Issue by ZhenZinian** [allmobilize/amazeui#359]
1.单页应用时一个div往往是一个手机页面

如何控制哪个div是当前该显示的页？

2.比如div1里是用户的注册表单  用户点击提交后

伪代码：
向左slide到另一个div2
ajax提交数据到后端
if 后端返回成功-->渲染div2,把返回数据打印到div2的dom中

这些基本的数据和前后端通信用amazeui怎么做？

能不能出个HYbrid app系列教学视频？

**Comment by Minwe** [comment]
merge to #94
