### ISSUE TITLE
模态窗口连续打开多次后笼罩层消失

### ISSUE THREAD

**Issue by wananys** [allmobilize/amazeui#367]
**问题描述**

连续点击多次后，笼罩层出现后会迅速消失

**产生环境**

- 设备：所有手机上都有这个问题
- 操作系统及版本：
- 浏览器及版本：所有浏览器也都出现了这个问题
- 演示地址：参照官网JS插件--模态窗口: http://amazeui.org/javascript/modal

**复现步骤**

1.演示中点击一次按钮，窗口和笼罩层正常显示
2.接着连续点击两次按钮，Model窗口能正常打开，笼罩层出现后迅速消失
3.再点击按钮，笼罩层都是出现后迅速消失

![qq 20141230163709](https://cloud.githubusercontent.com/assets/9670815/5577008/24fab59e-9043-11e4-8fa1-38ef3a1ca322.png)

**Comment by Minwe** [comment]
今天更新了 2.1-beta1，这个问题无法重现了。麻烦你那边再测试一下看还存不存在（测试前请清空浏览器缓存）。谢谢！
