### ISSUE TITLE
Bug: 浏览一塌糊涂

### ISSUE THREAD

**Issue by ivan820819** [allmobilize/amazeui#370]
你们的官网在Win7的FF上看错位的一塌糊涂，官网都展示不好还怎么能让俺们普通用户放心使用。
你们官网上面的开始使用链接，点进去自己看看吧，哎

**Comment by Minwe** [comment]
这个 Issue 也是两塌糊涂：

首先，什么叫【错位的一塌糊涂】？如果你的测试人员给你提交一个这样的 Bug，你能理解？起码做一下描述或者截个图啊。

其次，既然从包含链接模板的链接进来，为何不按照模板提交 Bug？FF 成百上千个版本，要一个一个去测试么？http://amazeui.org/getting-started/compatibility 我们只测试最新的两个正式版，上面已经说得很清楚。

国内的开源环境真是一塌糊涂，哎！没人参与共享代码就算了，连提个 Issue 也要一个一个的教……

如果是本着解决问题的态度来，那就按照下面的格式提交 Bug。说一堆词不达意的话，然后我们又在这一个一个追问半天，这不是浪费彼此的时间么？一次表达清楚不好么？


```
**问题描述**

（描述一下问题）

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1.
2.
...
```
