### ISSUE TITLE
引用 jquery.form.js，放到 amazeui.js后面，data-am-selected 失效。

### ISSUE THREAD

**Issue by Ahoo-Wang** [allmobilize/amazeui#379]
引用 jquery.form.js，放到 amazeui.js后面，data-am-selected 失效。

链接地址：https://github.com/malsup/form 。

辛苦了！！！

**Comment by Minwe** [comment]
jquery.form.js 具体是哪个插件？请给出地址。

**Comment by Ahoo-Wang** [comment]
https://github.com/malsup/form

**Comment by Ahoo-Wang** [comment]
https://github.com/malsup/form

**Comment by Minwe** [comment]
https://github.com/malsup/form/blob/6bf24a5f6d8be65f4e5491863180c09356d9dadd/jquery.form.js#L1240-L1258

函数名冲突……
