### ISSUE TITLE
2.0 modal组件字体在IE发虚

### ISSUE THREAD

**Issue by suwakowww** [allmobilize/amazeui#387]
操作系统：Windows 技术预览版（6.4.9879）
浏览器：IE11（11.0.9879.0）（右侧）/Firefox36.0a1（2014-11-28）（左侧，作对比用）
演示地址：http://amazeui.org/javascript/modal
（就是教程那个）
![font](https://cloud.githubusercontent.com/assets/6368936/5646900/f92b8662-96bb-11e4-8b66-8645cc0cfef7.png)
详细问题见图片对比。

**Comment by Minwe** [comment]
图片压缩过吗？图片上看起来不是很直观。另外，系统和浏览器都是非正式版，不再测试范围内。

**Comment by suwakowww** [comment]
用IE11+Windows 8.1试了一下，还是这个问题：
![2](https://cloud.githubusercontent.com/assets/6368936/5679636/36f764ac-983d-11e4-98ab-d479aa5bc26a.png)
大概是IE的问题吧

**Comment by minwe** [comment]
在 Edge 上也发现了这个问题，去掉 modal 的 tranlate3d transform 以后恢复正常，IE11 上可能也是这个原因吧。

回头新版发布以后你可以看一下这个问题还存不存在。

**Comment by minwe** [comment]
Fixed by 518b316, tested.
