### ISSUE TITLE
输入框组输入框会比btn高

### ISSUE THREAD

**Issue by ningxiaoixao** [allmobilize/amazeui#392]
iphone5 ios8 safari
chrom 38内核
出现这样的问题
![image](https://cloud.githubusercontent.com/assets/4375762/5674956/a03563c8-97ee-11e4-9159-4bd29fd6c3ab.png)

**Comment by wukonggg** [comment]
同样的问题出现在以下浏览器中：
chrome36.0.1985.125 m
ie11.0.9600.17501
360安全浏览器7.1.1.550极速模式（内核31.0.1650.63）
![unnamed qq screenshot20150109122541](https://cloud.githubusercontent.com/assets/10458950/5675507/ac689e74-97fa-11e4-8e3d-41419f80f7bb.png)

**Comment by Minwe** [comment]
via @wukonggg 

**问题描述**
使用输入框组合时输入框和按钮高度不一致

**产生环境**
- 设备：PC
- 操作系统及版本：Win7 64位
- 浏览器及版本：
360安全浏览器7.1.1.550（内核版本：31.0.1650.63）
chrome 36.0.1985.125 m
ie 11.0.9600.17501

**复现步奏**
1.查看官网地址即可：http://amazeui.org/css/input-group

**其他截图**
![unnamed qq screenshot20150109122541](https://cloud.githubusercontent.com/assets/10458950/5675568/a1389d90-97fc-11e4-8b6d-039bd907310d.png)

**Comment by Mrhyuan** [comment]
一样 还没有解决吗

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://lilypadresort.com/rank.php?69>

 

Again_moon@sohu.com
