### ISSUE TITLE
使用输入框组合时输入框和按钮高度不一致

### ISSUE THREAD

**Issue by wukonggg** [allmobilize/amazeui#394]
**问题描述**
使用输入框组合时输入框和按钮高度不一致

**产生环境**
- 设备：PC
- 操作系统及版本：Win7 64位
- 浏览器及版本：
360安全浏览器7.1.1.550（内核版本：31.0.1650.63）
chrome 36.0.1985.125 m
ie 11.0.9600.17501

**复现步奏**
1.查看官网地址即可：http://amazeui.org/css/input-group

**其他截图**
![unnamed qq screenshot20150109122541](https://cloud.githubusercontent.com/assets/10458950/5675568/a1389d90-97fc-11e4-8b6d-039bd907310d.png)

**Comment by Minwe** [comment]
合并到 #392 处理，谢谢！
