### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by yuandi0823** [allmobilize/amazeui#396]
看过了无数的移动端html5 ui框架，我觉得从易用性上面来说amazeui还不错。但是出现的问题也很多，因为可能不是全职做这个东东，这个可以理解。由于时间，人力，物力有限，amazeui可以不考虑兼容PC端的浏览器，只要专注于移动端的开发就好，好钢用在刀刃上。一点建议，希望你们做的东西越来越好用。

**Comment by suwakowww** [comment]
貌似amazeui一开始就是“移动优先”的设计吧。不过现在的移动设备的分辨率也有PC端的水平了。只做移动端会不会有平板党过来说按键间距很大不好用呢？

**Comment by Minwe** [comment]
@suwakowww 分辨率不等于实际渲染出来的大小，可以 Google 一下啊 devicePixelRatio。

R 屏 MBP 15.4－英寸 (2880 x 1800)，显示的时候默认按照 1440 * 900 渲染，iPad R 2048 x 1536，渲染出来是 1024 x 768

http://www.quirksmode.org/blog/archives/2012/06/devicepixelrati.html

http://viewportsizes.com/ 可以查到手机、平板的实际显示大小。

**Comment by Minwe** [comment]
@yuandi0823 谢谢建议。台子打起来以后会逐步调整重心，我们希望更多的人参与进来，但半年下来，感觉在中国这种环境似乎不太现实。

**Comment by Minwe** [comment]
我们下一步会着力 SPA，基本上也就是移动端的，此 issue 关闭，更多细节可以到 #94 中参与讨论。
