### ISSUE TITLE
Bug: 模态窗口下  data-am-popover会被隐藏

### ISSUE THREAD

**Issue by jxwy001** [allmobilize/amazeui#397]
**问题描述** 我的模态窗口里有一个按钮 模态窗口是INDEX:-1 然后这个窗口里有一个按钮
加了 data-am-popover="{content: '鄙是点击 Hover 显示的 Popover', trigger: 'hover focus',z-index:1200}"  应该是被遮挡了 怎么处理？

（描述一下问题）

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; rv:34.0) Gecko/20100101 Firefox/34.0
```

**Comment by haima95** [comment]
当添加了popover要怎么隐藏，我用了popover('close') , remove(), removeData() 都无效

**Comment by haima95** [comment]
在ios上

**Comment by minwe** [comment]
如果你真想解决问题，就给出一个可以在线查看的地址，这样我好理解你到底想实现什么。

**Comment by haima95** [comment]
很感谢你能这么快回复我。我想实现popover能被点击后，500ms会自动隐藏。只在本地测试，所以只能粘贴部分代码。popover没有消失，所以我想求教我在哪里写错了吗，谢谢！

 $('[data-am-popover]').eq(i).popover({
       content: “hello,world”,
       theme:'primary',
       trigger: 'click'
 }).on('open.popover.amui',function(){
         setTimeout("closePopover('+i+')",500); 
});
function closePopover(i){
    $('[data-am-popover]').eq(i).popover('close');
}

**Comment by minwe** [comment]
- 使用 JS 调用的时候不要加 `data-am-popover` 这个属性，换一个别的选择符。

应该是 `i` 没传进去，改成：

```js
setTimeout(function() {
  closePopover(i);
}, 500);
```

**Comment by haima95** [comment]
根据你的建议，我直接采用id去调用，i 是传递成功的，但是仍然无法将popover隐藏
 $('#popover'+i).popover({
        	   content: loadRoomInfo['rows'][i]['address'],
        	   theme:'primary',
        	   trigger: 'click'
               }).on('open.popover.amui',function(){
            	   setTimeout(function(){
            		   closePopover(i);
                	   },500);
               });
function closePopover(i){
		$('#popover'+i).popover('close');
		$('#popover'+i).removeData('amui.popover');

	}

**Comment by haima95** [comment]
我是采用js动态创建控件，在一个table里创建多个表格来点击
<tr><td><a href="javascript:void(0)" id="popover'+i+'">click me</a></td><tr>'

**Comment by minwe** [comment]
http://bin.amazeui.org/gimosu/edit?html,output

把完整代码写出来吧。

**Comment by haima95** [comment]
不好意思，这么晚回复你。代码已上传。静态布局popover可以正常隐藏，但是js动态添加控件，popover就隐藏失败。

http://bin.amazeui.org/xijudoyuba/edit?html,output

**Comment by minwe** [comment]
```js
      $(function() {        
        for(var i=0;i<4;i++){
          tr1 = '<tr><td><a href="javascript:void(0)" id="popover'+i+'">click ' + i + '</a></td><td>room</td>        <td>state</td>'
            +'</tr>';
          $('#roomTable').append(tr1);
          $('#popover'+i).popover({
            content: "hello " + i,
            theme:'primary',
            trigger: 'click'
          }).on('open.popover.amui',function(){
            var $this = $(this);
            setTimeout(function(){
              $this.popover('close');
            },500);
          });
        }
      });
```

http://bin.amazeui.org/daleju/edit?html,output

`setTimeout` 是异步的，传进去的 `i` 有问题。

**Comment by haima95** [comment]
真的很感谢你耐心的帮助，谢谢！

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://vip-games.cf/outside.php?j>

 

Again_moon@sohu.com
