### ISSUE TITLE
窗口宽度足够小的情况下，modal的关闭按钮消失不见

### ISSUE THREAD

**Issue by suwakowww** [allmobilize/amazeui#400]
又是modal组件......
设备：电脑/三丧i9505（高通版S4）
操作系统：Windows 8.1（6.3.9600）/Android 4.4.4
浏览器：IE11（电脑）/UC浏览器（手机）/Android系统自带浏览器（手机）
演示地址（还是这个......）：http://amazeui.org/javascript/modal
截图：
![02](https://cloud.githubusercontent.com/assets/6368936/5691642/04d8b9f0-990d-11e4-9dcc-b5c66fc934ed.png)
而Bootstrap则没有这个问题：
![03](https://cloud.githubusercontent.com/assets/6368936/5691643/05543a8a-990d-11e4-9c99-2243c37a04d0.png)
这个问题在手机先发现的，当时点了一下第一个演示modal之后，就因为找不到关闭键，关闭不了，然后只能根据windows给的经验（点右上角），戳了不下十次才关掉。（截图要在手机找，到时找到再传）
然后在电脑试了一 下，还是有这个问题...要先拉长窗口才能显示关闭键。
暂时还是避免用 .closeViaDimmer 这个样式吧......

**Comment by Minwe** [comment]
看清楚这个示例为了演示 `width` 这个参数，设置了 Modal 宽度为 `400px`

```html
<button class="am-btn am-btn-primary" data-am-modal="{target: '#doc-modal-1', closeViaDimmer: 0, width: 400, height: 225}">Modal</button>
```

如果不设置的话在 `sm` 区间的宽度是 `270px`，在绝大多数手机上都不会被隐藏。
