### ISSUE TITLE
Bug:后台管理模板

### ISSUE THREAD

**Issue by 2282666** [allmobilize/amazeui#412]
**后台管理模板表单页面错乱，帮助页面1、2描述重复*

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：win7家庭
- 浏览器及版本：谷歌、猎豹
- 演示地址：

**复现步奏**

1. 
2. 
...

**Comment by Minwe** [comment]
请提供截图，谢谢！接完图后直接在评论框里粘贴或者拖到评论框就可以上传。

**Comment by Minwe** [comment]
merge to #414
