### ISSUE TITLE
使用 artTemplate 如何使用 AMUI

### ISSUE THREAD

**Issue by mr18** [allmobilize/amazeui#413]
**意见反馈**
- 为什么你们用的Handlebars模板引擎，不用artTemplate等类似的体积小的，性能也好。我现在有个项目之前是artTemplate做的现在想用AMUI，貌似有很多插件都不能用，有什么办法吗？

**Comment by Minwe** [comment]
Handlebars 是前后端通用模板，很多框架都在用。

你可以继续使用你原来的模板引擎，只要按照 AMUI 代码结构组织模板就行了。

**Comment by mr18** [comment]
还有个问题，amazeui.js怎么不按模块加载，css都分开了，感觉文件好大的样子。

**Comment by Minwe** [comment]
现在的 HTTP 标准，发送多个请求比请求合在一起的文件要慢很多。

打包好的文件是给普通的用户使用的，有一定基础的用户建议直接使用源码开发。
