### ISSUE TITLE
后台管理模板表格显示问题

### ISSUE THREAD

**Issue by 2282666** [allmobilize/amazeui#414]
后台模板中的表格页错乱，帮助页中的1、2描述重复。

![qq 20150115193402](https://cloud.githubusercontent.com/assets/10544285/5756726/9a61a03e-9ced-11e4-9229-7dfc81b52d3b.jpg)
![qq 20150115193406](https://cloud.githubusercontent.com/assets/10544285/5756729/9c785106-9ced-11e4-8b5f-9db4ea668180.jpg)

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：win7旗舰32位
- 浏览器及版本：猎豹浏览器v5.1.77.9318
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/537.36 LBBROWSER
```

**Comment by Minwe** [comment]
![image](https://cloud.githubusercontent.com/assets/4370770/5871960/3fa92d86-a320-11e4-8818-258c7ed0b1c5.png)

你是说这块的问题？你截图白色的那块是渲染出来就那样还是你抹掉了？

**Comment by Minwe** [comment]
确实有红圈所示问题，Chrome 上也存在，@haungzhipeng 下周抽空看一下。

**Comment by 2282666** [comment]
am-hide-sm-only的继承问题，如下改过之后好了


@media (min-width: 1025px){
  .am-hide-sm-only, .am-show-sm-up, .am-hide-sm, 
  .am-hide-sm-down, .am-hide-md-only, .am-show-md-up, 
  .am-hide-md, .am-hide-md-down, .am-show-lg-only, 
  .am-show-lg-up, .am-show-lg, .am-show-lg-down{
    display:table-cell!important;

  }
}
@media (min-width: 641px){
.am-hide-sm-only, .am-show-sm-up, .am-hide-sm, .am-hide-sm-down, .am-show-md-only, .am-show-md-up, .am-show-md, .am-show-md-down, .am-hide-lg-only, .am-hide-lg-up, .am-hide-lg, .am-show-lg-down {
display: table-cell!important;
}

}

**Comment by Minwe** [comment]
@2282666 好的，谢谢，看来这对表格的样式也要加上。
