### ISSUE TITLE
Bug: 官网的2.1版本中admin-table.html表格grid样式错乱

### ISSUE THREAD

**Issue by hansark** [allmobilize/amazeui#418]
**问题描述**

admin-table.html 打开之后gird样式错乱。作者、修改日期明显错乱。错误太明显，请及时修正。

**产生环境**

- 设备：电脑
- 操作系统及版本：windows2012
- 浏览器及版本：火狐 遨游 360 均出现
- 演示地址：官网提供的压缩包中 admin-table.html

**复现步奏**
无需重复，打开即可见。

**Comment by Minwe** [comment]
合并到 #414 处理
