### ISSUE TITLE
Bug: ie下模态窗口 Modal 的头部错位

### ISSUE THREAD

**Issue by fengqiaoguke** [allmobilize/amazeui#419]
**问题描述**

在ie浏览器打开模态窗口会出现头部和窗口分离

**产生环境**

- 操作系统及版本：win8.1
- 浏览器及版本：ie11 (ie9,ie10内核也一样)
- 演示地址：http://amazeui.org/javascript/modal  
 http://goblog.tangfengqiao.cn/ 
屏幕截图: http://pan.baidu.com/s/1mgoSsM8
**复现步奏**

1. 点击登入会弹出modal
2. 发现modal的头部head和body是分离的
...

**Comment by Minwe** [comment]
![qq 20150118222303](https://cloud.githubusercontent.com/assets/4370770/5795957/fb1703ba-9fd6-11e4-84b0-ea9dfb80c2e5.jpg)

**Comment by galenyuan** [comment]
amazeui.css中.am-popup-hd的position改为relative即可，可修改padding来美化一下样式，不太会用pull request 就直接在这里回答好啦.. 我不太善于寻找bug, 希望能有机会加入你们帮助fix bug :)
