### ISSUE TITLE
控件初始化时DOM还没加载进来

### ISSUE THREAD

**Issue by Luoxinfang** [allmobilize/amazeui#424]
我使用的是angularjs 导航里面用了下拉列表这个控件
因为导航是通用的 我就放在header.html里面 然后include进来 
导致下拉列表点击无效

**Comment by Minwe** [comment]
传统 JS 插件的默认初始化事件都是在 DOM Ready 时候执行的，而单页应用动态加载这些组件的时候显然已经过了这个时机。当然，Angular 的特殊性还不止这些，这就是为什么需要单独为 Angular 等框架做移植的原因。

你可以试一下载入 Header 以后手动初始化下拉列队。

```js
$(element).dropdown();
```
