### ISSUE TITLE
Input Group显示有问题

### ISSUE THREAD

**Issue by wukonggg** [allmobilize/amazeui#429]
看官网截图就明白了
![360 20150124223332950](https://cloud.githubusercontent.com/assets/10458950/5887666/8aa98fb6-a419-11e4-9f8f-adf4593cb36c.png)

360安全浏览器 急速模式 内核版本31.0.1650.63

**Comment by Minwe** [comment]
**处理方式一：**

 `.am-input-group-label`  里的内容是不确定的，所以没有设定宽度。

你可以根据实际使用场景 `.am-input-group-label` 给设置一个宽度。

**处理方式二：**

如果觉得图标应该是等宽的，可以到 https://github.com/FortAwesome/Font-Awesome/issues 反馈。
