### ISSUE TITLE
希望能在Accordion 折叠面板 可以增加不可折叠所有面板

### ISSUE THREAD

**Issue by notyears** [allmobilize/amazeui#443]
**问题描述**

希望能在Accordion 折叠面板 可以增加不可折叠所有面板

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
...

**Comment by Minwe** [comment]
http://amazeui.org/widgets/accordion/default/0?_ver=2.x 第一个例子不是你说不可折叠？

```html
<section data-am-widget="accordion" class="am-accordion am-accordion-default"
data-am-accordion='{ "multiple": true }'>
  <dl class="am-accordion-item am-active">
    <dt class="am-accordion-title">就这样恣意的活着</dt>
    <dd class="am-accordion-bd am-collapse am-in">
      <!-- 规避 Collapase 处理有 padding 的折叠内容计算计算有误问题， 加一个容器 -->
      <div class="am-accordion-content">置身人群中
        <br/>你只需要被淹没 享受 沉默
        <br/>退到人群后
        <br/>你只需给予双手 微笑 等候</div>
    </dd>
  </dl>
  <dl class="am-accordion-item">
    <dt class="am-accordion-title">让生命去等候，去等候，去等候，去等候</dt>
    <dd class="am-accordion-bd am-collapse ">
      <!-- 规避 Collapase 处理有 padding 的折叠内容计算计算有误问题， 加一个容器 -->
      <div class="am-accordion-content">走在忠孝东路
        <br/>徘徊在茫然中
        <br/>在我的人生旅途
        <br/>选择了多少错误
        <br/>我在睡梦中惊醒
        <br/>感叹悔言无尽
        <br/>恨我不能说服自己
        <br/>接受一切教训
        <br/>让生命去等候
        <br/>等候下一个漂流
        <br/>让生命去等候
        <br/>等候下一个伤口</div>
    </dd>
  </dl>
  <dl class="am-accordion-item">
    <dt class="am-accordion-title">我就这样告别山下的家</dt>
    <dd class="am-accordion-bd am-collapse ">
      <!-- 规避 Collapase 处理有 padding 的折叠内容计算计算有误问题， 加一个容器 -->
      <div class="am-accordion-content">我就这样告别山下的家，我实在不愿轻易让眼泪留下。我以为我并不差不会害怕，我就这样自己照顾自己长大。我不想因为现实把头低下，我以为我并不差能学会虚假。怎样才能够看穿面具里的谎话？别让我的真心散的像沙。如果有一天我变得更复杂，还能不能唱出歌声里的那幅画？</div>
    </dd>
  </dl>
</section>
```

**Comment by notyears** [comment]
我说的是无法折叠所有版面，也就是一直有一个版面被显示，这个例子可以同时折叠所有版面的



notyears@126.com
 
发件人： Minwe LUO
发送时间： 2015-01-29 18:34
收件人： allmobilize/amazeui
抄送： notyears
主题： Re: [amazeui] Bug: 希望能在Accordion 折叠面板 可以增加不可折叠所有面板 (#443)
http://amazeui.org/widgets/accordion/default/0?_ver=2.x 第一个例子不是你说不可折叠？
<section data-am-widget="accordion" class="am-accordion am-accordion-default"
data-am-accordion='{ "multiple": true }'>
  <dl class="am-accordion-item am-active">
    <dt class="am-accordion-title">就这样恣意的活着</dt>
    <dd class="am-accordion-bd am-collapse am-in">
      
      <div class="am-accordion-content">置身人群中
        <br/>你只需要被淹没 享受 沉默
        <br/>退到人群后
        <br/>你只需给予双手 微笑 等候</div>
    </dd>
  </dl>
  <dl class="am-accordion-item">
    <dt class="am-accordion-title">让生命去等候，去等候，去等候，去等候</dt>
    <dd class="am-accordion-bd am-collapse ">
      
      <div class="am-accordion-content">走在忠孝东路
        <br/>徘徊在茫然中
        <br/>在我的人生旅途
        <br/>选择了多少错误
        <br/>我在睡梦中惊醒
        <br/>感叹悔言无尽
        <br/>恨我不能说服自己
        <br/>接受一切教训
        <br/>让生命去等候
        <br/>等候下一个漂流
        <br/>让生命去等候
        <br/>等候下一个伤口</div>
    </dd>
  </dl>
  <dl class="am-accordion-item">
    <dt class="am-accordion-title">我就这样告别山下的家</dt>
    <dd class="am-accordion-bd am-collapse ">
      
      <div class="am-accordion-content">我就这样告别山下的家，我实在不愿轻易让眼泪留下。我以为我并不差不会害怕，我就这样自己照顾自己长大。我不想因为现实把头低下，我以为我并不差能学会虚假。怎样才能够看穿面具里的谎话？别让我的真心散的像沙。如果有一天我变得更复杂，还能不能唱出歌声里的那幅画？</div>
    </dd>
  </dl>
</section>
