### ISSUE TITLE
能否禁止一个页面同时打开多个日期组件？

### ISSUE THREAD

**Issue by qingbugs** [allmobilize/amazeui#445]
**问题描述**

当一个页面使用2个日期输入框时，点击一个输入框出现日期框后，再点击另一个日期输入框会使两个日期框同时存在，前一个框并不会消失。

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
```

**Comment by Minwe** [comment]
日期插件并没有限制一个页面上只能打开一个日期选择面板，我们看一下有没有可能增加一个选项限制只能打开一个。

**Comment by Minwe** [comment]
@huangzhipeng 看一下这块怎么处理一下，我看原版插件打开一个新日期选择的时候其他的会自动关闭。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://newdiamondllc.com/practical.php?uo>

 

Again_moon@sohu.com
