### ISSUE TITLE
Bug:  tab 嵌套bug

### ISSUE THREAD

**Issue by qihuantian1** [allmobilize/amazeui#446]
**问题描述**

TAB 嵌套有问题

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本： all
- 浏览器及版本： all
- 演示地址：暂无

**复现步奏**

1.  新建一个tab页面
2.  在tab页里增加tab
不管tab是以何种方式呈现（嵌套， ajax加载等等） 都会产生问题
另外， tab 会与 jquery ui tab 冲突

**Comment by Minwe** [comment]
问题这个词太抽象，什么问题请描述清楚。

Tab 套 Tab 这种用法也够奇葩的。

另外，与 jQuery UI Tab 冲突这应该是使用者去考虑的问题：

首先，你的用法是否有问题，是否同时调用两个插件？

其次，既然是功能相同的插件，用一个就行了，没必要把所有插件都用上。

**Comment by qihuantian1** [comment]
1. tab嵌套在实际开发里 应用的还是很多的，  还有不管有没有 这个问题， 你遇没遇到这个问题， 你使不使用， 但是amazeui 确实存在这个问题。。。 只是希望官方解决而已。
2. amazeui 大部分插件使用的都是 am- 为什么tab 使用的是 ui- ？

**Comment by Minwe** [comment]
```html
<div class="am-tabs" data-am-tabs>
  <ul class="am-tabs-nav am-nav am-nav-tabs">
    <li class="am-active"><a href="javascript: void(0)">流浪</a></li>
    <li><a href="javascript: void(0)">流浪</a></li>
    <li><a href="javascript: void(0)">再流浪</a></li>
  </ul>

  <div class="am-tabs-bd">
    <div class="am-tab-panel am-active">
      ...
    </div>
    <div class="am-tab-panel">
      ...
    </div>
    <div class="am-tab-panel">
      ...
    </div>
  </div>
</div>
```

不知你哪里看到的 `ui-`。

**Comment by Minwe** [comment]
嵌套使用已经实现，等待新版本发布以后可用。

与 jQuery UI Tabs 冲突是因为都注册在 `jQuery.fn.tabs 上`，两个库都用的话就出问题了。
