### ISSUE TITLE
 动态插入内容如何初始化插件？

### ISSUE THREAD

**Issue by dengfuwei** [allmobilize/amazeui#447]
**问题描述**

动态增加的html部分效果没有

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 使用jquery的append方法动态增加上拉下拉按钮组
2. 点击上拉下拉按钮组，不能正常展开
...

**Comment by Minwe** [comment]
Amaze UI 不是具有动态绑定的功能，默认的初始化事件都是在 DOM Ready 以后进行的。

动态插入内容显然已经过了 DOM Ready 这个时机。你需要插入完成后手动调用插件完成初始化。

```js
$('[data-am-dropdown]').dropdown();
```

这些基本原来作为前端开发应该去了解。

**Comment by dengfuwei** [comment]
我引入了jquery.min.js和amazeui.min.js，使用你说的方法还是没效果，请问还有什么没注意到的地方么？

**Comment by Minwe** [comment]
你把相关的代码贴出来吧，这样才能看到是什么问题。

**Comment by dengfuwei** [comment]
下拉按钮组直接复制的网站内的html：
<div class="am-btn-group am-vertical-align-middle">
  	<button class="am-btn am-btn-secondary am-btn-xs">下拉按钮</button>
  	<div class="am-dropdown" data-am-dropdown>
    		<button class="am-btn am-btn-secondary am-dropdown-toggle am-btn-xs" data-am-dropdown-toggle> <span class="am-icon-caret-down"></span></button>
    		<ul class="am-dropdown-content">
      			<li class="am-dropdown-header">标题</li>
      			<li><a href="#">快乐的方式不只一种</a></li>
      			<li class="am-active"><a href="#">最荣幸是</a></li>
      			<li><a href="#">谁都是造物者的光荣</a></li>
      			<li class="am-disabled"><a href="#">就站在光明的角落</a></li>
      			<li class="am-divider"></li>
      			<li><a href="#">天空海阔 要做最坚强的泡沫</a></li>
    		</ul>
  	</div>
</div>

我使用了layer的模板加载数据（上面的html在模板内）：
var tmpl = $("#dataListTmpl").html();
laytpl(tmpl).render(data, function(render){
	$("#dataList").html(render);
});

加载完数据之后执行：
$('[data-am-dropdown]').dropdown();

报错：
Uncaught TypeError: undefined is not a function

**Comment by dengfuwei** [comment]
不好意思，html源码不知道要怎么粘贴

**Comment by dengfuwei** [comment]
我是放在列表中的，每一行都会有这样一个按钮组，不知道是不是多个的影响，但我使用循环来执行也不行：
var $dropdowns = $('[data-am-dropdown]');
for(var i=0; i<$dropdowns.length; i++){
	$dropdowns[i].dropdown();
}

**Comment by Minwe** [comment]
```js
var $dropdowns = $('[data-am-dropdown]');
for(var i=0; i<$dropdowns.length; i++){
  $dropdowns[i].dropdown();
}
```

你这个用法不对，$dropdowns[i] 是 DOM 对象，不是 jQuery 对象，当然用不了 jQuery 的方法。

**Comment by Minwe** [comment]
Markdown 语法：

http://wowubuntu.com/markdown/
https://help.github.com/articles/github-flavored-markdown/

**Comment by Minwe** [comment]
动态插入以后初始化的例子：
http://jsbin.com/kufuxofive/1/edit?html,output

如果打不开地址自行复制下面的代码粘贴到本地运行。

```html
<!DOCTYPE html>
<html>
<head>
<script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
  <meta charset="utf-8">
  <title>JS Bin</title>
  <link rel="stylesheet" href="http://cdn.amazeui.org/amazeui/2.2.1/css/amazeui.css
">
  <script src="http://cdn.amazeui.org/amazeui/2.2.1/js/amazeui.js
"></script>
</head>
<body>
  
<div id="my-dd">  
  <div class="am-dropdown" data-am-dropdown>
  <button class="am-btn am-btn-primary am-dropdown-toggle" data-am-dropdown-toggle>下拉列表 <span class="am-icon-caret-down"></span></button>
  <ul class="am-dropdown-content">
    <li class="am-dropdown-header">标题</li>
    <li><a href="#">快乐的方式不只一种</a></li>
    <li class="am-active"><a href="#">最荣幸是</a></li>
    <li><a href="#">谁都是造物者的光荣</a></li>
    <li class="am-disabled"><a href="#">就站在光明的角落</a></li>
    <li class="am-divider"></li>
    <li><a href="#">天空海阔 要做最坚强的泡沫</a></li>
  </ul>
</div>
  <hr>
  </div>  

  <script>
    $(function() {
      $('body').append($('#my-dd').html());
      $('body').append($('#my-dd').html());

      // 注释掉下面这一行插入的两个下拉菜单就不起作用了 
      $('[data-am-dropdown]').dropdown();
    });
    
  </script>
</body>
</html>
```

**Comment by dengfuwei** [comment]
找到原因了，是因为我多引入了一个jquery1.8版本的，非常感谢你的解答
