### ISSUE TITLE
提个关于icon的建议

### ISSUE THREAD

**Issue by bruceCzK** [allmobilize/amazeui#450]
Icon后面跟字的话距离会比较近，我一般都是加个空格什么的，不是很方便
![qq20150206-2](https://cloud.githubusercontent.com/assets/8399711/6075701/be3f23a6-ae12-11e4-9d92-f7f272ed7007.jpg)
可以用下面的代码解决，有字的时候没有边距

    [class*="@{ns}icon-"] {
      display: inline-block;
      &:empty:before {
        margin-right: 0;
      }
      &:before {
        margin-right: .25em;
        .am-icon-font;
      }
    }
![qq20150206-1](https://cloud.githubusercontent.com/assets/8399711/6075700/be3cdfec-ae12-11e4-98ec-6b7d29069ae5.jpg)

**Comment by markyun** [comment]
我也觉得有点。支持此修改。

**Comment by Minwe** [comment]
不同的场景使用方式不一样，加上 `margin-right` 有时也不完全合理，比如下面的使用方式：

```html
<span class="am-icon-qq">QQ</span>
```

建议根据使用场景和习惯自行补充一些样式。

**Comment by Minwe** [comment]
经讨论，为适应不同的使用场景，暂不添加该样式。

谢谢建议！

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://litovskaya2e.ru/interested.php?o8hh0>

 

Again_moon@sohu.com
