### ISSUE TITLE
offcanvas 中包含input控件在移动端的问题

### ISSUE THREAD

**Issue by zhoujinliang** [allmobilize/amazeui#452]
平台：微信
手机：魅族mx4
现象：弹出的键盘会触发offcanvas的closed事件。
期望解决方案：offcanvas增加一个参数，必须要显式调用close或者open才行。

**Comment by zhoujinliang** [comment]
已自己解决

**Comment by windcbf** [comment]
你可以发一个修改的pull request上来看看，开源需要大家共同参与

**Comment by Minwe** [comment]
@zhoujinliang 问题出在哪？解决方式是什么？谢谢！
