### ISSUE TITLE
gulp stuck at 'default'

### ISSUE THREAD

**Issue by PetersonLian** [allmobilize/amazeui#455]
运行gulp,然后,一直卡在

**Comment by PetersonLian** [comment]
`Starting 'default'...`    
`Finished 'default' after 10..`
一直运行不下去.卡了好久.
是否是我某个module未安装成功,从而导致default的task运行不下去了.

**Comment by Minwe** [comment]
没问题，只是在执行 watch 任务，所以没有关闭命令行
