### ISSUE TITLE
Bug: 图像预览、按钮组件存在的问题

### ISSUE THREAD

**Issue by woxinqidai** [allmobilize/amazeui#457]
1) 在微信下, 当在图像预览组件中增加了新的html片段, 则会以新的html片段中的图片来渲染, 之前的图片预览功能失效
 解决: 8737行: this.imgUrls = []; // for WeChat Image Preview
      改为 this.imgUrls = this.imgUrls||[]

2) 图片预览,其中data-rel属性在正常浏览器中可写相对路径即可, 但在微信中则必须写全路径, 并且官方文档中未对微信支持作出一些说明
 个人认为可以改进一下: 
    8766行: _this.imgUrls.push(src)
              改为  _this.imgUrls.push(/^(http|ftp)/i.test(src)?src:'http://'+location.host+src); 增加对相对路径的处理

3) 按钮组件的问题: http://amazeui.org/javascript/button  示例3, 原因没研究
   在chrome浏览器 pc模式中正常
   用chrome模拟移动设备后, 该组件里面的checkbox无论选中或未选中, 均无值

   另外在ios微信浏览器中, 发现按钮激活先激活, 然后再取消, 样式仍是激活样式, 要点击其他按钮, 按钮样式才会切换, 其他浏览器未知

<b>东西很棒, 加油!</b>

**Comment by Minwe** [comment]
谢谢反馈。

第二点中 `item.src` 返回的是完整路径，这没问题。可能 `$(item).data('rel')` 返回的是 DOM 中取到的值，有时候可能会有问题，下次更新时我们会加上。

第三点：按钮在模拟的时候确实有问题，回头我们在真机中测试一下。

在微信中的样式显示问题可能是由于 `:active` 或者 `:focus` 引起的，我们再看看。

**Comment by Minwe** [comment]
复选框按钮组无法获取值由 FastClick 导致，解决方式为在 `input` 上添加 `needsclick` class。

```
<div class="am-btn-group" data-am-button>
  <label class="am-btn am-btn-primary">
    <input type="checkbox" name="doc-js-btn" value="苹果"> 苹果
  </label>
  <label class="am-btn am-btn-primary">
    <input type="checkbox" name="doc-js-btn" value="橘子"> 橘子
  </label>
  <label class="am-btn am-btn-primary">
    <input type="checkbox" name="doc-js-btn" value="香蕉"> 香蕉
  </label>
</div>
<script>
  $(function() {
    var $cb = $('[name="doc-js-btn"]');
    $cb.on('change', function() {
      var checked = [];
      $cb.filter(':checked').each(function() {
        checked.push(this.value);
      });

      console.log('复选框选中的是：', checked.join(' | '));
    });
  });
</script>
```

**Comment by woxinqidai** [comment]
好, 看了最新版的妹子, 发现上面的第二条仍未修改, 代码贴出来看一下:


// get image URI from link's href attribute
    if (item.nodeName === 'A') {
      src = item.href; // to absolute path
      title = item.title || '';
    } else {
      // NOTE: `data-rel` should be a full URL, otherwise,
      //        WeChat images preview will not work
      src = $(item).data('rel') || item.src; // <img src='' data-rel='' />
      title = $(item).attr('alt') || '';
    }

    // add pureviewed flag
    item.setAttribute(viewedFlag, '1');

    // hide bar: wechat_webview_type=1
    // http://tmt.io/wechat/  not working?
    _this.imgUrls.push(src);


如<img src='/img/a.jpg'>这样获取出来即为相对地址 '/img/a.jpg', 在微信下面需要将其转化为完整的路径: http://xxxxxx/img/a.jpg, 这样微信才能访问到, 请测试一下.

**Comment by minwe** [comment]
当时好像时觉得获取绝对路径有点麻烦，所以 `data-rel` 没有处理。
