### ISSUE TITLE
bug:FastClick undefined

### ISSUE THREAD

**Issue by lexmeng** [allmobilize/amazeui#459]
core.js line:471
var FastClick = $.AMUI.FastClick;
应该是var FastClick = UI.FastClick;

否则，在前端js框架中引入require等框架加载js时，该行$.AMUI=undefined，抛异常，影响整个js无法运行。

**Comment by Minwe** [comment]
你是使用源码开发还是直接使用我们提供的打包的文件？

我们打包的文件里面 jQuery 被替换成全局的，如果使用 Require.js 加载 jQuery 的话应该是不行的。

```js
var $ = (typeof window !== "undefined" ? window.jQuery : typeof global !==
          "undefined" ? global.jQuery : null);
```

**Comment by lexmeng** [comment]
我的源码无论是用线上打包好的，还是我自己通过源码自己打包都存在这个问题。
但是我跟踪下来，$是有值的，$.AMUI是undefined，所以造成报错的。
