### ISSUE TITLE
amazeui 与 angularjs 不能很好集成

### ISSUE THREAD

**Issue by docoder** [allmobilize/amazeui#463]
当使用angularjs的directive时，在template里的amazeui的js插件有些不能很好工作（比如：下拉组件和按钮交互）。好像是在元素上添加属性不能工作，比如 data-am-loading,data-am-dropdown-toggle等。

**Comment by Minwe** [comment]
传统 JS 插件跟 AngularJS 的工作方式是不一样的，也就是说无法直接用于 AngularJS 项目中。
我们已经在做支持 AngularJS 相关的规划，预计年中会有初期版本出来，具体可见 #94。

**Comment by dusdong** [comment]
关于Angular的支出有时间表么？捉急啊！

**Comment by Minwe** [comment]
@dusdong  预计在 6 月初会推出 React.js 封装的版本。如果对 React 感兴趣，可以了解一下如何在 Angular 中使用 React。

**Comment by dusdong** [comment]
呃，决定用 React.js 了？到时候还会有 angularjs 版的么？

**Comment by Minwe** [comment]
@dusdong 应该不会有了，React 只是单纯的 View 层，可以结合 Angular、Backbone 等一起使用。

参考：
- https://github.com/davidchang/ngReact
- http://mono.software/posts/Improving-AngularJS-long-list-rendering-performance-using-ReactJS/
