### ISSUE TITLE
Bug: 模态窗口中模拟 Alert存在bug

### ISSUE THREAD

**Issue by hawkcraw** [allmobilize/amazeui#464]
在Alert中显示一个弹窗列表，若内容较多。显示滚动条。此时Android手机必须滑到最低端才能点击上确定按钮，否则无法点击上确定按钮（确定按钮可见）。在Iphone手机上正常

**Comment by hawkcraw** [comment]
已解决，只需在am-modal-bd上加入overflow:hidden即可

**Comment by Minwe** [comment]
谢谢反馈！
由于加上这样式可能是引发其他问题，所以只加了注释供用户参考。
