### ISSUE TITLE
iPhone5/5s 微信6.1 Modal 窗口输入框无法获取焦点？

### ISSUE THREAD

**Issue by wangwenjie1314** [allmobilize/amazeui#465]
问题链接：

打开http://mob.plldz.com/index.php

然后点击“登录”按钮，然后去点击“密码输入框”

![img](http://ebook.u.qiniudn.com/QQ图片20150305143248.png)

苹果5的情况应该是这样的问题，如果不打开键盘，输入框没问题，一打开键盘，输入框跑上面来了，但是输入的位置还在没打开键盘时输入框所在的位置上

**Comment by Minwe** [comment]
浏览器及版本？

**Comment by wangwenjie1314** [comment]
IOS7,微信内置浏览器，微信版本6.1最新

**Comment by Minwe** [comment]
现在点击【登录】没有使用 Modal 窗口了啊，已经改了？

**Comment by wangwenjie1314** [comment]
恩 哥们，抱歉，bug不等人，现在修改成跳转了；
如果你有时间的话，我发给你下当时down下来的静态页面；（没时间就这样吧）
但是你需要费点功夫了，
稍等～

**Comment by wangwenjie1314** [comment]
http://yunpan.cn/cJa6MYe6P2zmU  访问密码 37f5

**Comment by Minwe** [comment]
谢谢，这个不太好处理。

微信内置浏览器本身有很多问题，而且也不好调试。iOS8 的微信里面也会有类似的问题，Safari 下面正常。

针对微信内置浏览器开发交互比较多的应用不太现实，会搞死人的。
