### ISSUE TITLE
Cannot read property 'FastClick' of undefined 然后modal所有组件都不能用

### ISSUE THREAD

**Issue by delayhsiao** [allmobilize/amazeui#472]
Uncaught TypeError: Cannot read property 'FastClick' of undefined

就是报这个错，而且还是几率报，有的时候有，有的时候没有。
一旦报了这个错，modal的所有模块都不能用，如果没报，modal的所有模块使用正常。
求解！
妹子的JS是在jquery下面加载的，其他组件运行没问题，就这个有问题。求解！

**Comment by Minwe** [comment]
请说明问题产生的系统及浏览器，并给出完整的代码。

**Comment by delayhsiao** [comment]
OS：MIUI 6
浏览器：原生浏览器/微信内置浏览器
我弄了个只有妹子组件的代码，经测试，PC上Chrome的成功率比手机端高。demo大概就是点一下按钮弹个modal出来的例子没有其他代码，在手机上浏览，点了之后不弹modal。
code:

<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
<title>测试</title>
<script src="http://cdn.bootcss.com/jquery/2.1.1/jquery.min.js"></script>
<link href="http://cdn.amazeui.org/amazeui/2.0.0/css/amazeui.min.css" rel="stylesheet">
<script type="text/javascript" async="" src="http://cdn.amazeui.org/amazeui/2.2.1/js/amazeui.js"></script>
</head>
<body>
<button type="button" class="am-btn am-btn-primary am-radius" data-am-modal="{target: '#my-modal-loading'}">上传</button>
<div class="am-modal am-modal-loading am-modal-no-btn" tabindex="-1" id="my-modal-loading">
  <div class="am-modal-dialog">
    <div class="am-modal-hd">正在上传</div>
    <div class="am-modal-bd">
      <span class="am-icon-spinner am-icon-spin"></span>
    </div>
  </div>
</div>
</body>
</html>

**Comment by delayhsiao** [comment]
亲，求解啊！

**Comment by Minwe** [comment]
你把 http://cdn.amazeui.org/amazeui/2.2.1/js/amazeui.js 下载到本地，搜素下面的代码：

```js
var FastClick = $.AMUI.FastClick;
````

改为：

```js
var FastClick = UI.FastClick;
```

**Comment by delayhsiao** [comment]
高端！我改了amazeui.min.js一样可以，毕竟加载的时候min速度比较快。 感谢！如果我这个不是特殊情况的话，为什么不改源文件？

**Comment by Minwe** [comment]
已经修改了，放在下一版中发布。

**Comment by Minwe** [comment]
duplicate #459

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://dev.tsreid.com/launch.php?el>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://goldenhorseshoe.ru/pull.php?qeuu>

 

Again_moon@sohu.com
