### ISSUE TITLE
data-am-sticky的bug

### ISSUE THREAD

**Issue by MiracleSnow** [allmobilize/amazeui#473]
在firefox 36和ie 11下，当<div data-am-sticky="{top: 50}" class="am-g">这样使用时，在两边会有莫名奇妙的空隙，但是当去掉data-am-sticky="{top: 50}"后，两边的空隙就会去掉，在chrome 40下正常。

**Comment by Minwe** [comment]
有演示页面和截图吗？不然不太好理解你说的问题。

**Comment by MiracleSnow** [comment]
@Minwe  chrome下正常
![image](https://cloud.githubusercontent.com/assets/7878879/6685037/7bed7b6e-ccd1-11e4-8c52-2794ac0251e7.png)

ie和firefox下不正常
![image](https://cloud.githubusercontent.com/assets/7878879/6685047/908d2880-ccd1-11e4-9d04-da3b0cd4b4ae.png)

去掉data-am-sticky后都是正常的

**Comment by Minwe** [comment]
是整栏固定还是就带头像的这一块固定？

Sticky 生效以后会添加 `position: fixed` 样式，会去计算 sticky 元素的宽度然后设置样式，可能不同浏览器在计算上会有问题。我用官网的边栏在 Firefox 上测试了一下没有发现问题，所以你可能需要给出实际的演示代码，具体看一下。你可以在 JSBin 上做一个演示的页面然后把地址贴出来。

**Comment by MiracleSnow** [comment]
[http://jsbin.com/nufidofiqe/1/edit?html,output](http://jsbin.com/nufidofiqe/1/edit?html,output)

这个地址，你用ie和firefox看就会有问题
