### ISSUE TITLE
am-fr浮动使用问题

### ISSUE THREAD

**Issue by MiracleSnow** [allmobilize/amazeui#474]
![image](https://cloud.githubusercontent.com/assets/7878879/6700737/2c267f46-cd4d-11e4-84ba-fb52cea59d47.png)

往上偏了几个像素

**Comment by Minwe** [comment]
提问题之前我想你应该先搞懂什么是浮动。浮动不会帮你自动对齐，你需要自己设置高度、行高或者内外边距达到对齐效果。

**Comment by MiracleSnow** [comment]
好吧 受教了

**Comment by wengyulin** [comment]
请问你的是怎么解决的



发自我的小米手机

宋雪勦 <notifications@github.com>编写：

**Comment by MiracleSnow** [comment]
我的解决办法是给浮动元素的外层元素给一个适当的line-height
