### ISSUE TITLE
Bug: JS 插件[下拉选框]通过JS设置下拉选中，生成的下拉组件在Safari浏览器会显示选中了两个

### ISSUE THREAD

**Issue by zyc0507** [allmobilize/amazeui#476]
**问题描述**
通过JS设置下拉选中，生成的下拉组件在Safari浏览器会显示选中了两个

**产生环境**

- 设备：Safari浏览器，IPAD
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

```html
<select>
	  <option value="a">Apple</option>
	  <option value="b">Banana</option>
	  <option value="o">Orange</option>
	  <option value="m">Mango</option>
	</select>
````

```js
$("select").find("option[value='o']").attr('selected',true);
$("select").selectIt();
```
![Uploading QQ图片20150319140445.png . . .]()
![Uploading QQ图片20150319140500.png . . .]()
![Uploading QQ图片20150319140507.png . . .]()

 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; rv:36.0) Gecko/20100101 Firefox/36.0
```

**Comment by Minwe** [comment]
你的图片没有传上去，请等待 `Uploading` 消失以后在点保存按钮。
