### ISSUE TITLE
Bug: 手机UC浏览器下am-circle圆形图片的上下左右有一部分缺失

### ISSUE THREAD

**Issue by MiracleSnow** [allmobilize/amazeui#478]
**问题描述**

手机UC浏览器下am-circle圆形图片在加上am-img-thumbnail后上下左右有一部分缺失。

**产生环境**

- 设备：小米4
- 操作系统及版本：miui 6
- 浏览器及版本：uc浏览器 10.2
- 演示：

![2015-03-20_195437](https://cloud.githubusercontent.com/assets/7878879/6751056/19e00d12-cf3b-11e4-9b3b-5321364c9394.jpg)

**Comment by Minwe** [comment]
好奇葩的浏览器……你有看到别的网站使用了类似效果的、但是在 UC 浏览器上显示正常的，贴出网址我们对比一下实现方式。

**Comment by MiracleSnow** [comment]
没看到过啊，我现在就把边框去掉了，这样一般都兼容了

**Comment by Minwe** [comment]
好的。有时候为了兼容性也只能做一些减法了。有些问题本身是浏览器的 Bug，不按 Web 标准造成的。这样的我们也无能为力。
