### ISSUE TITLE
am js组件 初始化 调用

### ISSUE THREAD

**Issue by liyatang** [allmobilize/amazeui#480]
细节见
http://jsfiddle.net/liyatang/b1nd02kj/1/

求交流下...

**Comment by Minwe** [comment]
https://github.com/twbs/bootstrap/blob/master/js/tab.js BS 的 Tab 插件是通过事件委托来实现对动态创建的 DOM 事件处理的。

AMUI 则是在 Ready 事件里面初始化默认接口，动态插入的 DOM 已经是在 Ready 事件之后，所以没有绑定相关事件。

```js
// Init code
UI.ready(function(context) {
  $('[data-am-tabs]', context).tabs();
});
```

一些插件中通过事件委托可以解决动态插入 DOM 的事件绑定问题，但是并不是所有插件都可以这样，因为有的插件用户操作没有定位到要绑定元素的 DOM 上。

比如 https://github.com/twbs/bootstrap/blob/master/js/affix.js 这类插件。

要想完全解决这种问题可以借助 MutationObserver 监视 DOM 变化，但是浏览器支持不好。其他思路的话就是 Angular、Ember.js 这类的解决方案了。

我们在后续版本的开发中会考虑处理这些问题。

**Comment by liyatang** [comment]
好好，谢谢！  反馈速度给力，赞一个。
