### ISSUE TITLE
datePicker插件onRender不能阻止月份、年份视图日期的选择

### ISSUE THREAD

**Issue by meowl** [allmobilize/amazeui#486]
[官网用例](http://amazeui.org/javascript/datepicker#%E8%AE%BE%E7%BD%AE%E7%A6%81%E6%AD%A2%E9%80%89%E6%8B%A9%E6%97%A5%E6%9C%9F)
<b>问题描述：</b>
在datepicker的option中通过onRender方法禁止日期被选中，只能禁止days中的日期，对months\years视图无效。
若今天是2015-03-24，当禁止选中除当天时间以外的日期，若用户转到months视图，选择当前之前的月份如2月，会向页面输出2015-02-01或2015-02-24
![unnamed qq screenshot20150325141916](https://cloud.githubusercontent.com/assets/1335861/6819343/a692b418-d2fa-11e4-8a68-e864e9c2e43d.png)
只能选择当天日期
![22](https://cloud.githubusercontent.com/assets/1335861/6819348/baf13a74-d2fa-11e4-93d7-9327a1090ba6.png)
通过months视图进入2月，所有日期不能选择，仍像页面输出了2015-02-01

**Comment by Minwe** [comment]
```html
<div class="am-input-group am-datepicker-date" data-am-datepicker="{format: 'yyyy'}">
  <input type="text" class="am-form-field" placeholder="日历组件" readonly>
  <span class="am-input-group-btn am-datepicker-add-on">
    <button class="am-btn am-btn-default" type="button"><span class="am-icon-calendar"></span> </button>
  </span>
</div>
```

日期格式只保留 `yyyy` 的时候会报错，@huangzhipeng 看一下有没有只选择年份的可能，要是太复杂就算了。

**Comment by huangzhipeng** [comment]
日期格式需要设置分隔符：

```
format: 'yyyy ', viewMode: 'years', minViewMode: 'years' 
```
结合限制视图来实现只选择年份， `format: yyyy `加一个空格做完分隔符。

只设置年份：
```
<div class="am-input-group am-datepicker-date" data-am-datepicker="{format: 'yyyy ', viewMode: 'years', minViewMode: 'years' }">
  <input type="text" class="am-form-field" placeholder="日历组件" readonly>
  <span class="am-input-group-btn am-datepicker-add-on">
    <button class="am-btn am-btn-default" type="button"><span class="am-icon-calendar"></span> </button>
  </span>
</div>
```

onRender不能阻止月份、年份视图日期，已修正。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://sendbuket.md/living.php?ewi0p>

 

Again_moon@sohu.com
