### ISSUE TITLE
期望文档系统107个组件直观的可以看到

### ISSUE THREAD

**Issue by rongzedong** [allmobilize/amazeui#488]
**问题描述**

参考 php的文档系统
Amaze UI 含近 20 个 CSS 组件、10 个 JS 组件，更有 17 款包含近 60 个主题的 Web 组件！
将这107个组件直观的可以看到。

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36
```

**Comment by Minwe** [comment]
何来 107？

## CSS

- [样式统一](http://amazeui.org/css/normalize)
- [基础设置](http://amazeui.org/css/base)
- [文字排版](http://amazeui.org/css/typography)
- [打印样式](http://amazeui.org/css/print)
- [网格](http://amazeui.org/css/grid)
- [等分网格](http://amazeui.org/css/block-grid)
- [辅助类](http://amazeui.org/css/utility)
- [按钮](http://amazeui.org/css/button)
- [代码](http://amazeui.org/css/code)
- [表单](http://amazeui.org/css/form)
- [图片](http://amazeui.org/css/image)
- [表格](http://amazeui.org/css/table)
- [小徽章](http://amazeui.org/css/badge)
- [面包屑导航](http://amazeui.org/css/breadcrumb)
- [按钮组](http://amazeui.org/css/button-group)
- [关闭按钮](http://amazeui.org/css/close)
- [评论列表](http://amazeui.org/css/comment)
- [图标](http://amazeui.org/css/icon)
- [输入框组](http://amazeui.org/css/input-group)
- [列表](http://amazeui.org/css/list)
- [导航](http://amazeui.org/css/nav)
- [导航条](http://amazeui.org/css/topbar)
- [分页](http://amazeui.org/css/pagination)
- [面板](http://amazeui.org/css/panel)
- [进度条](http://amazeui.org/css/progress)
- [缩略图](http://amazeui.org/css/thumbnail)
- [CSS 动画](http://amazeui.org/css/animation)
- [文章页](http://amazeui.org/css/article)

## JS

- [警告框](http://amazeui.org/javascript/alert)
- [按钮交互](http://amazeui.org/javascript/button)
- [折叠面板](http://amazeui.org/javascript/collapse)
- [下拉组件](http://amazeui.org/javascript/dropdown)
- [模态窗口](http://amazeui.org/javascript/modal)
- [弹出框](http://amazeui.org/javascript/popover)
- [加载进度条](http://amazeui.org/javascript/nprogress)
- [图片轮播](http://amazeui.org/javascript/slider)
- [侧边栏](http://amazeui.org/javascript/offcanvas)
- [滚动侦测](http://amazeui.org/javascript/scrollspy)
- [滚动侦测导航](http://amazeui.org/javascript/scrollspynav)
- [平滑滚动](http://amazeui.org/javascript/smooth-scroll)
- [固定元素](http://amazeui.org/javascript/sticky)
- [选项卡](http://amazeui.org/javascript/tabs)
- [日期组件](http://amazeui.org/javascript/datepicker)
- [下拉选框](http://amazeui.org/javascript/selected)
- [单/多选框](http://amazeui.org/javascript/ucheck)
- [表单验证](http://amazeui.org/javascript/validator)
- [Cookie](http://amazeui.org/javascript/cookie)
- [FastClick](http://amazeui.org/javascript/fastclick)
- [全屏切换](http://amazeui.org/javascript/fullscreen)
- [触控事件](http://amazeui.org/javascript/hammer)
- [iScroll](http://amazeui.org/javascript/iscroll-lite)
- [本地存储](http://amazeui.org/javascript/store)
- [地理位置](http://amazeui.org/javascript/geolocation)

## Web 组件

组件主题见每个组件页面内。

- [ 调试工具](http://amazeui.org/widgets/debugger)
- [折叠面板](http://amazeui.org/widgets/accordion)
- [分割线](http://amazeui.org/widgets/divider)
- [单张图片](http://amazeui.org/widgets/figure)
- [页脚](http://amazeui.org/widgets/footer)
- [图片画廊](http://amazeui.org/widgets/gallery)
- [回顶部](http://amazeui.org/widgets/gotop)
- [页头](http://amazeui.org/widgets/header)
- [简介](http://amazeui.org/widgets/intro)
- [内容列表](http://amazeui.org/widgets/list_news)
- [菜单](http://amazeui.org/widgets/menu)
- [工具栏](http://amazeui.org/widgets/navbar)
- [分页](http://amazeui.org/widgets/pagination)
- [段落](http://amazeui.org/widgets/paragraph)
- [图片轮播](http://amazeui.org/widgets/slider)
- [选项卡](http://amazeui.org/widgets/tabs)
- [标题栏](http://amazeui.org/widgets/titlebar)

**Comment by rongzedong** [comment]
问题描述里写的啊。 近 20 个 CSS 组件、10 个 JS 组件，更有 17 款包含近 60 个主题

**Comment by rongzedong** [comment]
而且，要多一些 examples 就更方便，容易学习

**Comment by Minwe** [comment]
例子需要大家多贡献了，单靠一两个人搞不完。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://ct87391.tmweb.ru/norm.php?w6>

 

Again_moon@sohu.com
