### ISSUE TITLE
JS表单自定义ajax验证问题

### ISSUE THREAD

**Issue by meowl** [allmobilize/amazeui#500]
**问题描述**
表单控件使用自定义ajax验证后，若被验证控件内已经存在值，且该值是可以通过验证的，但此时没有触发该控件的验证事件，光标焦点也不在该控件上；
此时点击提交按钮，表单没有提交，光标焦点出现在该控件中，此时控件是通过验证的，需要再点击一次提交按钮才能提交。
我画个图各位看一下，我不知道这算不算bug：
![11](https://cloud.githubusercontent.com/assets/1335861/6934231/a16cabf6-d863-11e4-8cfc-73bc28f55f3c.png)
官网例子，用工具填上value，此时焦点不在控件上，也没有触发验证；
![22](https://cloud.githubusercontent.com/assets/1335861/6934259/25aa6ac0-d864-11e4-9da9-450c3e8ddeb7.png)
第一次点击提交，焦点出现在控件中，验证通过，但是表单没有提交，需要再点击一次才能正常提交表单

**总结**
就是在这种情况下，需要连续2次点击提交按钮，才能“正常”提交表单

**Comment by meowl** [comment]
现在项目正在用amazeui，累...

**Comment by meowl** [comment]
找了个办法，先判断控件值是否改变，改变后再ajax验证，绕过这个问题...

**Comment by Minwe** [comment]
表单在提交的时候会去验证每一个域，但 AJAX 验证是异步的，也就是说表单提交的时候使用 AJAX 验证的字段还是验证还没有完成，没有被标记为验证通过的，所以表单提交返回 `false`。

我们会考虑一下怎么处理表单提交前没有触发过验证状态情况。
