### ISSUE TITLE
tabs组件内表单字段，用鼠标选取内容时，会触发tabs切换

### ISSUE THREAD

**Issue by cos800** [allmobilize/amazeui#508]
**问题描述**

tabs组件内表单字段，用鼠标选取内容时，会触发tabs切换

**产生环境**

- 操作系统及版本：win7
- 浏览器及版本：chrome 41
- 演示地址：http://runjs.cn/detail/cncx73vo

**复现步奏**

选中输入框里的文字，就会触发tabs的切换效果了。

**Comment by Minwe** [comment]
选择时是触发 `swipeLeft` 事件，引起 Tab 切换，可以加上 `data-am-tabs="{noSwipe: 1}"` 把 swipe 功能禁用掉。

http://bin.amazeui.org/xakigu/1/edit?html,output

```html
<div class="am-tabs" data-am-tabs="{noSwipe: 1}">
...
</div>
```

**Comment by cos800** [comment]
那这不算一个Bug吗？

**Comment by Minwe** [comment]
触控事件不能处理得像鼠标事件那么精确，只能在触控和选择之间做一些取舍。

而且个人觉得在移动端让用户选择文本似乎体验也不太好。

**Comment by cos800** [comment]
好吧~ 谢谢

**Comment by cos800** [comment]
好吧~ 谢谢
