### ISSUE TITLE
Bug: 更新到2.3后，Tab组件无法使用

### ISSUE THREAD

**Issue by zjj1991729** [allmobilize/amazeui#513]
**问题描述**
之前是在2.2.1的基础上做的，今天更新到了2.3，目前发现之前正常的Tab组件无法使用，点击会出现/index.html#tab2这样的URL，之前是没有的。复制官方的案例代码到网页里面依然如此，替换回之前的JS文件一切正常
（描述一下问题）

**产生环境**
全部
- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：windows 7
- 浏览器及版本：chrome 38内核
- 演示地址：
http://www.ds100.net/demo/jd/  这里面是2.3演示地址，还有我之前头部的幻灯片也不显示了
http://www.ds100.net/demo/jd/index221.html 这个是2.2.1版本的正常状态

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 UBrowser/4.0.4627.3 Safari/537.36
```

**Comment by Minwe** [comment]
下载包里的和 CDN 上的我们都测试了，没发现你说的问题的。

2.3 中 Tabs 就是调整了一下选择符，如果你是复制官网的代码，按道理不会出问题。

你可以把 Tabs 部分的 HTML 贴出来我们看一下。

**Comment by zjj1991729** [comment]
http://www.ds100.net/demo/jd/ 这里面是演示地址，还有我之前头部的幻灯片也不显示了

**Comment by Minwe** [comment]
2.3 的 `.am-tabs-nav` 和 `.am-tabs-bd` 不能嵌套其他元素，必须是 `.am-tabs` 的相邻子级。

Tabs 报错，所以后面的 Slider 就没有正常执行了。
