### ISSUE TITLE
.am-img-responsive 引起的问题

### ISSUE THREAD

**Issue by rwmt** [allmobilize/amazeui#516]
> .am-img-responsive {
>   display: block;
>   ...
> }

`display:block;`添加在a标签里的img会导致该类元素上方含有浮动元素时的排版错误。

example.

	<div class="am-u-sm-12">
		<p class="am-fl">123</p>
		<div class="am-fr">
			bulabula
		</div>
		<a href=""><img class="am-img-responsive" src="" /></a>
	</div>

**Comment by Minwe** [comment]
怎么个错误法？请给出更完整的代码。 http://bin.amazeui.org/yujudu/1/edit?html,output

列外面应该始终有行包裹，列是浮动的，需要有清除浮动的元素。
```html
<div class="am-g">
      <div class="am-u-sm-12">
        <p class="am-fl">123</p>
        <div class="am-fr">
          bulabula
        </div>
        <a href=""><img class="am-img-responsive" src="http://www.bing.com/az/hprichbg/rb/OsakajoCherry_JA-JP10525241970_1920x1080.jpg" /></a>
      </div>
</div>
```

**Comment by rwmt** [comment]
囧rz。
抱歉，是我没有清除浮动，谢谢。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://depowertools.com/particular.php?au>

 

Again_moon@sohu.com
