### ISSUE TITLE
有没有只针对移动端的样式？就是从大而全的样式中剥离出来只针对移动端的？

### ISSUE THREAD

**Issue by agileago** [allmobilize/amazeui#517]
这样做的话体积应该会小很多，还是有方法构建没有？

**Comment by Minwe** [comment]
如果你只用到 http://amazeui.org/widgets 里面的东西，那可以读取 https://github.com/allmobilize/amazeui/tree/master/widget/ 目录下每个组件里面的 package.json，提取依赖的 JS 和 CSS，然后用这些信息构建一个，参考 https://github.com/allmobilize/amazeui/blob/v1.x/gulpfile.js。

后续我们应该会考虑独立出一个移动端的 UI。

**Comment by agileago** [comment]
谢谢，因为现在很多项目只针对移动端来做的，对体积会有一定的要求，amazeui现有的版本的路线是走的PC+移动，体积稍大，如果剥离出来一个amazeui-mobile，相信会降低不少体积，只针对640px一下的屏幕适配，那样的话我感觉用户量会猛增的，这样在技术选型的时候不会被人说体积太大，加载太慢而被抛弃掉。

**Comment by cnhans** [comment]
支持出分离后的h5版

**Comment by Minwe** [comment]
@agileago @cnhans 对于移动版框架，两位有什么更具体的考量（需求）可以大概说一下，给我们提供一些参考。

**Comment by agileago** [comment]
@Minwe 抱歉刚看到 最近在做微信端的项目 团队前端水平很差，但项目经理又要要求性能，页面加载速度，页面美观、大气（原谅我吧），又要保证开发进度，这个时候想到了amazeui提供的一套移动端组件(真的很不错，基本满足需求)，拿来改改就能用，但是当我用的时候发现加载三个基础文件好大，就有一个强烈的需求是能把那套移动端widget剥离出来提供个mobile版，但是官方好像没有提供，如果出个这个版本或者构建文档那最好了

**Comment by Minwe** [comment]
@agileago 可以按照 http://amazeui.org/customize 上面的说明定制。

**Comment by agileago** [comment]
要的就是这个 谢谢 @Minwe
