### ISSUE TITLE
Tabs组件跟easyui一起使用时，会产生冲突

### ISSUE THREAD

**Issue by linziguan** [allmobilize/amazeui#519]
跟easyui一起使用时，会产生冲突

**Comment by Minwe** [comment]
`$.fn.tabs` 同名导致，如果你要用 EasyUI 的，就把 Easy UI 的脚本放在 Amaze UI 的脚本之后。

**Comment by linziguan** [comment]
如果amazeui也提供layout这类组件就好了，我就不用easyui了，因为经常用到他的border Layout

**Comment by Minwe** [comment]
Layout 这类功能主要是用在后台管理界面上？

**Comment by linziguan** [comment]
是的

**Comment by Minwe** [comment]
https://github.com/allpro/layout 有独立的插件提供 layout 功能，演示 http://layout.jquery-dev.com/demos.cfm。

`layout` 这种实现方式现在应该是逐步被 SPA 替代了。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://mixmedia24.ru/supportive.php?vt>

 

Again_moon@sohu.com
