### ISSUE TITLE
Validator keyboardEvents 设置失效？

### ISSUE THREAD

**Issue by ucando** [allmobilize/amazeui#520]
**问题描述**

表单项目采用ajax异步验证，按照默认设置的话，用户每次输入一个字符都将产生一次异步调用，所以我将keyboardEvents设置成'focusout'，希望只有在用户离开输入框之后才验证。首次进入表单时，设置是有效的，只有用户离开焦点时才会产生验证。但是第二次再进入修改表单项目时，验证程序变成了默认设置，每输入一个字符都产生一次异步调用。

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：windows 7
- 浏览器及版本：chrome 41
- 演示地址：

**复现步奏**

1. 表单项目设置为异步验证
2. keyboardEvents配置为'focusout'
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36
```

**Comment by Minwe** [comment]
不是失效了，是里面针对验证失败的域绑定了一个 `keyup` 事件。

目前没有这个事件设置的接口，你可以先通过下面的代码把它禁用了：

```js
$('.am-form').off('keyup.validator.amui', '.am-active');
```
