### ISSUE TITLE
重新编译妹子出错

### ISSUE THREAD

**Issue by synchronizingtheworld** [allmobilize/amazeui#522]
![image](https://cloud.githubusercontent.com/assets/8369919/7198990/876eecb0-e523-11e4-9540-2faabafec92c.png)
为什么我把生成less源码的map文件放在位置1编译出错。放在位置2，编译不出错但是映射的less源文件不对呢？？？
报错截图：
![image](https://cloud.githubusercontent.com/assets/8369919/7199462/81a9cd50-e527-11e4-904b-e25bf707362c.png)

**Comment by Minwe** [comment]
sourcemap 用的什么模块？

**Comment by synchronizingtheworld** [comment]
用的是gulp的gulp-sourcemaps组件

**Comment by Minwe** [comment]
把 gulp-less 升级到 `3.0.2` 就没问题了，你试一下

**Comment by synchronizingtheworld** [comment]
![image](https://cloud.githubusercontent.com/assets/8369919/7223044/1415262c-e74d-11e4-84ca-51d557e33b4e.png)
![image](https://cloud.githubusercontent.com/assets/8369919/7223047/2d469982-e74d-11e4-95ef-3caff2be12f2.png)
还是有问题呢

**Comment by Minwe** [comment]
你只是改了版本号没有重新执行 `npm install` 吧？
看一下 `node_modules/gulp-less/package.json` 里面的版本是不是 `3.0.2`。

**Comment by synchronizingtheworld** [comment]
我重新执行了npm install gulp-less --save-dev命令  并且还重新执行了npm install gulp-sourcemaps --save-dev

**Comment by synchronizingtheworld** [comment]
代码我就添加了下面三hang行代码
![image](https://cloud.githubusercontent.com/assets/8369919/7223149/6d86977a-e74f-11e4-910e-69e1450204cf.png)
![image](https://cloud.githubusercontent.com/assets/8369919/7223171/c16b842c-e74f-11e4-850b-a92690ac34b8.png)

**Comment by Minwe** [comment]
按照你添加的代码，我这边能正常执行，请确认一下 `node_modules/gulp-less/package.json` 里面的版本号。

**Comment by synchronizingtheworld** [comment]
![image](https://cloud.githubusercontent.com/assets/8369919/7223307/a8c0ee60-e751-11e4-9ca7-b1554f98decd.png)

![image](https://cloud.githubusercontent.com/assets/8369919/7223323/fd871a6e-e751-11e4-8cd0-1a3f6f47d419.png)



好像没有哪里有问题

**Comment by Minwe** [comment]
应该加在 Minify 之后，对 minify 的文件建立 map 才有意义。Chrome 的调试工具是可以格式化 minify 之后的 CSS 的，所以 CSS 建立  map 没什么用。

![image](https://cloud.githubusercontent.com/assets/4370770/7223371/b9f3e3c6-e752-11e4-91d3-415bef482bc0.png)

`amazeui` 下面有一个 `node_modules` 的文件夹，看里面 `gulp-less` 文件里的 `package.json`。

![image](https://cloud.githubusercontent.com/assets/4370770/7223380/f1fd9870-e752-11e4-8823-94104be96795.png)

**Comment by synchronizingtheworld** [comment]
加在后面一开始我都说没有编译问题的  只是不能正确映射less源码。  不过现在把less插件升级成3.0.2版本好像less源码能正确映射了。

**Comment by Minwe** [comment]
那现在没问题了？

**Comment by synchronizingtheworld** [comment]
现在问题是解决了，只是有些不明白，为什么不能直接生成amazeui.css.map？  bootstrap就可以，只是它用的是grunt

**Comment by Minwe** [comment]
Gulp 和 Grunt 的工作原理不太一样。

gulp-sourcemaps  也需要插件支持 https://github.com/floridoo/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support，所以插件多了出问题的几率就大了。

你可以尝试直接使用 Less 的命令行编译 http://www.cnblogs.com/enix/p/3505610.html
