### ISSUE TITLE
用妹子UI开发了后台,里面使用到了标签页套了一个表单,会有手势干扰

### ISSUE THREAD

**Issue by mejuneyy** [allmobilize/amazeui#525]
用妹子UI开发了后台,里面使用到了标签页套了一个表单,会有手势干扰,
在输入框,选择内容删除的时候,会触发左右手势,
后台是电脑web,不需要手势,如何关掉手势?

**Comment by Minwe** [comment]
http://amazeui.org/javascript/tabs?_ver=2.x#%E7%A6%81%E7%94%A8%E8%A7%A6%E6%8E%A7%E6%93%8D%E4%BD%9C

```html
<div class="am-tabs" data-am-tabs="{noSwipe: 1}">
```

**Comment by mejuneyy** [comment]
谢谢
