### ISSUE TITLE
页面切换效果如何实现？

### ISSUE THREAD

**Issue by ffzhihua** [allmobilize/amazeui#527]
**问题描述**

（描述一下问题）

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36
```
http://amazeui.org/widgets/m?_ver=2.x

想要这个特效怎么都弄不出来，也没有demo代码，实在是费劲，一个好的APP，这种特效是必要的

**Comment by Minwe** [comment]
演示页面只有两个 View，所以使用简单的代码的 CSS 代码就能实现。
如果是页面比较多的 App，需要使用有 Router 功能的前端框架来管理页面视图。
