### ISSUE TITLE
Bug: input type为number时，自定义验证失效

### ISSUE THREAD

**Issue by ucando** [allmobilize/amazeui#528]
**问题描述**

根据需要自定义了一个手机验证规则

```
<script>
if ($.AMUI && $.AMUI.validator) {
      $.AMUI.validator.patterns.mobile = /^\s*1\d{10}\s*$/;
}
</script>
<input type="number" class="js-pattern-mobile" required>
```

测试时发现程序会验证required，但不会验证自定义的规则。将type改为text后，规则可以正常验证。

**产生环境**

- 操作系统及版本：win7
- 浏览器及版本：chrome 41

**Comment by Minwe** [comment]
`type="number"` 的输入框会应用内置的正则，忽略掉用户设置的规则。

```html
<form action="" data-am-validator="{H5inputType: ['email', 'url']}" class="am-form">
```

或者

```js
$('form').validator({
  H5inputType: ['email', 'url']
});
```

根据 H5 规范，信用卡号、手机号这种类型的输入并不推荐使用 `number`，而是建议使用 text + pattern 的形式。

https://html.spec.whatwg.org/multipage/forms.html#number-state-(type=number)

**Comment by Minwe** [comment]
http://bin.amazeui.org/mawage/1/edit
