### ISSUE TITLE
组件使用 Handlebars 渲染后事件失效？

### ISSUE THREAD

**Issue by KingST1230** [allmobilize/amazeui#531]
**问题描述**
关于Accordion折叠组件，用handlebar.js将json赋值给组件。如果以上的赋值代码放在<script></script>标签中，可以正常显示和点击。但是放在jquery的ready( )方法内，则只能显示出UI，折叠版的点击收缩与展开功能就失效了。经调试，发现am-accordion-title的click方法没有了。
不知道是我的代码写的有问题还是确实有该bug。
---------------------------------------------------------
**产生环境**
web
---------------------------------------------------------
**复现步奏**
1. 
<script type="text/x-handlebars-template" id="my-tpl">
  {{>accordion accordionData}}
</script>
2. 
$(function() {
  var $tpl = $('#my-tpl'),
      tpl = $tpl.text(),
      template = Handlebars.compile(tpl),
      data = {
        accordionData: {
          "theme": "basic",
          "content": [
            {
              "title": "标题一",
              "content": "内容一",
              "active": true
            },
            {
              "title": "标题二",
              "content": "内容二"
            },
            {
              "title": "标题三",
              "content": "内容三"
            }
          ]
        }
      },
      html = template(data);

  $tpl.before(html);
});

**Comment by Minwe** [comment]
默认的事件在 ready 的时候初始化，ready 里面渲染 DOM 渲染赶不上默认的初始化事件了，你可以收到执行初始化：

https://github.com/allmobilize/amazeui/blob/master/docs/examples/widget.html#L386-L389

参考 #356 

其实不用放在 ready 里面也可以。

**Comment by KingST1230** [comment]
问题解决了，长知识了。谢谢！
