### ISSUE TITLE
妹子项目release的构建流程是怎样的呢？

### ISSUE THREAD

**Issue by jiangyuhe123** [allmobilize/amazeui#537]
比如我依赖妹子做了一个项目，现在有很多html和js等文件，我需要把它们打成一个安装包，或者发布到appstore里面，能分享一些这样的流程和经验么？ 毕竟项目最后还是要经过这样一个关键环节，成不成功也看最后了。
有什么好的流程和妹子需要特殊处理和注意的地方么？开发过程中用到的构建工具比如npm和gulp的文件可以扔掉了吧？能不能做一个打包的组件去除不必要的文件呢？

谢谢

**Comment by Minwe** [comment]
就前端而言，NPM 和 Gulp 只是辅助开发的工具，产品环境只需要保留最终构建出来的文件即可。
