### ISSUE TITLE
小的建议，不是bug. 

### ISSUE THREAD

**Issue by msdlisper** [allmobilize/amazeui#538]
我在查看文档示例文件时，发现widget.html里的这句代码本可以不写的
<pre><code>
$.each(['slider', 'menu', 'gallery', 'footer', 'navbar'], function(i, m) {
      var module = $.AMUI[m];
      // module && module.init && module.init();
    })
</code></pre>

我看了下妹子的源码，是加载amazeui.js后给每个模块注册read事件，但注册的方式不一样，有的是$(function(){init();}),有的是$(document).on('ready',init);
我建议把这种方式都统一成后者的写法，就不用那句多余的代码了（测试了的），分析了一下原因;
 因为widget.html是以组件的方式加载文档，前者的方式在dom加载完后,这时handerjs的编译的html文本还没有插入，就调用init,。而用后者注册时，会等handerjs的编译的html文本插入完全后再调用init()

**Comment by Minwe** [comment]
https://api.jquery.com/ready/

There is also `$(document).on( "ready", handler )`, **deprecated as of jQuery 1.8**. This behaves similarly to the ready method but if the ready event has already fired and you try to `.on( "ready" )` the bound handler will not be executed. Ready handlers bound this way are executed after any bound by the other three methods above.

 `$(document).on( "ready", handler )` 是一个废弃的语法，而且和 `$(function() {})`/`$(document.ready(funciton() {}))` 没有本质上的区别。之所以**表面上**看着 ` $(document).on( "ready", handler )` 免去了渲染、插入 DOM 以后初始化接口，可能是由于在等待 `$(function() {})` 里面的队列完成。

所以这也不是一个靠谱的方法。

**Comment by Minwe** [comment]
- http://stackoverflow.com/questions/13589307/what-is-the-difference-between-document-readyinitialize-and-document-on
- http://stackoverflow.com/questions/19408082/differences-between-document-readyfunction-and-document-onready

**Comment by msdlisper** [comment]
不管怎样，用web组件的时候再<pre>
$.each(['slider', 'menu', 'gallery', 'footer', 'navbar'], function(i, m) {
      var module = $.AMUI[m];
      // module && module.init && module.init();
    })
</pre>
都两次执行了初始化的代码，不是个好方法啊

**Comment by Minwe** [comment]
已经将废弃的 `on('ready')` 语法统一替换。

其实手动初始化这个步骤是可以规避，只要在 DOM ready 之前渲染组件并插入到文档中就行。

比如把 Handlebars 的渲染逻辑移到 `$(function(){ });` 外面，要更可靠一点的话就把 `amazeui.js` 放在渲染逻辑之后加载。

https://github.com/allmobilize/amazeui/blob/b2ceea78c4d6e10e8f73526c8429103d51b212eb/docs/examples/widget.html
