### ISSUE TITLE
新手上路编译问题

### ISSUE THREAD

**Issue by jiangyuhe123** [allmobilize/amazeui#539]
我把 landing.html 和相应的js css image等资源文件放到starter kit项目中，然后cmd运行npm install
gulp serve，发生编译错误，求解。谢谢

error log:
E:\git\starter-kit>gulp serve
[21:27:46] Using gulpfile E:\git\starter-kit\gulpfile.js
[21:27:46] Starting 'default'...
[21:27:46] Starting 'clean'...
[21:27:46] Finished 'clean' after 14 ms
[21:27:46] Starting 'styles'...
[21:27:47] Starting 'jshint'...
[21:27:47] Starting 'html'...
[21:27:47] Starting 'images'...
[21:27:48] Starting 'copy'...
[21:27:48] Starting 'browserify'...
[21:27:48] Finished 'browserify' after 1.6 ms

E:\git\starter-kit\app\js\amazeui.min.js
  line 1  col 118    Line is too long.
  line 2  col 8912   This character may get silently deleted by one or more browsers.
  line 2  col 32009  Line is too long.
  line 2  col 20     Missing "use strict" statement.
  line 2  col 72     Strings must use singlequote.
  line 2  col 107    Expected '{' and instead saw 'return'.
  line 2  col 127    Expected '{' and instead saw 'return'.
  line 2  col 180    Strings must use singlequote.
  line 2  col 186    Strings must use singlequote.
  line 2  col 200    Missing semicolon.
  line 2  col 219    Strings must use singlequote.
  line 2  col 200    Expected an identifier and instead saw '='.
  line 2  col 201    Missing semicolon.
  line 2  col 221    Missing semicolon.
  line 2  col 313    Missing semicolon.
  line 2  col 335    Missing semicolon.
  line 2  col 355    Missing semicolon.
  line 2  col 376    Strings must use singlequote.
  line 2  col 421    Expected '{' and instead saw 'o'.
  line 2  col 437    Missing semicolon.
  line 2  col 439    Wrap an immediate function invocation in parens to assist the reader in underst
anding that the expression is the result of a function, and not the function itself.
  line 2  col 457    Missing "use strict" statement.
  line 2  col 482    Strings must use singlequote.
  line 2  col 564    Strings must use singlequote.
  line 2  col 592    Strings must use singlequote.
  line 2  col 616    Strings must use singlequote.
  line 2  col 640    Strings must use singlequote.
  line 2  col 719    Strings must use singlequote.
  line 2  col 770    Strings must use singlequote.
  line 2  col 858    Strings must use singlequote.
  line 2  col 904    Strings must use singlequote.
  line 2  col 927    Strings must use singlequote.
  line 2  col 981    Strings must use singlequote.
  line 2  col 1029   Strings must use singlequote.
  line 2  col 1051   Strings must use singlequote.
  line 2  col 1069   Strings must use singlequote.
  line 2  col 1071   Missing semicolon.
  line 2  col 1073   Missing semicolon.
  line 2  col 1075   Missing semicolon.
  line 2  col 1086   Strings must use singlequote.
  line 2  col 1105   Strings must use singlequote.
  line 2  col 1124   Strings must use singlequote.
  line 2  col 1165   Strings must use singlequote.
  line 2  col 1215   Missing semicolon.
  line 2  col 1261   Strings must use singlequote.
  line 2  col 1269   Missing semicolon.
  line 2  col 1293   Strings must use singlequote.
  line 2  col 1327   Strings must use singlequote.
  line 2  col 1357   Strings must use singlequote.
  line 2  col 1383   Missing semicolon.
  line 2  col 1383   Too many errors. (25% scanned).

  ×  4 errors
  ‼  47 warnings

E:\git\starter-kit\app\js\jquery.min.js
  line 1  col 82     Line is too long.
  line 2  col 32012  Line is too long.
  line 2  col 24     Strings must use singlequote.
  line 2  col 24     Missing semicolon.
  line 2  col 24     Missing "use strict" statement.
  line 2  col 24     Expected an identifier and instead saw '=='.
  line 2  col 26     Expected an operator and instead saw 'typeof'.
  line 2  col 32     Missing semicolon.
  line 2  col 49     Strings must use singlequote.
  line 2  col 134    Expected '{' and instead saw 'throw'.
  line 2  col 192    Strings must use singlequote.
  line 2  col 205    Missing semicolon.
  line 2  col 211    Missing semicolon.
  line 2  col 224    Strings must use singlequote.
  line 2  col 213    Wrap an immediate function invocation in parens to assist the reader in underst
anding that the expression is the result of a function, and not the function itself.
  line 2  col 266    Missing "use strict" statement.
  line 2  col 381    Strings must use singlequote.
  line 2  col 423    Missing semicolon.
  line 2  col 529    Missing semicolon.
  line 2  col 583    Strings must use singlequote.
  line 2  col 631    Missing semicolon.
  line 2  col 660    Use '!==' to compare with 'null'.
  line 2  col 708    Missing semicolon.
  line 2  col 817    Missing semicolon.
  line 2  col 861    Missing semicolon.
  line 2  col 946    Missing semicolon.
  line 2  col 949    Missing semicolon.
  line 2  col 1014   Missing semicolon.
  line 2  col 1050   Missing semicolon.
  line 2  col 1086   Missing semicolon.
  line 2  col 1181   Missing semicolon.
  line 2  col 1244   Missing semicolon.
  line 2  col 1390   Strings must use singlequote.
  line 2  col 1439   Strings must use singlequote.
  line 2  col 1503   Expected '{' and instead saw 'if'.
  line 2  col 1510   Use '!==' to compare with 'null'.
  line 2  col 1529   Expected '{' and instead saw 'for'.
  line 2  col 1540   Expected '{' and instead saw 'c'.
  line 2  col 1721   Missing semicolon.
  line 2  col 1749   Strings must use singlequote.
  line 2  col 1784   Strings must use singlequote.
  line 2  col 1833   Missing semicolon.
  line 2  col 1892   Strings must use singlequote.
  line 2  col 1904   Missing semicolon.
  line 2  col 1960   Use '!==' to compare with 'null'.
  line 2  col 1977   Missing semicolon.
  line 2  col 2040   Missing semicolon.
  line 2  col 2082   Strings must use singlequote.
  line 2  col 2187   Strings must use singlequote.
  line 2  col 2194   Missing semicolon.
  line 2  col 2194   Too many errors. (40% scanned).

  ×  5 errors
  ‼  46 warnings

[21:27:49] 'jshint' errored after 1.76 s
[21:27:49] Error in plugin 'gulp-jshint'
Message:
    JSHint failed for: E:\git\starter-kit\app\js\amazeui.min.js, E:\git\starter-kit\app\js\jquery.mi
n.js
[21:27:49] 'default' errored after 2.32 s
[21:27:49] Error: [object Object]
    at formatError (C:\Users\michael\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (C:\Users\michael\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:195:15)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (E:\git\starter-kit\node_modules\gulp\node_modules\orchestrat
or\index.js:264:8)
    at E:\git\starter-kit\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (E:\git\starter-kit\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (E:\git\starter-kit\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:29:3)
    at finish (E:\git\starter-kit\node_modules\run-sequence\index.js:53:5)
    at Gulp.onError (E:\git\starter-kit\node_modules\run-sequence\index.js:60:4)
    at Gulp.emit (events.js:129:20)
    at Gulp.Orchestrator._emitTaskDone (E:\git\starter-kit\node_modules\gulp\node_modules\orchestrat
or\index.js:264:8)
    at E:\git\starter-kit\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (E:\git\starter-kit\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at DestroyableTransform.<anonymous> (E:\git\starter-kit\node_modules\gulp\node_modules\orchestra
tor\lib\runTask.js:52:4)
    at DestroyableTransform.f (E:\git\starter-kit\node_modules\gulp\node_modules\orchestrator\node_m
odules\end-of-stream\node_modules\once\once.js:17:25)
    at DestroyableTransform.emit (events.js:129:20)
[21:27:49] 'styles' all files 224 B
[21:27:49] Finished 'styles' after 2.34 s
[21:27:49] 'i' all files 7.93 kB
[21:27:49] Finished 'images' after 1.6 s
[21:27:49] 'html' all files 9.91 kB
[21:27:49] Finished 'html' after 1.92 s
[21:27:49] 'copy' all files 3.47 MB
[21:27:49] Finished 'copy' after 651 ms

**Comment by Minwe** [comment]
这不是错误，只是 JSHint 校验代码格式没通过。你可以忽略掉。

压缩以后的代码不建议放在 `app/js` 下面。
