### ISSUE TITLE
bug:js插件中iScroll插件在安卓自带浏览器中超链不能点击跳转

### ISSUE THREAD

**Issue by HeChangGG** [allmobilize/amazeui#540]
**问题描述**
js插件中iScroll插件在安卓自带浏览器中超链不能点击跳转

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）三星手机 型号：GT-I9100
- 操作系统及版本：Android 4.4.4
- 浏览器及版本：
- 演示地址：http://amazeui.org/examples/iscroll.html

**复现步奏**

1. 访问http://amazeui.org/examples/iscroll.html
2. 点击标题超链
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; rv:36.0) Gecko/20100101 Firefox/36.0
```

**Comment by Minwe** [comment]
提 Issue 之前请先查看文档：

http://amazeui.org/javascript/iscroll-lite#%E4%BD%BF%E7%94%A8-iscroll-%E4%BB%A5%E5%90%8E%E9%93%BE%E6%8E%A5%E6%97%A0%E6%B3%95%E7%82%B9%E5%87%BB%EF%BC%9F

**Comment by HeChangGG** [comment]
sorry,未看完整,请更新下载实例中的初始化参数。




------------------ 原始邮件 ------------------
发件人: "notifications";<notifications@github.com>;
发送时间: 2015年4月29日(星期三) 上午9:43
收件人: "allmobilize/amazeui"<amazeui@noreply.github.com>; 
抄送: "訸暢"<295372901@QQ.COM>; 
主题: Re: [amazeui] bug:js插件中iScroll插件在安卓自带浏览器中超链不能点击跳转 (#540)




提 Issue 之前请先查看文档：
 
http://amazeui.org/javascript/iscroll-lite#%E4%BD%BF%E7%94%A8-iscroll-%E4%BB%A5%E5%90%8E%E9%93%BE%E6%8E%A5%E6%97%A0%E6%B3%95%E7%82%B9%E5%87%BB%EF%BC%9F

**Comment by Minwe** [comment]
iOS 不加那个选项也可以点击，安卓上奇葩浏览器太多了。
