### ISSUE TITLE
请问妹子与bootstrap 还有knockout.js 冲突么

### ISSUE THREAD

**Issue by jiangyuhe123** [allmobilize/amazeui#541]
得知妹子知识一个view层快速开发框架，我打算把knockout.js 引入到自己的项目来处理view logic。另外发现bootstrap一些功能也不错，请问妹子和 bootstrap，knockout冲突么

**Comment by Minwe** [comment]
JS 插件有几个命名上和 BootStrap 有冲突，比如 Alert、Button、Modal；Knockout.js 没试过，应该不会有什么冲突。

**Comment by jiangyuhe123** [comment]
Thanks, let me try it.
