### ISSUE TITLE
如何测试？

### ISSUE THREAD

**Issue by liyatang** [allmobilize/amazeui#549]
你好，我打算基于amazeui做二次开发。 但是把github的包down下来之后，构建后。发现没有提供测试页面。
那么问题来了，我怎么测试我的改动？ 例如最基本的，我改了@one-primary: #15afef的色值，怎么测试效果呢。
谢大神，坐等答案...555

**Comment by Minwe** [comment]
项目中目前没有包含测试页面的代码。你可以自行解析 `docs` 里面的文档来预览效果。

后续会补上这部分代码，不过要到下月才有空弄这个。

**Comment by liyatang** [comment]
3q
