### ISSUE TITLE
Web 组件中的图片轮播在iPhone Safari 中闪一下就消失了

### ISSUE THREAD

**Issue by nextoneme** [allmobilize/amazeui#551]
**问题描述**

（描述一下问题）

**产生环境**

- 设备：iPhone 5s
- 操作系统及版本：ios7
- 浏览器及版本：测试过QQ浏览器，safari，和微信内置webview都是如此
- 演示地址：

**复现步奏**

1. 
2. 
...

**Comment by Minwe** [comment]
你是使用官网的查看的么？还是自己写的页面？

**Comment by nextoneme** [comment]
自己写的页面，代码如下
<!doctype html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>首页</title>
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="stylesheet" href="__PUBLIC__/AmazeUI-2.3.0/assets/css/amazeui.min.css">
  <link rel="stylesheet" href="__PUBLIC__/AmazeUI-2.3.0/assets/css/app.css">
</head>
<body>
  <div class="am-container-fluid">
     <div class="advertisement">
		
		<div data-am-widget="slider" class="am-slider am-slider-c1" data-am-slider='{&quot;directionNav&quot;:false}'>
		  <ul class="am-slides">
		    <volist name="activity" id="v">
  		    <li>
		      <a href="{$v.url}">
  		      	<img src="__ROOT__/{$v.pic}">
		      </a>
  		      <div class="am-slider-desc">{$v.title}</div>
  		    </li>
        		</volist>
		  </ul>
		</div>
     </div>
     
     
	<ul class="am-list am-list-static am-list-border">
	  <li>
	  	<a href="{:U('Product/index')}" class="am-text-truncate">
		  	<i class="am-icon-users   am-icon-fw"></i>
		  		导航一
		    <i class="am-icon-chevron-right am-fr"></i>
	  	</a>
	  </li>
	  <li>
	  	<a href="{:U('Museum/index')}" class="am-text-truncate">
		  	<i class="am-icon-map-marker am-icon-sm am-icon-fw"></i>
		  		导航二
		    <i class="am-icon-chevron-right am-fr"></i>
	  	</a>
	  </li>
	  <li>
	  	<a href="{:U('Forum/index')}" class="am-text-truncate">
		  	<i class="am-icon-yelp   am-icon-fw"></i>
		  		导航二
		    <i class="am-icon-chevron-right am-fr"></i>
	  	</a>
	  </li>
	  <li>
	  	<a href="{:U('Infor/index')}" class="am-text-truncate">
		  	<i class="am-icon-paper-plane    am-icon-fw"></i>
		  		导航三
		    <i class="am-icon-chevron-right am-fr"></i>
	  	</a>
	  </li>
	  <li>
		<button class="am-btn am-btn-secondary am-fr am-round am-btn-sm" href="#">
		  <i class="am-icon-mail-forward"></i>
		  导航四
		</button>
	  </li>
	</ul>
	<div class="am-cf "></div>
     
  <input type="hidden" value="{$mapPoint[0].city}" id="city">
  <input type="hidden" value="{$mapPoint[0].adds}" id="adds">
  
  
  <div id="l-map">
  </div>
  
 </div>


<div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default "
     id="">
  <ul class="am-navbar-nav am-cf am-avg-sm-4">
    <li class="nav-cur" >
      <a href="{:U('Homes/index')}">
        <span class="am-icon-home"></span>
        <span class="am-navbar-label">菜单一</span>
      </a>
    </li>
    <li>
      <a href="{:U('Product/index')}">
        <span class="am-icon-forumbee"></span>
        <span class="am-navbar-label">菜单二</span>
      </a>
    </li>
    <li>
      <a href="{:U('Search/index')}">
        <span class="am-icon-search"></span>
        <span class="am-navbar-label">菜单三</span>
      </a>
    </li>
    <li>
      <a href="{:U('Usercenter/index')}">
        <span class="am-icon-user"></span>
        <span class="am-navbar-label">菜单四</span>
      </a>
    </li>
  </ul>
</div>

<script src="__PUBLIC__/AmazeUI-2.3.0/assets/js/jquery.min.js"></script>
<script src="__PUBLIC__/AmazeUI-2.3.0/assets/js/amazeui.min.js"></script>
<script type="text/javascript" src="http://api.map.baidu.com/api?type=quick&ak=21d1bb28558331ec3ef47b6eb4d567e9&v=1.0"></script>
<script src="__PUBLIC__/AmazeUI-2.3.0/assets/js/app.js"></script>
<script>getPoint()</script>
</body>
</html>

**Comment by nextoneme** [comment]
自己写的页面，代码如下
```
<!doctype html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>首页</title>
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp" />
  <link rel="stylesheet" href="__PUBLIC__/AmazeUI-2.3.0/assets/css/amazeui.min.css">
  <link rel="stylesheet" href="__PUBLIC__/AmazeUI-2.3.0/assets/css/app.css">
</head>
<body>
  <div class="am-container-fluid">
     <div class="advertisement">
		<!-- Slider -->
		<div data-am-widget="slider" class="am-slider am-slider-c1" data-am-slider='{&quot;directionNav&quot;:false}'>
		  <ul class="am-slides">
		    <volist name="activity" id="v">
  		    <li>
		      <a href="{$v.url}">
  		      	<img src="__ROOT__/{$v.pic}">
		      </a>
  		      <div class="am-slider-desc">{$v.title}</div>
  		    </li>
        		</volist>
		  </ul>
		</div>
     </div>
     
     <!--Index Nav-->
	<ul class="am-list am-list-static am-list-border">
	  <li>
	  	<a href="{:U('Product/index')}" class="am-text-truncate">
		  	<i class="am-icon-users   am-icon-fw"></i>
		  		导航一
		    <i class="am-icon-chevron-right am-fr"></i>
	  	</a>
	  </li>
	  <li>
	  	<a href="{:U('Museum/index')}" class="am-text-truncate">
		  	<i class="am-icon-map-marker am-icon-sm am-icon-fw"></i>
		  		导航二
		    <i class="am-icon-chevron-right am-fr"></i>
	  	</a>
	  </li>
	  <li>
	  	<a href="{:U('Forum/index')}" class="am-text-truncate">
		  	<i class="am-icon-yelp   am-icon-fw"></i>
		  		导航二
		    <i class="am-icon-chevron-right am-fr"></i>
	  	</a>
	  </li>
	  <li>
	  	<a href="{:U('Infor/index')}" class="am-text-truncate">
		  	<i class="am-icon-paper-plane    am-icon-fw"></i>
		  		导航三
		    <i class="am-icon-chevron-right am-fr"></i>
	  	</a>
	  </li>
	  <li>
		<button class="am-btn am-btn-secondary am-fr am-round am-btn-sm" href="#">
		  <i class="am-icon-mail-forward"></i>
		  导航四
		</button>
	  </li>
	</ul>
	<div class="am-cf "></div>
   <!--//input hidden data-->  
  <input type="hidden" value="{$mapPoint[0].city}" id="city">
  <input type="hidden" value="{$mapPoint[0].adds}" id="adds">
  
  <!--baidu map artical-->
  <div id="l-map">
  </div>
  
 </div>

<!-- Navbar -->
<div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default "
     id="">
  <ul class="am-navbar-nav am-cf am-avg-sm-4">
    <li class="nav-cur" >
      <a href="{:U('Homes/index')}">
        <span class="am-icon-home"></span>
        <span class="am-navbar-label">菜单一</span>
      </a>
    </li>
    <li>
      <a href="{:U('Product/index')}">
        <span class="am-icon-forumbee"></span>
        <span class="am-navbar-label">菜单二</span>
      </a>
    </li>
    <li>
      <a href="{:U('Search/index')}">
        <span class="am-icon-search"></span>
        <span class="am-navbar-label">菜单三</span>
      </a>
    </li>
    <li>
      <a href="{:U('Usercenter/index')}">
        <span class="am-icon-user"></span>
        <span class="am-navbar-label">菜单四</span>
      </a>
    </li>
  </ul>
</div>
<script src="__PUBLIC__/AmazeUI-2.3.0/assets/js/jquery.min.js"></script>
<script src="__PUBLIC__/AmazeUI-2.3.0/assets/js/amazeui.min.js"></script>
<script type="text/javascript" src="http://api.map.baidu.com/api?type=quick&ak=21d1bb28558331ec3ef47b6eb4d567e9&v=1.0"></script>
<script src="__PUBLIC__/AmazeUI-2.3.0/assets/js/app.js"></script>
<script>getPoint()</script>
</body>
</html>
```

**Comment by nextoneme** [comment]
另外在amaze官网文档里的这个图片画廊下面评论中也有其他朋友反馈过这个问题，我见你们未与回复所以到这儿给反馈了

**Comment by ywt0803** [comment]
话说这个邮件怎么发我了？？？






在 2015-05-11 15:06:42，"Vier" <notifications@github.com> 写道：


另外在amaze官网文档里的这个图片画廊下面评论中也有其他朋友反馈过这个问题，我见你们未与回复所以到这儿给反馈了

**Comment by Minwe** [comment]
@ywt0803 可能是 GitHub 通知系统有 Bug。

@nextoneme 你把下面那个改一下试试：

```
 <div data-am-widget="slider" class="am-slider am-slider-c1" data-am-slider='{"directionNav": false}'>
```

**Comment by nextoneme** [comment]
@Minwe 正中靶心，问题已解决！Thankyou！另外不明白你们单独对这个参数做引号转义的目的，虽然在安卓上可以正常解析，但是在safari下会有问题。所以官网文档上可以做适当修正。

**Comment by Minwe** [comment]
@nextoneme 其实是应该不转义的，那个是 handlebars 高亮代码渲染出来自动转义了，暂时没有找到好的方法处理，回头会在文档上加一个说明。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://vip-games.cf/passenger.php?3v>

 

Again_moon@sohu.com
