### ISSUE TITLE
建议：JS 插件 下拉选框 只能用 attr() 改变选中值，不能用 prop()，能否改进下呢？

### ISSUE THREAD

**Issue by yxzblue** [allmobilize/amazeui#552]
看了页面上例子 1.10，看到是用的 `attr()` 来动态改变选中值，亲试后，发现 `prop()` 却不行。

```js
if (action === 'toggle') {
    $o.attr('selected', !$o.get(0).selected);
}
```

最近正好有了解到 `prop()`。应该也可以通过 `prop()` 来动态地改变选中的值才对吧，当然现在用 `attr()` 也能达到要的效果，只是提个建议

**Comment by Minwe** [comment]
值是可以改变的，但注意看注释：

```js
// 使用 `attr()` 可以被 MutationObserver 观察到
$('select').find('option').eq(1).attr('selected', true);

// 以下操作不会被 MutationObserver 观察到
$('select').val('aa');
$('select').find('option').eq(1).prop('selected', true);
$('select').find('option')(1).selected = true;
```

动态设置值以后，需要重新渲染交互的下拉菜单，使用 `attr()` 的话 MutationObserver 可以观察到 DOM 变化，自动去渲染。

**使用 `prop` 设置不会被 MutationObserver 观察到**，需要手动去触发 `changed.selected.amui` 事件执行重新渲染。
