### ISSUE TITLE
有amazeui和datatables结合的例子吗？

### ISSUE THREAD

**Issue by cxjava** [allmobilize/amazeui#553]
有amazeui和datatables结合的例子吗？

不知道datatables的css和amazeui的css兼容不？

**Comment by meowl** [comment]
...碰到同好了...datatables本身是支持bootstrap样式的
你自己试一下，大部分可以兼容，目前发现的问题是：
1.thead和tfoot在top和bottom各会多一条border，可以通过css修正
2.分页（上一页下一页页数）样式需要自己写
3.datatables的横向滚动条在使用时可能出现thead与tbody中的列对不齐问题，这个目前没解决

**Comment by cxjava** [comment]
@meowl 多谢提醒！！ 你说的第3个问题不知道在这个http://www.zi-han.net/theme/hplus/table_data_tables.html 里面是不是已经解决了，我目测第一，第二个问题在上面的URL里面已经解决了。

**Comment by meowl** [comment]
你的链接里是使用的dataTables.bootstrap.css和dataTables.bootstrap.js，如果不用bootstrap样式，全部使用amazeui的话，就会出现上面的问题

**Comment by Minwe** [comment]
谢谢反馈。常用的插件我们会陆续增加样式适配。

**Comment by Minwe** [comment]
实现方式参考

https://github.com/DataTables/Plugins/tree/master/integration/bootstrap/3

**Comment by cxjava** [comment]
@Minwe 多谢！

**Comment by Minwe** [comment]
@cxjava 我们这两天会处理这个东西，你要是不着急用的话可以等着我们的版本。

**Comment by Minwe** [comment]
集成了一下，两位可以试用一下 https://github.com/amazeui/datatables

**Comment by xfworld** [comment]
我也来试试

**Comment by Minwe** [comment]
各位使用中有什么问题可以到 https://github.com/amazeui/datatables 反馈，我们会不断完善。

**Comment by cxjava** [comment]
好的，谢谢！
