### ISSUE TITLE
Slider 使用时出现空白页

### ISSUE THREAD

**Issue by feichangtutu** [allmobilize/amazeui#559]
**问题描述**

轮播产生两个空页，圆点数目不一致

**产生环境**
线上用php后
- 设备：（手机、平板等移动设备时填写此项）
WAP&PC端
- 操作系统及版本：
WIN7&WIN8&iOS
- 浏览器及版本：
ALL
- 演示地址：
本地测试代码ok，网页地址：http://dev.8mbang.com/newpage/piclib.html
上线后用过php，出现问题，不知是否和php有关，问题页面： http://www.8mbang.com/?q=pic%2Flist
**复现步骤*

1. 本地纯html代码显示页面正常
2、用php后出现问题，但是不确定是php引起的问题

**Comment by feichangtutu** [comment]
问题代码 

<div data-am-widget="slider" class="am-slider am-slider-a1 pic-lib-slides am-show-lg-only"
     data-am-flexslider="{controlNav: true,slideshow: true, slideshowSpeed: 3000,pauseOnAction: true,pauseOnHover:true }" data-am-slider='{}'>
    <ul class="am-slides">
        slide1
       <?php foreach($hot as $pic):?>
        <li>
            <div class="image-part am-u-sm-8 ">
                <a href="<?php echo url(array('pic/show','id'=>$pic['id']))?>" target="_blank"><img src="<?php echo $pic['coverurl'];?>" style="height:400px;"></a>             
            </div>
            <div class=" am-u-sm-4" style="margin-top: 30px;">
				<div class="slide-pic-title am-slider-desc">
					<a href="<?php echo url(array('pic/show','id'=>$pic['id']))?>" target="_blank">
						<?php echo $pic['title'];?>
					</a>
				</div>
                <div class="slide-contents">
				<?php echo $pic['summary'];?>
				<div>
            </div>
        </li>
      <?php endforeach?>        
    </ul>
    <div class="left-shadow"></div>
    <div class="right-shadow"></div>
</div>

**Comment by feichangtutu** [comment]
问题代码：
![1](https://cloud.githubusercontent.com/assets/8478315/7585187/85fdcbc4-f8d5-11e4-853e-ab06aa1936a7.png)

本地ok纯html代码
![2](https://cloud.githubusercontent.com/assets/8478315/7585241/ab4cebbc-f8d5-11e4-924f-9c8695699d4e.png)

**Comment by Minwe** [comment]
![image](https://cloud.githubusercontent.com/assets/4370770/7602537/2eff0620-f958-11e4-8b68-3a5a4a2e1f94.png)

你引入了两次 Amaze UI 的脚本，可以删掉一个：

```html
  <script src="vendor/js/jquery-1.11.1.js" type="text/javascript"></script>
  <script src="vendor/js/lazyload.min.js"  type="text/javascript"></script>
  <link rel="shortcut icon" type="image/ico" href="images/common/favicon.ico">
﻿<!--[if (gte IE 9)|!(IE)]><!-->
<script src="vendor/js/amazeui.js"></script>
<!--<![endif]-->

<!--[if lt IE 9]>
<script src="vendor/js/modernizr-2.8.3.js"></script>
<script src="vendor/polyfill/rem.min.js"></script>
<script src="vendor/polyfill/respond.min.js"></script>
<script src="vendor/js/amazeui.legacy.min.js"></script>
<![endif]-->
```

我这再检查一下初始化逻辑。

下面这个也可以改一下：

```html
<div data-am-widget="slider" class="am-slider am-slider-a1 pic-lib-slides" 
data-am-slider='{controlNav: true,slideshow: true, slideshowSpeed: 5000,pauseOnAction: true,pauseOnHover:true }'>
```

**Comment by Minwe** [comment]
@feichangtutu 请问按照上面的修改以后，问题是否已经解决？

**Comment by synchronizingtheworld** [comment]
关于slider组件我提两个问题。
1，样式问题：手机上用QQ浏览器，方向控制器会有bug，这个问题我自己修复了。
2，我把这个组件重新改造了一下，以便于下面的控制视图来自定义出slider。
我改造的方式是修改样式问题。但问题出来了，缩略图控制器的图片显示不出来了。

![image](https://cloud.githubusercontent.com/assets/8369919/7745581/e7667f5e-ffde-11e4-9dbd-36f2c90bd3ce.png)

**Comment by Minwe** [comment]
@synchronizingtheworld 

- 你可以把修复 QQ 问题的样式贴出来，我们加上；
- 你可以给出查看地址，我们帮你看看问题出在哪。

**Comment by synchronizingtheworld** [comment]
修复QQ浏览器问题的办法是.am-direction-nav a选择器上去掉padding，重写width和height，.am-direction-nav a:before 上width:100%等。

![Uploading image.png…]()

**Comment by Minwe** [comment]
@synchronizingtheworld 你说的在 QQ 浏览器上有问题是指上下切换镜头里面有别的文字对吧？

**Comment by synchronizingtheworld** [comment]
@Minwe 
<li>是的。</li>
<li>至于第二个问题。我回头再跟你讨论，在放到线上让你看看什么原因。</li>

**Comment by feichangtutu** [comment]
@Minwe 把重复引入的amaze ui脚本删掉后，首页的重复点点解决了！多谢！ 详见new.8mbang.com首页轮播；但是爸妈图库页的轮播还不ok.再调一下。

**Comment by feichangtutu** [comment]
@Minwe sorry，刚说错了。其他页面的轮播也ok了！http://new.8mbang.com/?q=pic%2Flist
我想问下原理是为什么

**Comment by Minwe** [comment]
@feichangtutu 具体原因还不太确定，按道理已经初始化过一次以后是不会再重复初始化的。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://gratefulexistence.com/consultant.php?eyr>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://www.kats.com.co/expedition.php?hz>

 

Again_moon@sohu.com
