### ISSUE TITLE
jquery调用模态框，遮罩层点击一直可以关闭模态框，原因求解

### ISSUE THREAD

**Issue by KingST1230** [allmobilize/amazeui#562]
如题，有经验者帮忙解答下问题吗？为什么官网的demo点击遮罩层不可以关闭模态框。
问题追加，jquery直接调用模态框，如何追加option，比如，closeViaDimmer如何赋值。

备注：调试自己的网页，发现调试窗口里的Event Listeners里的注册方法与官网给的demo的注册方法不一致，少了close closed open opend这几个方法。

**Comment by liyatang** [comment]
根据官网说明第一个modal是不可以关闭的。
![image](https://cloud.githubusercontent.com/assets/1010130/7646112/53af77ee-faf1-11e4-82c9-61b190ec26e6.png)

通过closeViaDimmer 可以控制这个逻辑。

怎么控制？
翻到下面的2.2.1参数说明，都是有例子的。
比如$().modal({closeViaDimmer:true}); 就行了。 btw，此值默认就是true。

and 看不懂你的备注...是否版本的问题？

**Comment by Minwe** [comment]
### 通过 HTML 方式设置参数

```html
<button class="am-btn am-btn-primary" data-am-modal="{target: '#doc-modal-1', closeViaDimmer: 0}">Modal</button>

<div class="am-modal am-modal-no-btn" tabindex="-1" id="doc-modal-1">
  <div class="am-modal-dialog">
    <div class="am-modal-hd">Modal 标题
      <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
    </div>
    <div class="am-modal-bd">
      Modal 内容。本 Modal 无法通过遮罩层关闭。
    </div>
  </div>
</div>
```

### JS 方式调用

```html
<button class="am-btn am-btn-primary js-modal-open">打开 Modal</button>

<div class="am-modal am-modal-no-btn" tabindex="-1" id="your-modal">
  <div class="am-modal-dialog">
    <div class="am-modal-hd">Modal 标题
      <a href="javascript: void(0)" class="am-close am-close-spin" data-am-modal-close>&times;</a>
    </div>
    <div class="am-modal-bd">
      Modal 内容。
    </div>
  </div>
</div>
<script>
  $(function() {
    var $modal = $('#your-modal', {
     closeViaDimmer: false
  });

    $('.js-modal-open').on('click', function(e) {
        $modal.modal('open');
    });

     $modal.on('open.modal.amui', function(){
  console.log('弹窗打开了');
});
  });
</script>
```

**Comment by KingST1230** [comment]
@Minwe 
通过 HTML 方式设置参数，还是可以通过点击遮罩层关闭模态框。
加的js如下 ：
![image](https://cloud.githubusercontent.com/assets/12092564/7646872/f4673e46-fafc-11e4-9cc1-0dc571566ca7.png)
不知道什么原因。或者你打包一个完整的demo（包括引入的js），我对比查下原因

**Comment by KingST1230** [comment]
问题解决了，原因是：少引入一个amazeui.min.css，并且按照官网的demo把各个引入文件的版本都更换了一下。
谢谢你们@liyatang @Minwe

**Comment by Minwe** [comment]
@KingST1230 使用 Amaze UI 时，Amaze UI 的 CSS、jQuery、Amaze UI 的 JS 是必须的。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://dorama-bank.com/similarity.php?cpx>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://margaretbarnhart.com/his.php?73a6>

 

Again_moon@sohu.com
