### ISSUE TITLE
引入 amazeui.js 文件后，type="date" 类型失效

### ISSUE THREAD

**Issue by cheft** [allmobilize/amazeui#563]
引入 amazeui.js 文件后，type="date" 类型表单字段，在android 中居然失效了，在ios中就没问题。
去掉 amazeui.js 后，android 中就可以了，能弹出系统时间选择器，求解决啊，急。

**Comment by huangzhipeng** [comment]
http://bin.amazeui.org/qifuji/1/

你用上面那个测试地址看下，我用 MX-2 QQ 和 微信都测试过了，点击后会弹出系统自带的日历

![s50515-163202](https://cloud.githubusercontent.com/assets/5733851/7649564/abe822d8-fb20-11e4-80ae-01c905925806.jpg)
