### ISSUE TITLE
Resource interpreted as Font but transferred with MIME type text/html

### ISSUE THREAD

**Issue by KingST1230** [allmobilize/amazeui#564]
Resource interpreted as Font but transferred with MIME type text/html: "....../assets/fonts/fontawesome-webfont.woff2?v=4.3.0".

在谷歌浏览器下，控制台报以上信息。这个怎么去掉？
百度上查找的方法：修改Apache目录config下的mime.types文件方法没有用。请问怎么修改或者怎么解决

**Comment by Minwe** [comment]
```
AddType application/font-woff .woff
AddType application/font-woff2 .woff2
```

**Comment by KingST1230** [comment]
还是不能解决...@Minwe

**Comment by Minwe** [comment]
那就不知道了，Apache 这块不熟，不影响显示的可以不管它。或者你可以引其他 CDN 上的字体。

**Comment by KingST1230** [comment]
@Minwe 好的，谢谢。
不影响显示。
