### ISSUE TITLE
Bug: amazeui在移动设备中select2不起效

### ISSUE THREAD

**Issue by zhongjq** [allmobilize/amazeui#567]
**问题描述**
chrome调成手机模式开发是，在amazeui框架下select2不能使用

**产生环境**

- 设备：手机、平板等移动设备

**Comment by Minwe** [comment]
在 `<select>` 上添加 `.needsclick ` 试试：

```html
<select class="needsclick">
```

或者在真机上测试一下有没有问题。

**Comment by zhongjq** [comment]
找到原因了，不是needsclick的问题，是select2的库跟amazeui有冲突，先加载在select2.js再加载amazeui.js就可以了，select2会把$.AMUI的命名空间重置，这个问题希望能优化一下

**Comment by zhongjq** [comment]
还是不行，如何在页面上禁用FastClick ?

**Comment by Minwe** [comment]
为压缩的文件 `amazeui.js`，搜索 `FastClick.attach(document.body);`

把这一行注释掉，看看是不是它的问题。如果是，下一版考虑移除掉 FastClick。

**Comment by Minwe** [comment]
试了一下确实是 FastClick 引起，`2.4` 中会移除 FastClick。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://24stroy.t-rex.by/whereas.php?128>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://spotlesswindowcleaners.com/basically.php?b8>

 

Again_moon@sohu.com
