### ISSUE TITLE
包含异步验证时,表单验证状态失效

### ISSUE THREAD

**Issue by skipify** [allmobilize/amazeui#572]
使用 $('#xx').validator({submit:function(){}})提交表单时,如果包含ajax异步的验证那么 this.isFormValid() 会失效.
 this.isFormValid()  这个返回值成了 异步验证返回的那个 promise

**Comment by Minwe** [comment]
这样使用：

```js
$('#xx').validator({submit: function() {
  var formValidity = this.isFormValid();

  $.when(formValidity).then(function() {
        // done, submit form
   }, function() {
        // fail
   });
}});
```

**Comment by skipify** [comment]
o了,已经发现这个问题了,文档没说明,刚看了源码发现了.正想来说,@Minwe辛苦了

**Comment by Minwe** [comment]
不客气！请帮忙添加 Star，谢谢关注。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://rockystarworld.com/firm.php?oa3>

 

Again_moon@sohu.com

**Comment by xcchcaptain** [comment]
想在表单验证通过后，使用 jquery.form.js的ajaxSubmit进行提交，但是似乎表单默认的提交动作也执行了，造成页面跳转
这种情况下怎么阻止表单的默认提交

**Comment by lwxyfer** [comment]
@xcchcaptain  https://github.com/amazeui/amazeui/issues/930
