### ISSUE TITLE
select插件会触发一次change事件

### ISSUE THREAD

**Issue by eworthcms** [allmobilize/amazeui#579]
```
<select name="pid" data-am-selected="{maxHeight: 200}">
  <option value="0">顶级栏目</option>
  <option value="1">二级栏目</option>
</select>
```
代码如上，我定义了一个select的change事件，结果change事件执行两次，经查，select在初始化的时候change了一次，请问，怎么解决呢？

**Comment by Minwe** [comment]
先 `off` 再绑定试试：

```js
$('#xxx').off('change').on('change', fn);
```

**Comment by liiklin** [comment]
貌似不行。还是会调用。一定要在2.4.1版本才有效？

**Comment by Minwe** [comment]
当然。

**Comment by zxw5775** [comment]
2.4.2同样遇到这个问题

**Comment by minwe** [comment]
@zxw5775 初始化的时候不会触发，每次选择值的时候会触发。

http://bin.amazeui.org/vocoqo/edit?html,console,output

**Comment by zxw5775** [comment]
2.4.2最新的版本中，.attr('selected', true);在chrome下会正常被选中，在IOS的safari下会把默认option跟指定的option一起触发变成多选了，并且改变selected后会触发一次change事件，求解决方案，如何正确被选中和不触发change事件，我需要的是单选

**Comment by zxw5775** [comment]
http://bin.amazeui.org/pumawusema/1/edit?html,console,output

**Comment by acitydu** [comment]
的确存在safari多选的问题

**Comment by zxw5775** [comment]
求尽快解决啊，全是在IOS里用到的

**Comment by minwe** [comment]
@zxw5775 你的使用场景是使用 JS 去选择 `<select>` 的值？

**Comment by minwe** [comment]
@zxw5775 Selceted 和 `<select>` 的数据同步是单向的，`<select>` 初始化以后的数据改变不会体现在 selected 上。

如果你的需求是需要通过 JS 选中 selected 的某一项，我们可以考虑添加一个方法来完成这个操作。

**Comment by zxw5775** [comment]
@minwe 是的，使用js改变select的选中值

**Comment by minwe** [comment]
@zxw5775 

2.5 以后可以直接使用 selected 的 `select` 方法选择，不用再直接操作 `<select>` 了：

```js
$('[data-am-selected]').eq(0).selected('select', 3);
```

其中 `3` 是选项的 index。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://bergwillgroup.ee/drop.php?5qntk>

 

Again_moon@sohu.com

**Comment by chaiman2601** [comment]
@minwe 官方使用文档中对JS的操作介绍太少了，根本不够用啊，每次都要找找找

**Comment by 13542202544** [comment]
当往这个select中动态添加选项或者改变选项的时候会触发绑定的change时间，怎么解决！

**Comment by mytxz** [comment]
消失了 好像js会给data-am-selected加上style="disabled: true"

**Comment by gloria1990** [comment]
select自动触发change,2.7以上的版本怎么解决呢？

**Comment by kikaendeavor** [comment]
https://github.com/amazeui/amazeui/issues/579#issuecomment-314637156

同问

**Comment by blueskysword** [comment]
在页面设置一个全局变量var i=1;，如果页面第一次加载，i=1；’在change事件中判断 ，若i=1，则不执行需要执行的change内部方法，防止第一次change事件的执行，然后i+1；这样第二次加载i就不等于1，在执行change方法。

**Comment by treefuture** [comment]
拿不到下拉框里面的值啊
