### ISSUE TITLE
妹子的页面左右滑动是怎么实现的啊？

### ISSUE THREAD

**Issue by KingST1230** [allmobilize/amazeui#581]
http://amazeui.org/widgets/m#accordion
如上面的页面的导航栏部的回退键产生的滑动效果。
先谢谢了

**Comment by Minwe** [comment]
https://github.com/allmobilize/amazeui/blob/master/tools/app/public/style.less
https://github.com/allmobilize/amazeui/blob/master/tools/app/views/index.hbs

参考里面的实现方式，就是监听 hash 变化来改变两个容器的样式。

克隆项目，执行 `npm install` 以后再执行 `npm preview`，打开 `localhost:3008` 可以看到类似的界面。

**Comment by KingST1230** [comment]
@Minwe 
谢谢你的回答。
