### ISSUE TITLE
建议将链接按钮访问后的样式统一改为白色

### ISSUE THREAD

**Issue by jimlaren** [allmobilize/amazeui#584]
如果用<a href="#" class="am-btn am-btn-danger">链接</a>制作按钮，访问后，字会变为蓝色，很难看，建议将访问后am-btn-primary外的按钮颜色样式统一设置为白色：
a.am-btn-primary:visited,a.am-btn-danger:visited,a.am-btn-warning:visited,a.am-btn-secondary:visited,a.am-btn-success:visited{
  color:#fff;
}

**Comment by Minwe** [comment]
什么浏览器会出现这样的情形？

**Comment by LinSundy** [comment]
阿萨德
