### ISSUE TITLE
感觉amazeui 迭代得有点慢

### ISSUE THREAD

**Issue by linziguan** [allmobilize/amazeui#586]
感觉amazeui 迭代得有点慢。还有建议完善一下js那块，样式是出来了，可是要操作其中的元素还差一些距离。

**Comment by iparanoid** [comment]
然而并不慢 我觉得任何产品都需要细腻

**Comment by Minwe** [comment]
@linziguan 那些功能觉得不够用的可以具体提出来。

迭代的速度太快也未必是好事，前端是一个比较琐碎的事情，用户升级起来还是比较麻烦的。
