### ISSUE TITLE
怎么阻止模态框的默认关闭行为？

### ISSUE THREAD

**Issue by 178620086** [allmobilize/amazeui#589]
我测试了写当在onConfirm事件中返回false还是无法阻止关闭，请问有何方法可以实现谢谢！

**Comment by Minwe** [comment]
目前没有提供不关闭的 Modal 的选项，只能是把按钮的事件先移除掉：
http://bin.amazeui.org/yejeji/1/edit?html,output

```js
$('#my-confirm').find('.am-modal-btn').off('click.close.modal.amui');
```

**Comment by 178620086** [comment]
这样是可以，但是取消也没有了。。唉 难两全么？？

或者有没有办法再把这个事件绑定上去
？

**Comment by Minwe** [comment]
那你就只取消确定按钮的：

```js
$('#my-confirm').find('[data-am-modal-confirm]').off('click.close.modal.amui');
```

**Comment by 178620086** [comment]
我现在使用的是v2.2如何更新到最新的2.41？看了一圈貌似都是零碎的 原谅我在这方面还是一个新手 。

**Comment by Minwe** [comment]
2.4.1 还没有发布呢，一般直接替换成新版的 CSS 和 JS 就行。

**Comment by 178620086** [comment]
恩，好，
估计这个替换也不好弄（等等再去测试）。
我刚刚试了一下：<pre>
$('#addmodal').find('[data-am-modal-confirm]').off('click.close.modal.amui');
</pre>
这样是能够去掉那个关闭的事件，但是我想再次个这个对象加上这个事件（就是直接on(....)）但是无效。不知道具体里面是怎么处理？

**Comment by 178620086** [comment]
<pre>
$("p").on("click", function(){
alert( $(this).text() );
});
</pre>
刚刚去查看了一下jquery的api原来是这样添加事件。
所有请问这个具体函数中都做了哪些事。如果很多的话可以给一个链接我自己去查看一下么？

**Comment by 178620086** [comment]
<pre>
//先去掉确定按钮的事件
$('#addmodal').find('[data-am-modal-confirm]').off('click.close.modal.amui');
//当事情搞定后，调用快速关闭的事件。。
$(".am-dimmer").trigger("click")
</pre>

我都没想到我能想到这么奇葩的解决方案 。

**Comment by Minwe** [comment]
关闭那步你可以直接调用 Modal 的方法：

```js
$('#addmodal').modal('close');
```

**Comment by 178620086** [comment]
！！！！没想到还可以这样 
行 我改。
感谢耐心解答。

**Comment by mqliutie** [comment]
我要点击确认才知道才知道要不要关闭Modal，怎么破?

**Comment by wufeng87** [comment]
$('.redownloadBtn').off('click.close.modal.amui').click(function(){
		
	})

这样写点击，并不能阻止默认的点击按钮关闭窗口的行为了？

**Comment by icepy** [comment]
this.el.modal(defaultOptions);
this.el.find('[data-am-modal-cancel]').off('click.close.modal.amui');

没起作用啊，有什么技巧么？

**Comment by minwe** [comment]
@wufeng87 @icepy 

确保选到了 Modal 里的两个按钮。

http://bin.amazeui.org/yejeji/edit?html,console,output

**Comment by wufeng87** [comment]
@minwe 谢谢，我的已经找到问题了，是我自己的调用顺序问题，off需要在amazeui的脚本之后调用

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://baselinecomputer.com/lobby.php?eri6m>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://mhol.ru/formal.php?hnpx1>

 

Again_moon@sohu.com

**Comment by STKGSF** [comment]
2.7.2版本 只能使用 $('#my-confirm').off('click.close.modal.amui'); 了。
$('#my-confirm').find('.am-modal-btn').off('click.close.modal.amui');的方法已经失效了
这样就不能单独针对一个按钮off对话框关闭事件 :(
