### ISSUE TITLE
Imagining Amaze UI Next: Amaze UI Mobile

### ISSUE THREAD

**Issue by minwe** [allmobilize/amazeui#590]
> Amaze UI React 版本开发（移植）主体已经完成，剩下的只是细节完善和 Bug 修复，是时候对下一阶段的方向做一下思考。

## 现状

Amaze UI 的前身是公司内部为方便网站适配编写的一些列移动端组件（官网上 「**Web 组件**」栏目），后来扩充了一些 CSS 组件和 JS 插件并开源，然后从 Zepto 转向 jQuery，发展成为现在的 Amaze UI。

一款带着内部定制烙印的产品，转为面向公众后，由于需求的差异性，一些问题就显现出来了。

### 功能不足与功能过剩

Amaze UI 以满足**轻交互、展示性**响应式页面需求为原则设计，对这种类型的页面开发自然顺风顺水，但对于其他场景则会比较纠结：

- **交互较复杂的（如管理后台）应用场景不够用**。Amaze UI 部分 JS 插件功能相对简单，对于更复杂的需求，用户需要编写更多的代码来实现。对于这个问题，我们选择融入 jQuery 生态圈，以样式 AMUI 化、不动 JS 代码、独立成项的形式，让一些很有代表性的 jQuery 插件能和 Amaze UI 一起使用。在不破坏设计原则、不增加需求相对简单用户负担的前提下，满足更复杂的使用场景。**我们会延续这个思路解决「不够用」的问题，继续探索 CSS 依赖管理问题，提高用户使用便利性**。
- **功能过剩**。Amaze UI 说不上庞大，但也五脏俱全，对于一些只面向移动端的需求，显得有些臃肿，不够纯粹；基于 jQuery 也让对代码体积敏感的用户嘘嘘不已。功能不够可以加，但是要做减法，尤其是削减 jQuery 这个基础依赖并不太现实，因此，才会萌生独立出一个完全面向移动端的项目的念头。

### 内部使用遗留问题

- **所谓主题**，只是针对单一组件的实现，并非整体的实现，简单的样式变化增加了代码量，但对外部用户可能意义不大，**提供基础的默认样式 + 良好的样式扩展接口**对于可能更好的选择；
- **不适用于 SPA**。对于传统的服务器渲染方式，Amaze UI 工作得很好，但对于日趋流行的 SPA，使用时会有一些问题，比如需要手动初始化插件等。React 版本能有效解决这一问题，**但仍然逃不过移动端使用略显臃肿的问题**。在交互方式上，SPA 局部刷新（某个容器）和传统 Web（基于 window）也会有一些区别，实现方式和性能优化方式也会有差别。

**基于以上问题，才有了独立出一个完全面向移动端的 Amaze UI Mobile 的想法。**

### 应用场景
- 开发**原生 App**，需要快速出代码级别的交互原型。

  > A prototype is worth a thousand meetings.
- **移动营销快速搭建移动站点：**
 
  - 响应式网站 PC、Mobile 关联，牵一发动全身，无法根据营销需求进行大规模、快速调整；
  - 有的 PC 站过于庞大，做响应式不现实；
  - 没有 PC 站，就是单纯做移动站。
- 基于BaaS 或者第三方 API，做一个有趣的应用，不需要后端；
- **Hybrid App**，不可能把一个臃肿、低效的响应式的网站打包进 App；
- ……

### 设计原则

- 只是 UI(View)；
- 向下兼容不是首要目标；
- 一切从简，但提供良好扩展接口；
- 考虑服务器端渲染的情形（为爬虫提供内容）。

### 技术架构

- **基于 React 开发，不依赖 Zepto 等 DOM 操作库**，可能的使用方式：
	- React + react-router + Flux
	- React + Backbone
	- React + Angular
	- React + Meteor
- **使用 Sass？**

  Less 松散的语法、容易上手，但是编程能力很鸡肋。
- 使用 Flexbox 布局；
- **沿袭现在的 UI 风格（参考微软 UWP 设计指南）**：我们不再需要一个 Framework7，也不再需要 Material Design 的 UI 移动框架；不要带有过多的系统痕迹。

### 组件规划

- 适用于移动端的超轻量网格系统
- Button
- Header 页头
- Titlebar 标题
- List：展示功能、过滤同能
- Tapbar 底部工具栏
- Form
- 图片查看
- Icon: 寻找更小的 Font Icon，FontAwesome 对于移动端有些大
- Modal 
- Slider
- Tabs

***待调研、补充、完善。***

**Comment by udbmnm** [comment]
Amaze UI Mobile单独出来必须支持，早该这么做了，兼容PC没意义，不是为了做全响应，干上React 更是爽爆了

**Comment by shenger153** [comment]
更具业务需要确实需要一款只考虑移动端的轻应用产品，并不是所有的项目都需要pc端

**Comment by acterce** [comment]
支持，大势所趋！！bootstrap都单独开发了mobile apps的Ratchet。

**Comment by yay2008** [comment]
技术架构赶快确定啊...以后就跟你们了..

**Comment by redspear119** [comment]
最好各个组件独立可以自己打包选择.

**Comment by agileago** [comment]
很早就有这个需求了，很多项目不需要pc+mobile兼容，仅仅只是pc或者mobile而已，支持Amazeui mobile👍⚡️

**Comment by Bantes** [comment]
##必须支持##
早就应该这么干了！

**Comment by fudaoji** [comment]
希望amazeui利用这个大招，“勾引到”更多的使用者

**Comment by zhoumo310** [comment]
支持推出只针对移动端的。
建议是兼顾pc端的响应式版本+只针对手机端的版本。做2个独立版本。

**Comment by bobstar** [comment]
我感觉AmazeUI的定位，稍微有点混乱。到底是要做啥？Jquery主流于是改Jquery，React红火了改React，移动端开发日趋火热，单独出移动版本？？同样的思路，这地球上有多少框架了？
大家的目标完全一致，办法殊途同归，为什么不统一为一个“PC+移动”的版本呢？
我在给公司写一个内部的OA系统，用的AmazeUI，我希望是一套代码，跨设备，跨平台，免维护。
而不是，PC用AmazeUI,移动用移动版本，时间精力都浪费在调整2套界面了，累不累？

**Comment by bobstar** [comment]
很多人说的，很多网站只需要移动版本，PC上不用浏览的，我想说你在开玩笑，你是用原生APP的方式在开发web，你找个只用手机浏览PC无人访问的网站给我看看？APP的缺陷在于不同屏幕尺寸匹配的问题，web的优势，特别是HTML5定稿之后，最大优势就是跨设备，跨平台，自适应和开发、升级的便利。
我们需要放弃这种优势，然后针对不同的设备或尺寸开发不同的版本？那样的话，我开发一个网站，PC端实现了，移动端呢？是继续PC端一套代码的方案呢还是选择有一定优化的移动端的UI？累不累？
我知道一个框架，兼容所有设备和屏幕尺寸有一定难度，但这不正是AmazeUI存在的意义，开发者们的渴望的挑战和建立丰功伟业的机会吗？

**Comment by jflow1** [comment]
专注移动端，是最好的！

**Comment by Leaybc** [comment]
既然口号是移动优先，其实可以先做移动端，但是完全不顾PC的话，也挺尴尬的

**Comment by aidenzou** [comment]
React + react-router + Flux
React + Backbone

2选1 吧

**Comment by kai19841228** [comment]
专注移动挺好的，pc时代已经过去了，兼容pc只会让妹子ui的js，css文件大。更难做到手机的优化速度。不利于手机访问的优化使用，会使体验降低。

**Comment by dcy** [comment]
建议专做Mobile版本，毕竟pc web很多会选bootstrap等其他

**Comment by banshourenx** [comment]
必须多版本啊

**Comment by liyatang** [comment]
支持专mobile

**Comment by gywgithub** [comment]
建议PC+Mobile整合版本

**Comment by gybin02** [comment]
建议是兼顾pc端的响应式版本+只针对手机端的版本。做2个独立版本。
只针对手机端的版本  == 这个应该是更紧急的。。 比较 响应式的已经很有多了。。
== 这个应该是最佳的方案。。

**Comment by pigwing** [comment]
关于妹子UI使用了http://fontawesome.io/作为icon.但是我使用妹子的场景是GBK编码的.导致http://fontawesome.io/无法使用.请问妹子有没有办法解决了.毕竟我的环境已经是GBK的了.无法改变.

**Comment by byzhangshuo** [comment]
@pigwing 链接编辑下吧，挂了

**Comment by pigwing** [comment]
@byzhangshuo 哈哈,那个连接问题不大不是连接过去的..但是目前我的妹子无法显示icon很蛋疼

**Comment by weikety** [comment]
单独出来太好了~~~I like

**Comment by neilchencn** [comment]
独立出 mobile 版本还是很有必要的.  毕竟想要用一个框架来解决pc, 平板, 手机这些太美好, 算是理想. 
昨天碰巧看到妹子 UI 出了 react 版本的, 感觉还不错, 组件化之后让用户有选择性的使用比较好.
不过 react native 就算是手机端也独立出了ios 版本和 android 版本. 想要用户体验更好, 做的更精致,目前来看靠一套方案通吃还是很难做.
现在各种框架层出不穷, 还是做点什么特色的框架比较好.

**Comment by Minwe** [comment]
@pigwing 你说的问题不存在吧，我在 Mac 各个浏览器里试了一下都没问题：

```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="gbk">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>Amaze UI 在线调试</title>
  <link rel="stylesheet" href="http://cdn.amazeui.org/amazeui/2.4.0/css/amazeui.min.css"/>
</head>
<body>
麻花藤 <span class="am-icon-qq"></span>

<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://cdn.amazeui.org/amazeui/2.4.0/js/amazeui.min.js"></script>
</body>
</html>
```

**Comment by Yeocat** [comment]
支持推出Amaze UI Mobile,喜欢这个搭配：React + Angular，:D
管理后台的确需要加强一下下，作者加油~

**Comment by dcy** [comment]
Angular?更喜欢正美的Avalon，https://github.com/RubyLouvre/avalon

**Comment by chenyeyuze** [comment]
我怎么觉得越来越混乱了啊

**Comment by windcbf** [comment]
@bobstar 你们的OA系统具体实现什么业务？ 能放个界面截图上来么？  我们想看看什么样的OA系统适用响应式， 什么样的系统适合PC和Mobile 分开

**Comment by Minwe** [comment]
@bobstar 出专门的移动版并不影响你使用现在的响应式版本，下面三个版本是并行维护、更新的，只是满足不同的需求而已：

- Amaze UI （jQuery）
- Amaze UI React 
- Amaze UI Mobile

其中 jQuery 版和 React 都是响应式的，你可以继续使用 jQuery 版本进行开发，并不存在以后停止更新、维护问题。

Mobile 版本则是面向没有桌面版需求的用户。

**Comment by kiyeer** [comment]
这是一个非常好的消息！绝对支持，PC端和移动目前来讲还是具有很大的差异，没必要整在一起。

**Comment by xfworld** [comment]
等待更新版本....
每天都有新的惊喜

**Comment by cyhunter** [comment]
期待  希望Mobile版本支持更多的手势

**Comment by bobstar** [comment]
OA才开发了20%不到，不好意思给人看。我也知道你们的几个版本都在同时开发和维护，我的意思是，这个世界的框架已经太多太多了，作为菜鸟级开发者，我希望有一个框架就够了，可以重点针对移动设备进行优化，然后完全兼容PC，而不是PC2套，一个Jquery，一个React，然后移动版本又一套。感觉大家都走了极端，脱离了初衷。现在所有人都在强调移动，所以都很极端的忽视了PC，专注移动了。不要忘了，移动设备毕竟尺寸有限，很多很多东西还是PC上体验更好。大家还是按照开发APP的逻辑在考虑“未来的移动网站”，我觉得不合理，真的要有特色，就应该一套框架，优先移动，兼容PC，然后不断进行极致优化，这才是未来。版本太多，未必是好事情，现在什么都讲究一个快，在这个快的时代，我们输不起慢的代价，框架是为了满足需求存在的，一套框架通吃真的不行吗？这不就是HTML5存在的意义吗 ？没人喜欢折腾好几套东西。个人看法，菜鸟一枚，欢迎拍砖。

**Comment by bobstar** [comment]
顺便说一句，OA开发了一点点，但是每一个功能，界面，我都是PC和手机同时测试的，达到满意才收手，或者至少移动端非常满意，PC端基本满意，也许是网站定位和针对人群的不同，我没发现性能是问题，我感觉Jquery版本的已经足够。
目前，OA是完全跨设备，跨平台，跨浏览器的，一套代码，（当然了，不只是用了妹子UI）我觉得很好。

**Comment by jiangyuhe123** [comment]
我来说几句吧，我个人现在也在用amazeui，我自己搞了个前段view和viewmodel的架构，view展示用amazeui，viewmodel用knockoutjs，使用template来加载html片段，做single page的app。用amazeui最大的一个困惑是还不够贴近真实的使用，比如app的进入现在都流行一些展示页面，这个都要自己凑。我建议可以做一些纯前端的template，做几套目前市场上流行的套件，毕竟developer最缺少的是设计，或者说做有艺术感的设计很费精力。我想有一套amazeui的可以拿来演示的app原型，然后我往里面填页面逻辑，组织转跳，再稍微修改一下页面就可以跑起来了。做成像叮当，简网，WeX5那样的app原型，但是不绑定后台，不需要依赖别人的后台环境，纯粹就是些template html和js文件的框架。

**Comment by zfengyu** [comment]
Amaze UI Mobile  单独做出来最好了，就怕你们精力不够，做不精致了，还是又大量累赘的代码...产品线太多，总有纰漏，定制化下载，需要什么用什么就好了，何必搞独立的

**Comment by MetSystem** [comment]
支持Amaze UI Mobile

**Comment by donfo** [comment]
强力支持Amaze UI Mobile   现在这块需求实在太急切  
个人觉得最狂拽酷炫的方式
目前还没这种完全独立于移动端的React UI，PC要不要兼容，答案是肯定要兼容，但是我们要怎样做到满足各种需求（如：全端、PC端、移动端），给开发者带来真真正正的便利呢。那就是：
~~~~~~~~~~模块化~~~~~~~~~~可选择~~~~~~~~~~可定制~~~~~~~~~~~可组合~~~~~~~~~~~

**Comment by liyatang** [comment]
@donfo 现在妹子就是这样的吧。

**Comment by agileago** [comment]
@donfo 怎么强力支持？来点实际的😃

**Comment by MetSystem** [comment]
@liyatang  

看看Minwe说的现状。

**Comment by zoominet** [comment]
支持

**Comment by minwe** [comment]
@all:

谢谢各位参与讨论。

Amaze UI 移动版已经初步完成，现邀请部分用户内部预览。

### 内部预览遵循以下规则：

- 感兴趣的用户请在后面跟帖留下 https://bitbucket.org/ 的用户名，优先选取前 10 - 20 名用户；
- 目前源码未对外开放，**请勿传播预先查看到的源代码（我们不会追踪，但请遵守基本的契约精神）**；
- 开发者预览版相关讨论，请到 https://github.com/amazeui/amazeui-touch/issues/2。

**Comment by agileago** [comment]
@minwe  agileago 

略期待啊

**Comment by jimlaren** [comment]
@minwe jimlaren

一直在等待。

**Comment by minwe** [comment]
@agileago @jimlaren https://bitbucket.org/amazeui/amazeui-touch-dp

谢谢关注。

**Comment by dasonn** [comment]
支持啊啊

**Comment by doublenian** [comment]
支持

**Comment by minwe** [comment]
Amaze UI Touch 开始公测：https://github.com/amazeui/amazeui-touch

此 Issue 关闭。
