### ISSUE TITLE
offcavas自动关闭的问题

### ISSUE THREAD

**Issue by Stephenzxb** [allmobilize/amazeui#597]
移动设备上offcavas组件中存在input情况下，focus时由于输入法弹出会导致offcavas关闭。
桌面上，打开浏览器调试窗口，或改变浏览器窗口大小也会导致offcavas关闭。
貌似是窗口宽高改变时，都会出现这样的情况。

**Comment by Minwe** [comment]
基于窗口 resize 的时候需要重新计算窗口高度、滚动条的位置等考虑，添加了一个 resize 自动关闭的处理。

可能弹出键盘的时候也会触发 resize 事件，所以被关闭了。

你试一下把 `resize` 监听取消掉：

```js
$(window).off('resize.offcanvas.amui');
```

**Comment by Stephenzxb** [comment]
谢谢了，就是这样解决了

**Comment by noodleswww** [comment]
移动设备上offcavas组件中存在js调用modal时，也会存在自动关闭的现象，
> $(window).off('resize.offcanvas.amui');
不会阻止关闭

**Comment by minwe** [comment]
@noodleswww 什么系统、浏览器？

http://bin.amazeui.org/xuwure iPhone 测试了一下没发现这个问题。

你可以试试

```js
$(window).off('resize.offcanvas.amui orientationchange.offcanvas.amui');
```

**Comment by noodleswww** [comment]
@minwe 
我在设置了侧边栏100%全屏，然后以之为容器，加入表单并验证，动态通过

> $('xxxx').modal('open') 调出模态窗口显示用户输入提示信息

结果：modal弹出后，侧边栏自动关闭。
> $(window).off('resize.offcanvas.amui orientationchange.offcanvas.amui');
> $(window).off('resize.offcanvas.amui');
加入这两个均无阻止

**Comment by noodleswww** [comment]
![wechat_1443509746](https://cloud.githubusercontent.com/assets/8499950/10157182/39c53fd2-66ba-11e5-8be7-b846a95a2c4c.jpeg)
@minwe 
> android下 侧边栏100%后，左侧会有一条竖条，ios下无，
>modal导致退出的也是在这个页面

注：
android下 input 会导致侧边栏退出，ios不会出现
modal导致的退出现象，android和ios均出现

**Comment by noodleswww** [comment]
@minwe 
> android下 侧边栏100%后，左侧会有一条竖条，ios下无，
>modal导致退出的也是在这个页面

注：
android下 input 会导致侧边栏退出，ios不会出现
modal导致的退出现象，android和ios均出现

**Comment by minwe** [comment]
@noodleswww 

用传统方式布局的页面在移动段特别是安卓上可能问题比较多。

可以尝试的做法是 html、body高度设为 100%，把滚动条移动到更子级元素上

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://www.amatravel.ro/pleasure.php?hx>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://organicsib.ru/instance.php?9b>

 

Again_moon@sohu.com

**Comment by jansanw** [comment]
`
        //!!!修正webview表单focus时缩放触发关闭
        $("#offcanvas-user").on("open.offcanvas.amui", function (e) {
            $(window).unbind("resize.offcanvas.amui orientationchange.offcanvas.amui");
        });
`

**Comment by sxq2370756633** [comment]
开启侧边栏后，怎么设置关闭鼠标点击区域导致侧边栏关闭，想要纯用btn控制开启关闭？求解决在线等

**Comment by TJ315** [comment]
怎么解决？？？？？？？？？？？？

**Comment by long198712** [comment]
$case.on('open.offcanvas.amui', function() {
      $(window).off('resize.offcanvas.amui orientationchange.offcanvas.amui');
    }).on('close.offcanvas.amui', function() {

    });
放在触发触发事件里面，才会有效

**Comment by woshixiaoma** [comment]
谁有解决办法？我试了上面的还是不行

**Comment by liuwei18374744373** [comment]
@long198712 还是不行呢？放到input输入框调用的手机输入法的触发事件里面？怎么放呢
