### ISSUE TITLE
admin-index-fixed.html 侧滑菜单被页头覆盖

### ISSUE THREAD

**Issue by xfworld** [allmobilize/amazeui#599]
刚刚更新的这个 版本，在移动端访问的时候，会因为固定的admin-header，导致admin-sidebar菜单第一行被遮住，这个bug咋修复，求指导

**Comment by xfworld** [comment]
<footer>
  <hr>
  <p class="am-padding-left">© 2014 AllMobilize, Inc. Licensed under MIT license.</p>
</footer>

这段代码也失效了....

**Comment by xfworld** [comment]
@Minwe  这个有没办法解决啊...

**Comment by Minwe** [comment]
被遮挡的问题调一下 `z-index` 就行，我等会修复。

这种固定页头和边栏的布局，页脚一般就显示在内容区域底部了吧？

**Comment by xfworld** [comment]
@Minwe  z-index我调了一下，没啥效果....
页脚基本上就放弃了...

看看怎么弄。我把中间的内容区域改成用iframe加载了，如果tabs支持创建、刷新和关闭，我就不用这么改了...折腾啊

**Comment by Minwe** [comment]
你用下面的链接替换一下本地的 `admin.css`

https://raw.githubusercontent.com/allmobilize/amazeui/c860b2e181c067aa0097f271e1394e8ad3735cb6/docs/examples/assets/css/admin.css

iframe 是比较省事，不过毕竟是过时的技术，而且做响应式也不好做，现在流行的方式应该是 SPA。

**Comment by xfworld** [comment]
.fixed-layout .admin-content{
	height: 100%;
	overflow-x: hidden;
	overflow-y: hidden;
}
.fixed-layout .admin-sidebar {
  height: 100%;
  overflow-x: hidden;
  overflow-y: scroll;
}

这段css建议改成这样子，不然右边的滑动条会出现两根。
我去看看SPA的构建方式，人懒了 ^_^

**Comment by Minwe** [comment]
什么浏览器右边会出现两个滚动条？

**Comment by xfworld** [comment]
版本 43.0.2357.81 m
 
Google Chrome 已是最新版本。

这个版本...反正挺奇怪的

**Comment by Minwe** [comment]
你用的是 windows  版本？我在 Mac 上测了一下没问题啊。

**Comment by xfworld** [comment]
是的，windows版的
我自己优化后，在别的版本上也挺ok的
