### ISSUE TITLE
tab支持不太友好

### ISSUE THREAD

**Issue by xfworld** [allmobilize/amazeui#602]
@Minwe  tab太宽了，比原生的easytabs宽好多，而且定义的tab过多，没有向前或者向后的按钮。在pc端和移动端的展示都不太好（换行展示）。

能否提供向前和向后滑动的按钮，支持多tab方式的展示。最好能提供add,remove,find,ativce等动态绑定方法。

初始化参数option，提供的参数也太少了....  增加几个吧...

**Comment by xfworld** [comment]
![tabpig](https://cloud.githubusercontent.com/assets/5020771/8001707/c80b9a82-0b9a-11e5-970c-2c6a84dd4ab7.png)
这是打开的效果...

**Comment by xfworld** [comment]
![tabpig2](https://cloud.githubusercontent.com/assets/5020771/8001721/e0b3f1ce-0b9a-11e5-8a77-8baa3ce2dcff.png)
这是缩小浏览器后的效果....

**Comment by Minwe** [comment]
你把 `am-nav-justify` 这个 class 去掉可能会好一些。小屏幕上我们再看看吧，在小屏幕上使用太多 Tab 本身不是很友好的交互方式。

**Comment by xfworld** [comment]
去掉就变成换行了 ^_^  

看来只能嵌套在嵌套了。而且不能超过3个...

**Comment by sddwt** [comment]
另外，如果在tab中存在flexslider，会导致滑动slider导致tab页也滑动，尽管可以手动修改监听对象，但是希望官方能出一个class来排除监听

**Comment by heyguojing** [comment]
选项卡tab不能关闭，这个有点鸡肋
