### ISSUE TITLE
Modal取消关闭行为

### ISSUE THREAD

**Issue by mqliutie** [allmobilize/amazeui#603]
[#589](https://github.com/allmobilize/amazeui/issues/589)问题中，说是移除按钮事件，可是这个按钮事件我是需要的，我要用`onConfirm`方法来判断填的内容，如果输入内容有空的Modal是不能关闭的，请问有什么办法解决吗?

**Comment by xfworld** [comment]
你的问题很简单啊，移除的只是按钮，但是关闭的事件还是可以用的。

意思是你在<code>onConfirm</code>执行逻辑判断后，在执行关闭事件就收工了。

**Comment by Minwe** [comment]
@xfworld 说得对

http://bin.amazeui.org/yaqisupeyu/1/edit?html,output

**Comment by mqliutie** [comment]
@Minwe 你给的方法OK的，
可是文档中我没看到这种用法呢.
不懂这句话的作用
`$promt.find('[data-am-modal-confirm]').off('click.close.modal.amui');`

**Comment by xfworld** [comment]
@mqliutie  你的这个问题可以关闭了。 @Minwe  都给出答案了，照抄即可；
<code>$promt.find('[data-am-modal-confirm]').off('click.close.modal.amui');</code>
是取消关闭事件的意思；
off() 方法通常用于移除通过 on() 方法添加的事件处理程序。
自 jQuery 版本 1.7 起，off() 方法是 unbind()、die() 和 undelegate() 方法的新的替代品。该方法给 API 带来很多便利，我们推荐使用该方法，它简化了 jQuery 代码库。
注意：如需移除指定的事件处理程序，当事件处理程序被添加时，选择器字符串必须匹配 on() 方法传递的参数。
提示：如需添加只运行一次的事件然后移除，请使用 one() 方法。
你看我写的，应该能懂了
<code>
$(function() {
        $('#doc-prompt-toggle').on('click', function() {
          var $promt = $('#my-prompt').modal({
            relatedTarget: this,
            onConfirm: function(e) {
              if (!e.data) {
                 alert('输入点东西吧！')
              } else {
                alert('输入了');
                this.close();
              }
            },
            onCancel: function(e) {
              alert('不想说!');
            }
          });
$promt.find('[data-am-modal-cancel]').off('click.close.modal.amui');
$promt.find('[data-am-modal-confirm]').off('click.close.modal.amui');
        });
      });
</code>

**Comment by Minwe** [comment]
`[data-am-modal-confirm]` 这个按钮上默认绑定了一个 click 事件（ `click.close.modal.amui`），点击的时候回关闭 Modal。

通过 `$promt.find('[data-am-modal-confirm]').off('click.close.modal.amui');` 取消这个 click 事件。

**Comment by 178620086** [comment]
我是这样弄的：
<pre lan='js'>

$('#addmodal').find('[data-am-modal-confirm]').off('click.close.modal.amui');//去掉modal的关闭事件。
  $("#addmodal").modal({
    onConfirm : function(options) {
$.ajax({
		url : "ShopCartServlet",
		data : {
		        opt : 1,
			isbn : isbn,
			num : num
			},
		dataType : "json",
		type : "post",
		success : function(data) {
		if (data && data.success) {
				$("#AddSuccess").show(300);
				$("#keyWord").text(data.key);
				setTimeout(function(){
					$('#addmodal').modal('close');//就是这里了
					},1300);
				}else{
				}
				},
					error : function(XMLHttpRequest,
				}
		});
}

});

</pre>

如有不对请指正

**Comment by zorc** [comment]
2.5.2这招行不通

**Comment by minwe** [comment]
升级以后此方法失效，实现方式参考 https://github.com/amazeui/amazeui/issues/836#issuecomment-190074130
