### ISSUE TITLE
强烈建议实现集成腾讯的MT

### ISSUE THREAD

**Issue by wzlee** [allmobilize/amazeui#604]
建议专注于移动端的web UI，强烈建议集成MT:http://mt.tencent.com

**Comment by xfworld** [comment]
都是基于AMD的，@wzlee你可以自己试试啊...

**Comment by wzlee** [comment]
试了不行好像

**Comment by Minwe** [comment]
MT 对于流量比较小的网站没什么意义，只是增加复杂程度而已。

**Comment by Minwe** [comment]
建议用户寻找技术方案的时候，选择一些成熟的、大众化的方案。过度定制化的技术方案没有社区支持，使用和维护都成问题。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://thesafeandlockshop.co.uk/extremely.php?w>

 

Again_moon@sohu.com
