### ISSUE TITLE
TBC: 表单验证插件与 Selected 兼容性问题

### ISSUE THREAD

**Issue by Minwe** [allmobilize/amazeui#605]
在form标签中加入 data-am-validator，然后在这个form中加入
`<select id="city" data-am-selected="{btnWidth: '200px', btnSize: 'lg', btnStyle: ''}"></select>`就会出现页面加载不出来的情况，去掉其中的一个就正常了

**产生环境**

- 设备：pc端
- 操作系统及版本：win7
- 浏览器及版本：chorme 41.0.2272.118 m
- 演示地址：

**Comment by xfworld** [comment]
这是干啥...

**Comment by Minwe** [comment]
Fixed by 2840c1fdca328d0e976a7d2b4957d5068f103c4c

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://santasbargainbasement.com/film.php?b>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://hoavaiphuocphat.com/expert.php?7>

 

Again_moon@sohu.com
