### ISSUE TITLE
Panel上面可以加按钮么？

### ISSUE THREAD

**Issue by xfworld** [allmobilize/amazeui#606]
如题....
panel上现在只有一个折叠的按钮，是否可以和modal类似，可以在靠右上增加小按钮，图例：
![image](https://cloud.githubusercontent.com/assets/5020771/8002708/a7251e20-0ba3-11e5-9e74-98174323758a.png)

**Comment by Minwe** [comment]
这个你根据需要自己加就行了。

**Comment by xfworld** [comment]
好的，我试试

**Comment by Minwe** [comment]
http://bin.amazeui.org/domogu/1/edit

**Comment by xfworld** [comment]
@Minwe  怎么能够让panel上自己添加的按钮， 不触发折叠事件啊...头大，难道又要用off?

**Comment by xfworld** [comment]
或者折叠了，我手动让他在打开？

**Comment by xfworld** [comment]
我发现我写个OnClick事件，panel就没了...

**Comment by xfworld** [comment]
@Minwe  求答案....

**Comment by Minwe** [comment]
你要实现什么功能？

**Comment by xfworld** [comment]
@Minwe 怎么能够让panel上自己添加的按钮，触发的onclick事件， 不触发折叠事件啊...

**Comment by Minwe** [comment]
我这没触发啊

```
 $('.am-btn').on('click', function(e) {
        e.stopPropagation();
        console.log('aa');
});
```

**Comment by xfworld** [comment]
我试试...

**Comment by xfworld** [comment]
加了这个e.stopPropagation(); 事件就好了.....
