### ISSUE TITLE
Topbar 导航条 优化

### ISSUE THREAD

**Issue by ww380459000** [allmobilize/amazeui#611]
导航条在手机端am-topbar-right没用，还有能不能有个居中的样式呢？想自己布局个导航，左边logo，中间有个下拉菜单，右边也有个下拉菜单，样式不支持，能否写到框架里呢？谢谢

**Comment by ww380459000** [comment]
么人打理我

**Comment by Minwe** [comment]
你说的和 http://amazeui.org/css/topbar 这上面的例子不是差不多吗？

**Comment by ww380459000** [comment]
差的多么，想把那个下拉放中间，好像没有居中的样式只有am-topbar-right和am-topbar-left，手机上的话am-topbar-right是不管用的

**Comment by ww380459000** [comment]
不想用手机端右边那个绿色的菜单

**Comment by Minwe** [comment]
这个得自己写点 CSS 去实现了，不可能满足所有人的需求。

**Comment by ww380459000** [comment]
好吧，那手机端am-topbar-right也是个bug，能否解决一下呢，谢谢

**Comment by Minwe** [comment]
你说的 bug 具体是什么情况？

**Comment by ww380459000** [comment]
![qq 20150608202101](https://cloud.githubusercontent.com/assets/2534696/8034640/277b471e-0e1c-11e5-897c-6fa4f5fde750.png)
![qq 20150608202123](https://cloud.githubusercontent.com/assets/2534696/8034641/27cd5216-0e1c-11e5-8d3f-c5bea7fbccdb.png)

640px以下的

**Comment by Minwe** [comment]
http://bin.amazeui.org/tewalo/1/edit?html,output

```html
    <header class="am-topbar am-topbar-inverse">
      <h1 class="am-topbar-brand">
        <a href="#">Amaze UI</a>
      </h1>

      <div class="am-fr am-margin-right-sm">
        <div class="am-dropdown" data-am-dropdown="{boundary: '.am-topbar'}">
          <button class="am-btn am-btn-secondary am-topbar-btn am-btn-sm am-dropdown-toggle" data-am-dropdown-toggle>其他 <span class="am-icon-caret-down"></span></button>
          <ul class="am-dropdown-content">
            <li><a href="#">注册</a></li>
            <li><a href="#">随便看看</a></li>
          </ul>
        </div>
      </div>
    </header>
```

活学活用，学会变通。理解背后的实现方式，才能运用自如。

**Comment by ww380459000** [comment]
嗯，谢谢，你人真好
