### ISSUE TITLE
帮助文件的copy按钮是怎么实现的？

### ISSUE THREAD

**Issue by xfworld** [allmobilize/amazeui#612]
真不容易，终于上传成功了
![image](https://cloud.githubusercontent.com/assets/5020771/8027031/ee59df1e-0dc0-11e5-9097-953a8229692e.png)

**Comment by ww380459000** [comment]
你自己看js么，用ZeroClipboard这个插件

**Comment by Minwe** [comment]
对头 https://github.com/zeroclipboard/zeroclipboard

**Comment by xfworld** [comment]
关键是想知道点击copy按钮以后，右下角的弹出框是咋实现的... 也是开源组件么

**Comment by Minwe** [comment]
右上角吧。

https://github.com/alexgibson/notify.js/

**Comment by xfworld** [comment]
![image](https://cloud.githubusercontent.com/assets/5020771/8031595/38d8c1a4-0e02-11e5-9adb-a75bb896b65c.png)
看图....

**Comment by xfworld** [comment]
http://alxgbsn.co.uk/notify.js/

看到demo了，可以关闭了
