### ISSUE TITLE
Thumbnail 图文混排 最后一个向右对齐

### ISSUE THREAD

**Issue by ww380459000** [allmobilize/amazeui#614]
你好，Thumbnail 图文混排 最后一个向右对齐，这个好像不太合理哦
这个能否有个自适应布局？

**Comment by xfworld** [comment]
Thumbnail 不太好用 ：） 我直接用的WEB组件里面的图片库...

你也试试

**Comment by ww380459000** [comment]
嗯，好，谢谢
