### ISSUE TITLE
关于amazeui.js的模块化加载

### ISSUE THREAD

**Issue by zhoushun49** [allmobilize/amazeui#618]
我从官网下载的amazeui.js,貌似是采用模块化打包，类似于browserify这种工具。问题是，我的项目也是采用类似工具打包的。如果希望把amazeui.js当做一个模块来打包，和我们自用到的js包，例如jquery，echart等打包成一个文件的话，要怎么做？

**Comment by Minwe** [comment]
直接 `require('amazeui')` 就行。
