### ISSUE TITLE
Bug: Web 组件演示页面在 iOS Chrome 上点击无反应

### ISSUE THREAD

**Issue by qianyuhao** [allmobilize/amazeui#621]
**问题描述**
点击无效
（描述一下问题）
http://amazeui.org/widgets/m# 页面在手机浏览器上打开无法点击查看demo
**产生环境**

- 设备：IOS
- 操作系统及版本：chrom浏览器
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 
2. 
...

**Comment by Minwe** [comment]
已经修复。

iScroll 的 `click` 选项和 `tap` 选项都有问题，没有按预期工作。添加 FastClick 以后就可以了。
