### ISSUE TITLE
div background-image 自适应问题

### ISSUE THREAD

**Issue by jiangyuhe123** [allmobilize/amazeui#622]
我想要在一个页面上加个div 然后div的背景是张图片。我发现使用css
background-image: url('../../img/Welcome.png'); 后，图片不能自适应，而且css必须指定图片的高度，否则不显示。
请问如何解决呢

**Comment by xfworld** [comment]
document.ready....

**Comment by Minwe** [comment]
这个跟我们没关系啊。

div 里面没有内容、没有设置padding、边框的时候，高度就是 0，所以需要设置高度才能显示你设置的背景图片。
