### ISSUE TITLE
添加fixed-layout导致am-show-sm-only无法显示问题

### ISSUE THREAD

**Issue by letheliu** [allmobilize/amazeui#623]
admin-index-fixed.html文件了fixed-layout，在小屏上无法显示菜单按钮。

**Comment by Minwe** [comment]
已经修复，只是还没有发布，如果现在要用可以替换一下 CSS
https://raw.githubusercontent.com/allmobilize/amazeui/c860b2e181c067aa0097f271e1394e8ad3735cb6/docs/examples/assets/css/admin.css

从参见 #599。
