### ISSUE TITLE
有没有这样玩的,用妹子做的界面内嵌到android里面做成apk???效果怎么样啊

### ISSUE THREAD

**Issue by msdlisper** [allmobilize/amazeui#625]
没的案桌程序员, 我想这样做,不晓得行不行哦

**Comment by letheliu** [comment]
可以，Phonegap一包装就可以

**Comment by msdlisper** [comment]
你这样玩过?,效果好不好,打包麻烦不啊

**Comment by Minwe** [comment]
参考 
- https://cordova.apache.org/
- http://phonegap.com/

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://www.abenteuerpension.at/sword.php?8xz>

 

Again_moon@sohu.com
