### ISSUE TITLE
Modal中添加按钮组，在ipad中选择按钮组时弹窗出现上下跳动

### ISSUE THREAD

**Issue by HeChangGG** [allmobilize/amazeui#640]
Modal中添加按钮组，在ipad中选择按钮组时弹窗出现上下跳动
测试地址：http://allinone.products.seevia.cn/contacts/
测试ipad版本 8.2（12D508）

**Comment by Minwe** [comment]
确实有这个问题，但是如果一个页面中只放一个 Modal 的话又无法重现。

你升级到 2.4.1 试试。

**Comment by HeChangGG** [comment]
升级到2.4.0了，这个问题没有了，日期组件禁用日期又报错了。。
    var nowTemp = new Date();
    var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate()+1, 0, 0, 0, 0);
    var next_week = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate()+7, 0, 0, 0, 0);
    var $myStart2 = $('#appointment_date');

    var checkin = $myStart2.datepicker({
      onRender: function(date) {
        return date.valueOf() < now.valueOf() || date.valueOf() > next_week.valueOf() ? 'am-disabled' : '';
      }
    }).on('changeDate.datepicker.amui', function(ev) {
//        if (ev.date.valueOf() > checkout.date.valueOf()) {
//          var newDate = new Date(ev.date)
//          newDate.setDate(newDate.getDate() + 1);
//          checkout.setValue(newDate);
//        }
        checkin.close();
        //$('#my-end-2')[0].focus();
    }).data('amui.datepicker');


return date.valueOf() < now.valueOf() || date.valueOf() > next_week.valueOf() ? 'am-disabled' : '';这段报错

------------------ 原始邮件 ------------------
发件人: "notifications";<notifications@github.com>;
发送时间: 2015年6月30日(星期二) 下午2:53
收件人: "allmobilize/amazeui"<amazeui@noreply.github.com>; 
抄送: "訸暢"<295372901@QQ.COM>; 
主题: Re: [amazeui] Modal中添加按钮组，在ipad中选择按钮组时弹窗出现上下跳动 (#640)




确实有这个问题，但是如果一个页面中只放一个 Modal 的话又无法重现。
 
你升级到 2.4.1 试试。

**Comment by Minwe** [comment]
http://bin.amazeui.org/sucara/1/edit

日期这个也没有你说的问题啊

**Comment by HeChangGG** [comment]
ok了，js冲突



------------------ 原始邮件 ------------------
发件人: "notifications";<notifications@github.com>;
发送时间: 2015年6月30日(星期二) 下午5:04
收件人: "allmobilize/amazeui"<amazeui@noreply.github.com>; 
抄送: "訸暢"<295372901@QQ.COM>; 
主题: Re: [amazeui] Modal中添加按钮组，在ipad中选择按钮组时弹窗出现上下跳动 (#640)




http://bin.amazeui.org/sucara/1/edit
 
日期这个也没有你说的问题啊
