### ISSUE TITLE
sass？

### ISSUE THREAD

**Issue by lili21** [allmobilize/amazeui#641]
以后会提供sass版本的源码吗？

**Comment by Minwe** [comment]
https://github.com/amazeui/amazeui-sass

**Comment by wengyulin** [comment]
我想知道你们的意图


来自 魅蓝

-------- 原始邮件 --------
发件人："li.li" <notifications@github.com>
时间：周五 6月26日 17:11
收件人：allmobilize/amazeui <amazeui@noreply.github.com>
主题：[amazeui] sass？ (#641)

**Comment by fengquan8866** [comment]
sass比less更好，目前对sass用得也稍多些

在 2015-07-01 06:48:11，"weng" <notifications@github.com> 写道：
我想知道你们的意图


来自 魅蓝

-------- 原始邮件 --------
发件人："li.li" <notifications@github.com>
时间：周五 6月26日 17:11
收件人：allmobilize/amazeui <amazeui@noreply.github.com>
主题：[amazeui] sass？ (#641)
