### ISSUE TITLE
js动态创建Tabs 组件无法使用的问题

### ISSUE THREAD

**Issue by MetSystem** [allmobilize/amazeui#652]
问题描述：
使用js动态创建的Tabs组件tabs无法切换。
我把网页中的输出的Tabs Html代码放到另一个静态网页中却可以正常切换。

**Comment by Minwe** [comment]
JS 创建完成以后执行 `$('#yourTabs').tabs();` 初始化。

**Comment by xfworld** [comment]
@Minwe 啥时候发新的版本啊，我看到你提交了tab的事件了，有新增和关闭

**Comment by MetSystem** [comment]
$('#yourTabs').tabs();
初始化后，能切换，就是内容显示不出来。通过google debug工具查看到面板的div缺少样式am-active。导致显示是空白的。

**Comment by xfworld** [comment]
@MetSystem 你没做样式引用么？

@Minwe  你有QQ不，求QQ号....

**Comment by MetSystem** [comment]
做了样式引用，就是点切换，但是这个样式没有加到面板里面，导致没有显示出来。
官方QQ群里面有2人也遇到了。

**Comment by MetSystem** [comment]
289755007@qq.com

**Comment by xfworld** [comment]
![20150630143303](https://cloud.githubusercontent.com/assets/5020771/8425096/f913d9a2-1f34-11e5-8ec1-c8178c55de4f.png)
你说的是这个么？ 可以用啊....

**Comment by MetSystem** [comment]
面板上缺少am-active 所以就空了。

**Comment by Minwe** [comment]
你怎么动态创建的啊？能给出可以运行的代码么？

**Comment by MetSystem** [comment]
<div id="content">
 </div>
 
 <script type="text/x-handlebars-template" id="tpi-list-detail">    
 <div class="am-tabs" >
            <ul class="am-tabs-nav am-nav am-nav-tabs">
            {{#each this}}
                <li class="{{#last}}am-active{{/last}}" ><a href="[data-panel-{{Month}}]">{{Month}}</a></li> 
            {{/each}}
            </ul>
            <div class="am-tabs-bd">
             {{#each this}}  
                <div [data-panel-{{Month}}] class="am-tab-panel {{#last}}am-active{{/last}}">
                    <table class="am-table am-table-bordered am-table-radius am-table-striped">
                        <tr>
                            <td>{{@Month}}月申明细</td>
                        </tr> 
                     </table> 
                </div>  
            {{/each}}
            </div>
        </div> 
</script>

<script type="text/javascript">
        var compiler = Handlebars.compile($("#tpi-list-detail").html());
		var result = [{Month:1},{Month:2},{Month:3}];
		var html = compiler(result);
		$("#content").html(content);
</script>

**Comment by MetSystem** [comment]
<div id="content">
 </div>
 
 <script type="text/x-handlebars-template" id="tpi-list-detail">    
 <div class="am-tabs" >
            <ul class="am-tabs-nav am-nav am-nav-tabs">
            {{#each this}}
                <li class="{{#last}}am-active{{/last}}" ><a href="[data-panel-{{Month}}]">{{Month}}</a></li> 
            {{/each}}
            </ul>
            <div class="am-tabs-bd">
             {{#each this}}  
                <div [data-panel-{{Month}}] class="am-tab-panel {{#last}}am-active{{/last}}">
                    <table class="am-table am-table-bordered am-table-radius am-table-striped">
                        <tr>
                            <td>{{@Month}}月申明细</td>
                        </tr> 
                     </table> 
                </div>  
            {{/each}}
            </div>
        </div> 
</script>

<script type="text/javascript">
        var compiler = Handlebars.compile($("#tpi-list-detail").html());
		var result = [{Month:1},{Month:2},{Month:3}];
		var html = compiler(result);
		$("#content").html(content);
</script>

**Comment by Minwe** [comment]
https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown

**Comment by MetSystem** [comment]
&lt;div id="content"&gt;
 &lt;/div&gt;
 
 &lt;script type="text/x-handlebars-template" id="tpi-list-detail"&gt;    
 &lt;div class="am-tabs" &gt;
            &lt;ul class="am-tabs-nav am-nav am-nav-tabs"&gt;
            {{#each this}}
                &lt;li class="{{#last}}am-active{{/last}}" &gt;&lt;a href="[data-panel-{{Month}}]"&gt;{{Month}}&lt;/a&gt;&lt;/li&gt; 
            {{/each}}
            &lt;/ul&gt;
            &lt;div class="am-tabs-bd"&gt;
             {{#each this}}  
                &lt;div [data-panel-{{Month}}] class="am-tab-panel {{#last}}am-active{{/last}}"&gt;
                    &lt;table class="am-table am-table-bordered am-table-radius am-table-striped"&gt;
                        &lt;tr&gt;
                            &lt;td&gt;{{@Month}}月申明细&lt;/td&gt;
                        &lt;/tr&gt; 
                     &lt;/table&gt; 
                &lt;/div&gt;  
            {{/each}}
            &lt;/div&gt;
        &lt;/div&gt; 
&lt;/script&gt;

&lt;script type="text/javascript"&gt;
        var compiler = Handlebars.compile($("#tpi-list-detail").html());
		var result = [{Month:1},{Month:2},{Month:3}];
		var html = compiler(result);
		$("#content").html(content);
&lt;/script&gt;

**Comment by xfworld** [comment]
你这写的啥啊？
模板信息怎么和dom，JS都混一块了？
好歹把生成好的数据传过来，在用JS加载到dom就o了.....

**Comment by MetSystem** [comment]
汗，这很明显是提取出来的，我那代码都自己添加了事件来处理了。

**Comment by Minwe** [comment]
http://bin.amazeui.org/melifi/1/edit?html,output

**Comment by xfworld** [comment]
text/x-handlebars-template 这是个什么脚本，，好用不？有点意思...

**Comment by xfworld** [comment]
这个东西不错，我刚好用的上，收了 ^_^

**Comment by MetSystem** [comment]
谢谢Minwe
 问题是官网demo上tabs 组件的panel 没有加 "[]" 引起。
 &lt;div data-tab-panel-0 class="am-tab-panel am-active"&gt;【青春】那时候有多好，.....
改成如下代码就可以正常切换。
 &lt;div [data-tab-panel-0] class="am-tab-panel am-active"&gt;【青春】那时候有多好，.....

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://watersedgefrisco.org/philosophical.php?n1jgp>

 

Again_moon@sohu.com
