### ISSUE TITLE
讨论：哪种方式写less更舒服？

### ISSUE THREAD

**Issue by agileago** [allmobilize/amazeui#660]
最近在学习前端，觉得amazeui的源码写的非常不错，一个组件一个组件的，在学习写组件的时候产生了一个疑问，好比给一个```button```写less

首先先到```variable.less```注册```button```所用的变量
<img width="683" alt="qq20150704-2 2x" src="https://cloud.githubusercontent.com/assets/11799110/8508108/94bc5c86-2295-11e5-8349-181fe4b46278.png">

然后再到```button.less```去写button的样式，感觉这个模式能不能改成这个样子，

全局性的东西定义在```variable.less```里面，前缀都带global
而写组件的时候，组件所用的变量就写在组件less->```button.less```里面

其实不只变量了，比如```button.less```还用到```mixin.less```里面的```.button-variant()```混合，

把button组件用到的这些关联东西都放在```button.less```里面

我觉得这样做对我目前的开发模式有几点帮助：
1.  我是用sublime编辑器，ps:(以前也用webstorm的，但是webstorm那个风格实在太难看，说实话，ws功能很强大，各种智能提示，有时候变量下面还有波浪线，用了一段时间实在是有些烦人)，而sublime是静态变量分析提示的，这样导致你在```variable.less  mixin.less```定义的变量，混合它是提示不出来的，只有靠分屏人肉手写，而写在一个文件里面它是可以提示的

2.  便于浏览查看修改代码，试想？如果我想修改button的某个颜色，我第一直觉是不是应该在```button.less```中修改，修改混合也是如此，

3.  感觉比较的解耦，更易读

其他的就没啥了，知道团队是使用WS的，变量写一个文件里面，所有文件都会有提示的，但是你们能记住那么多变量么？哪个是哪个么？最后在吐槽一下WS的界面风格，猛一看杂乱无章（细看井然有序），惹人恶心，但能把那么多功能集成到一个IDE里面真是一门哲学啊！

团队觉得这种方式怎样？

**Comment by wengyulin** [comment]
你是怎么在你的github里面写这个呢？求教程啊？

**Comment by Minwe** [comment]
变量都写在一个文件里是考虑如果做自定义变量的 GUI，读取方便一些。项目一旦成型以后，如果不是大版本更新，一般都懒得去动这些基本的结构了。

实际项目中怎么拆分文件，还是看项目结构和个人偏好吧。我们后来加的一些插件，变量和 mixin 都没归并到总的文件里面去。

即便把变量和 mixin 都写在模块里，如果文件过长的话可能还是需要分屏来查看，上下滚动比较繁琐，当然也看个人习惯。
