### ISSUE TITLE
closest是个什么属性？

### ISSUE THREAD

**Issue by xfworld** [allmobilize/amazeui#667]
<code>
$(validity.field).closest('.am-form-group').find('.am-alert').hide();
</code>

我看到新代码中到处都有<code>closest</code>，请问一下这个是干嘛的？

**Comment by xd199153** [comment]
自己查jquery的手册

**Comment by xfworld** [comment]
closest() 方法获得匹配选择器的第一个祖先元素，从当前元素开始沿 DOM 树向上。
