### ISSUE TITLE
日期组件不支持IE8吗?

### ISSUE THREAD

**Issue by mqliutie** [allmobilize/amazeui#675]
因为`modal`不支持IE8 

所以我用了`simplemodal`代替amaze的模态窗

但是现在一个问题是当我引入`simple-modal.js`时候日期插件就不好使了- - 

当我把引入的注销掉就好使(在IE8下测试)

**Comment by ccwq** [comment]
妹子ui还支持ie？

**Comment by Minwe** [comment]
你的标题跟得出的结论完全不符啊。

你可以看一下引入 simplemodal 以后控制台里有没有报错。

**Comment by mqliutie** [comment]
- -后来还是用的妹子,模态框IE8能用,只是有一段话出错了,弹出模态框时背景那种虚化状态,我在妹子js把那句话注释掉,IE8就可以用了.只是没有那种虚的状态

**Comment by minwe** [comment]
@mqliutie 具体是哪行代码？下次更新的时候我们可以处理一下。谢谢！
