### ISSUE TITLE
slider 图片轮播改成 4x2多图后，会导致4x2的图标出现空白，在手机上滑动和切换不流畅

### ISSUE THREAD

**Issue by MetSystem** [allmobilize/amazeui#676]
原始代码
&lt;div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0"&gt;
  &lt;ul class="am-slides"&gt;
    &lt;li&gt;&lt;img src="http://s.amazeui.org/media/i/demos/bing-1.jpg" /&gt;&lt;/li&gt;
    &lt;li&gt;&lt;img src="http://s.amazeui.org/media/i/demos/bing-2.jpg" /&gt;&lt;/li&gt;
  &lt;/ul&gt;
&lt;/div&gt;
修改后会导致 轮播或滑动的时候 li标签里面的图片空白，而后才加载出来
&lt;div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0"&gt;
  &lt;ul class="am-slides"&gt;
    &lt;li&gt;
        &lt;ui&gt;
                 &lt;li&gt;&lt;img /&gt;1&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;2&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;3&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;4&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;5&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;6&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;7&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;8&lt;/li&gt;
         &lt;/ul&gt; 
   &lt;/li&gt;
    &lt;li&gt;
         &lt;ui&gt;
                 &lt;li&gt;&lt;img /&gt;1&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;2&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;3&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;4&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;5&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;6&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;7&lt;/li&gt;
                 &lt;li&gt;&lt;img /&gt;8&lt;/li&gt;
         &lt;/ul&gt; 
    &lt;/li&gt;
  &lt;/ul&gt;
&lt;/div&gt;

**Comment by Minwe** [comment]
尝试以下两种方法：

- `<li>` 里面不要嵌套 `<ul>`，使用别的标签组合试试；
- 使用其他插件替换：
  - https://github.com/amazeui/slick
  - https://github.com/amazeui/swiper

**Comment by MetSystem** [comment]
之前可能是使用的问题套到l4x2上面无法使用，我就没用swiper 插件了，刚刚重新改了，完美解决。
谢谢@Minwe
