### ISSUE TITLE
Bug: 关于am-class命名与angular的ng-class标签冲突的情况？

### ISSUE THREAD

**Issue by asdf3309** [allmobilize/amazeui#682]
**问题描述**

今天在用angular加amaze-ui做分页指令的时候，
需要动态指定按钮 属性am-active和am-disable时发现的问题，
就是ng-class中定义为ng-class="{am-active: page.active}"，发现命名规则无法使用减号-，使用下划线_不会发生问题。
请问该怎么解决捏。

**产生环境**

angular1.3.17
chrome&firefox

```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
```

**Comment by asdf3309** [comment]
应该也不算大问题，就是难道我只能把am带头的标签都换了吗 
555

**Comment by asdf3309** [comment]
想了想感觉特么是angular的问题，我要去那边问问··

**Comment by minwe** [comment]
`ng-class="{'am-active': page.active}"` 加引号应该就可以了吧，angular 不至于那么 low。

**Comment by asdf3309** [comment]
原来是这样，啧啧啧，，3q

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://churia.com/regard.php?9ab7>

 

Again_moon@sohu.com
