### ISSUE TITLE
表单验证插件如何在验证成功以后 Ajax 提交表单？

### ISSUE THREAD

**Issue by mcc108** [allmobilize/amazeui#691]
**问题描述**

```js
$.when($('myForm').validator('isFormValid')).then(function() {
// 验证成功的逻辑
}, function() {
// 验证失败的逻辑
});
```
无法正确的判断是否验证成功。

**Comment by mcc108** [comment]
就是如何判断整个表单是否成功，

**Comment by mcc108** [comment]
如何让input submit 自定义时也触发表单验证

**Comment by mcc108** [comment]
想实现的是，通过异步提交表单，提交前需要js的验证

**Comment by minwe** [comment]
包含异步验证的时候才使用 `$.when()`，同步验证时直接判断就行：

```js
      $('#my-form').validator({
        submit: function() {
          var formValidity = this.isFormValid();

          if (formValidity) {
            console.log('成功，使用 ajax 提交表单');
          } else {
            console.log('失败');
          }

          return false;
        }
      });
```

http://bin.amazeui.org/fiqedo/edit?html,console,output

**Comment by mcc108** [comment]
@minwe   不是异步验证，而是异步提交表单，而且是验证通过后才能异步提交表单

**Comment by mcc108** [comment]
@minwe  可不可以不用submit 提交，而用其他的比如button 来触发ajax异步提交表单和验证表单呢？

**Comment by minwe** [comment]
```js
$('#my-form').validator('validateForm'); 
```

http://bin.amazeui.org/fiqedo/edit?html,console,output

**Comment by mcc108** [comment]
找到原因了，浏览器问题：
在Safari上 $('myForm').validator('isFormValid') 返回的值为 该表单的结点对象；
在Chrome上 $('myForm').validator('isFormValid') 返回的值为 布尔值

**Comment by minwe** [comment]
ok.

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://tehservice.in.ua/logical.php?950ij>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://kattennaam.nl/consumer.php?mjc28>

 

Again_moon@sohu.com
