### ISSUE TITLE
Modal传入值的问题

### ISSUE THREAD

**Issue by sduqlsc** [allmobilize/amazeui#694]
function(name){
$('#my-confirm').modal({
    onConfirm: function(options) {
   console.log(name)
  }
}

第一次传入'123'，输出正常，第二次'321'，依旧输出'123'！

**Comment by xfworld** [comment]
全部代码帖出来看看

**Comment by minwe** [comment]
http://amazeui.org/javascript/modal?_ver=2.x#mo-ni-confirm 示例代码下面【存在问题】中已经做说明。
