### ISSUE TITLE
如何监听折叠面板Accordion的某块是否被打开

### ISSUE THREAD

**Issue by bajian** [allmobilize/amazeui#702]
因为需要在折叠的时候更新内容就像QQ接收到新消息一样，标记个红点。所以需要知道当前版块是否被折叠（这个应该没问题）和再次打开时隐藏红点（这个没找到如何监听）。有何解决方案吗

**Comment by xfworld** [comment]
你说的是这个事件么？
自定义事件在折叠的元素上触发，以上面的折叠菜单为例，#collapse-nav 触发自定义事件：

<pre><code>
$('#collapse-nav').on('open.collapse.amui', function() {
  console.log('折叠菜单打开了！');
}).on('close.collapse.amui', function() {
  console.log('折叠菜单关闭鸟！');
});
</code></pre>
事件	描述
open.collapse.amui	open 方法被调用时立即触发
opened.collapse.amui	元素完全展开后触发
close.collapse.amui	close 方法被调用后立即触发
closed.collapse.amui	元素折叠完成后触发

**Comment by bajian** [comment]
哦，原来如此。thanks！！！官方2.2.3自定义事件那里是刚加上的吗？还是我眼瞎看走眼了- - ！

**Comment by minwe** [comment]
谢谢 @xfworld 帮忙解答。

使用时遇到问题可以先去文档里从头到尾看一下，包括用户评论。

**Comment by bajian** [comment]
其实我问的是web组件里的Accordion，它好像是封装过的，和js插件里的collapse不一样，加了collapse的监听也不行。换回collapse才可以用$('#collapse-nav').on('open.collapse.amui', function() {。。是我不会弄吗？

**Comment by minwe** [comment]
要找对应的元素监听事件，不是那个 ID 的元素你监听了当然没用。

```js
$('.am-accordion-item').on('opened.collapse.amui', function() {
  console.log('折叠菜单打开了x！');
}).on('closed.collapse.amui', function() {
  console.log('折叠菜单关闭鸟x！');
});
```

**Comment by bajian** [comment]
好的，。成功了。谢谢。不过我好像需要这样写才可以监听单独一个。。
$('.am-accordion-item').on('opened.collapse.amui', function() {
  if($(this).attr('id') == "audio_live"){
    console.log('折叠菜单打开了x！');
  }
  
}).on('closed.collapse.amui', function() {
  if($(this).attr('id') == "audio_live"){
    console.log('折叠菜单关闭鸟x！');
  }
  
});
直接用id监听单独的好像不行啊。。我之前就是这样测试不行的，，
$('#audio_live').on('opened.collapse.amui', function() {
    console.log('折叠菜单打开了x！');
}).on('closed.collapse.amui', function() {
    console.log('折叠菜单关闭鸟x！');
});


  <dl class="am-accordion-item" id="audio_live">
    <dt class="am-accordion-title">语音聊天</dt>
。。
。
。
。省略
    </dl>
哎，js基础不行

**Comment by xfworld** [comment]
@bajian  你可以按照组或者单个的进行监听；问题不大的；

如果你是自己定义的dom对象，需要用js初始化一下
<pre><code>
$('#myCollapse').collapse({
  toggle: false
})
</code></pre>

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://www.x4tune.com/blade.php?w>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://notestorosa.com/world.php?z>

 

Again_moon@sohu.com
