### ISSUE TITLE
[急救] 关于single page的app，amazeui.js 加载问题

### ISSUE THREAD

**Issue by jiangyuhe123** [allmobilize/amazeui#703]
如果是single page的架构，底层只有一个index.html，所有的页面都是通过ajax加载的方式读取到然后添加在index的某些div中间。发现amazeui 如果是在index.html中就加载的话， 后添加上去的html 元素即使采用了amazeui的动态js效果，也不起作用。但是如果F5刷新一下页面，保持amazeui.js 在最后加载的话，动态效果就会出现。

问题：amazeui.js 一定要在页面dom元素渲染完毕后加载，amazeui的效果才会起作用么？那么对于single page的应用，amazeui有什么好的后加载方式或者重新渲染js效果的方法么？

**Comment by minwe** [comment]
- 方式一：Ajax 加载内容完成以后调用插件的方法初始化；
- 方式二：使用 React 版本。

**Comment by jiangyuhe123** [comment]
方式一：Ajax 加载内容完成以后调用插件的方法初始化；

请问如何操作，可以举个例子么？谢谢

**Comment by minwe** [comment]
比如你加载进来的内容要显示一个 Modal 窗口，那就在加载完成以后执行 `$('#xxx').modal()`。

**Comment by jiangyuhe123** [comment]
可否在控件上加上 data-am-observe，否则每个控件都要初始化一次，代码有些啰嗦

**Comment by minwe** [comment]
MutationObserver 只是实验性功能，浏览器支持有限。

你这种后端只提供数据场合的应用应该在前端在加一个 MVC 之类的框架，不然完全靠手写 Ajax 来渲染感觉很麻烦。

**Comment by xfworld** [comment]
@minwe  我就自己写了一个扫描组件，用来初始化和渲染每个展示块相应的内容；ajax异步加载；没办法，现在只有jquery玩得比较溜；
坐等react版本....

**Comment by minwe** [comment]
SPA 应该是结合别的前端框架一起使用，如果只是单纯的通过 jQuery ajax 的形式实现，开发、维护都不太方便。

后续抽空看一下比较容器结合的框架。

**Comment by xfworld** [comment]
框架很多了，随便玩：） @minwe 你在react里面推荐的结合框架，都可以拿来用了；我觉得问题都不大

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://dymoyazici.com/nearby.php?cp7fk>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://funkybibs.co.uk/routine.php?qo>

 

Again_moon@sohu.com
