### ISSUE TITLE
modal遮罩层

### ISSUE THREAD

**Issue by liangshiyuan** [allmobilize/amazeui#704]
每个弹出的modal能不能都加上遮罩层。

**Comment by Mrxdh** [comment]
可以   自己配置一个

**Comment by minwe** [comment]
就这么一句话实在无从追踪问题产生的原因。

参考以下格式：

**问题描述**

（描述一下问题）

**产生环境**

- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1.
2.
...
