### ISSUE TITLE
能配置多个js入口文件么？

### ISSUE THREAD

**Issue by agileago** [allmobilize/amazeui#706]
开发一个网站的时候，可能有很多页面，而目前大多数前端项目看起来都是只针对一个页面，
而多个页面每个页面的js可能不一样，怎么配置gulpfile让他支持多个入口的js文件？

**Comment by minwe** [comment]
参考 http://stackoverflow.com/a/24443634/2340355

```js
'use strict;'

var config = require('../config');
var gulp = require('gulp');
var plumber = require('gulp-plumber');
var glob = require('glob');
var browserify  = require('browserify');
var source = require('vinyl-source-stream');

gulp.task('tests', function(){
  var testFiles = glob.sync('./spec/**/*.js');
  return browserify({
      entries: testFiles,
      extensions: ['.jsx']
    })
    .bundle({debug: true})
    .pipe(source('app.js'))
    .pipe(plumber())
    .pipe(gulp.dest(config.dest.development));
});
```

不太确定 Browserify 是否支持多个入口文件同时打包，你可以试一下，或者看看 webpack。

**Comment by agileago** [comment]
我见现在很多网站有很多页面，但整体的js文件就那几个，难道每个页面的逻辑都一样？我之前做的页面都是一个页面一个js文件，里面写本页面的逻辑，我现在就很困惑，难道现在都变成一个网站一个js文件了？大神请解释一下，刚转前端不久

**Comment by minwe** [comment]
一般把所有页面的 JS 都合并到一起了，这样只需要加载一次，其他页面打开时速度更快。

**Comment by agileago** [comment]
好吧，再研究一段时间。

**Comment by agileago** [comment]
感觉这个问题最能体会我的感受，http://stackoverflow.com/questions/26861340/bests-practice-for-browserify-in-large-web-projects-gulp

**Comment by minwe** [comment]
没遇到过不同页面的 JS 很大的情形，所以基本都是合在一起了。看具体情况吧。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://kattennaam.nl/feedback.php?f3rmg>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://sexlandia.ru/interesting.php?son7a>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://obatjambang.com/then.php?a>

 

Again_moon@sohu.com
