### ISSUE TITLE
 amazeui masonry handlebars item的事件失效

### ISSUE THREAD

**Issue by qq137712630** [allmobilize/amazeui#707]
我在 amazeui masonry 模版上加了个按钮

        <script type="text/x-handlebars-template" id="tpl-list" class="grid">
            {{#each events}}
            <div class="msry-item grid__item">
            <section class="am-panel am-panel-default">
            <header class="am-panel-hd ">
            <h3 class="am-panel-title">{{title}}</h3>
            </header>
            <div class="am-panel-bd action--buy">
            开始：{{begin_time}} <br/>
            结束： {{begin_time}}<br/>
            地点：{{address}} <br/>
            类型： {{category_name}} <br/>
            <a href="{{alt}}" target="_blank">查看详情 &rarrlp;</a>

            </div>
            </section>
            <button class="action--buy" onclick="addToCart()">购买</button>
            </div>
        
            {{/each}}

        </script>

并实现了事件：

/**
 * Created by 啟成 on 2015/8/3.
 */

$(function () {

    // cart
    var cart = document.querySelector('.cart'),
        cartItems = cart.querySelector('.cart__count'),

    function addToCart() {
        cartItems.innerHTML = Number(cartItems.innerHTML) + 1;
    }

    $('.action--buy').on('click', function () {
        alert("233333333");
        cart;
        addToCart();
    });

});

结果报错：
Uncaught ReferenceError: addToCart is not defined

大概理解为 .action--buy没初始化

而在网上找到了这2个答案：
https://github.com/allmobilize/amazeui/issues/531
https://github.com/allmobilize/amazeui/issues/356

请问这个方法：

 /*
  // 如果 Handlebars 渲染出来的 HTML 在 DOM ready 事件之后插入文档，需要手动初始化组件
   $.each(['slider', 'menu', 'gallery', 'footer', 'navbar'], function(i, m) {
     var module = $.AMUI[m];
     module && module.init && module.init();
   })
   */
是不是可以解决的？
还有就是这个要放在哪里使用的？？

**Comment by minwe** [comment]
与 #708 重复。
