### ISSUE TITLE
amazeui masonry handlebars item的事件失效

### ISSUE THREAD

**Issue by qq137712630** [allmobilize/amazeui#708]
**问题描述**

我在 amazeui masonry 模版上加了个按钮

```html
        <script type="text/x-handlebars-template" id="tpl-list" class="grid">
            {{#each events}}
            <div class="msry-item grid__item">
            <section class="am-panel am-panel-default">
            <header class="am-panel-hd ">
            <h3 class="am-panel-title">{{title}}</h3>
            </header>
            <div class="am-panel-bd action--buy">
            开始：{{begin_time}} <br/>
            结束： {{begin_time}}<br/>
            地点：{{address}} <br/>
            类型： {{category_name}} <br/>
            <a href="{{alt}}" target="_blank">查看详情 &rarrlp;</a>

            </div>
            </section>
            <button class="action--buy" onclick="addToCart()">购买</button>
            </div>
        
            {{/each}}
        </script>
```
并实现了事件：

```js
/**
 * Created by 啟成 on 2015/8/3.
 */

$(function () {

    // cart
    var cart = document.querySelector('.cart'),
        cartItems = cart.querySelector('.cart__count'),

    function addToCart() {
        cartItems.innerHTML = Number(cartItems.innerHTML) + 1;
    }

    $('.action--buy').on('click', function () {
        alert("233333333");
        cart;
        addToCart();
    });

});
```

结果报错：

```
Uncaught ReferenceError: addToCart is not defined
```

大概理解为 .action--buy没初始化

而在网上找到了这2个答案：
https://github.com/allmobilize/amazeui/issues/531
https://github.com/allmobilize/amazeui/issues/356

请问这个方法：

```js
 /*
  // 如果 Handlebars 渲染出来的 HTML 在 DOM ready 事件之后插入文档，需要手动初始化组件
   $.each(['slider', 'menu', 'gallery', 'footer', 'navbar'], function(i, m) {
     var module = $.AMUI[m];
     module && module.init && module.init();
   })
   */
```
是不是可以解决的？
还有就是这个要放在哪里使用的？？

**Comment by minwe** [comment]
把按钮上的点击事件去掉：

```html
<button class="action--buy" >购买</button>
```

JS 做一个事件委托：

```html
 $(document).on('click', 'action--buy', function () {
        alert("233333333");
        addToCart();
    });
```

**Comment by qq137712630** [comment]
十分感谢回复！不过已经解决了，虽然没用这个方法，但还是感谢回复

我的解决方法是这样的：

1.  <div class="am-panel-bd action--buy">中去掉action--buy，这样不会占用事件

  <script type="text/x-handlebars-template" id="tpl-list" class="grid">
            {{#each events}}
            <div class="msry-item grid__item">
                <section class="am-panel am-panel-default">
                    <header class="am-panel-hd ">
                        <h3 class="am-panel-title">{{title}}</h3>
                    </header>
                    <div class="am-panel-bd">
                        开始：{{begin_time}} <br/>
                        结束： {{begin_time}}<br/>
                        地点：{{address}} <br/>
                        类型： {{category_name}} <br/>
                        <a href="{{alt}}" target="_blank">查看详情 &rarrlp;</a>

                    </div>
                </section>
                <button class="action--buy">购买</button>
            </div>

            {{/each}}


        </script>

2.在 $.getJSON中加入事件：

一开始是这样加的：
 $.getJSON(url,function (data) {
            params.start = params.start + 10;
            //params.pagenum = params.pagenum + 1;
            var $html = $(compiler(data));
            $c.append($html).masonry('appended', $html).masonry('layout');

            $('.action--buy').on('click', function () {
               addToCart();
           });

        })

后来发现这样没法知道当前是点哪个商品，
所以后来变成这样：

 $.getJSON(url,function (data) {
            params.start = params.start + 10;
            //params.pagenum = params.pagenum + 1;
            var $html = $(compiler(data));
            $c.append($html).masonry('appended', $html).masonry('layout');

           initEvents();

        })

// grid element
  var  grid = document.querySelector('.grid');

//注，如果有多个action--buy，那只有前面的第一个才生效
function initEvents() {
 
    // add to cart 加入购物车
    [].slice.call(grid.querySelectorAll('.grid__item')).forEach(function (item) {
        item.querySelector('.action--buy').addEventListener('click', function () {
            item;//当前所选择的item
            addToCart(item);
        });
    });
}

**Comment by minwe** [comment]
解决就好。谢谢关注！
