### ISSUE TITLE
Bug:  Slider 设置轮播间隔时间无效

### ISSUE THREAD

**Issue by hrcyx** [allmobilize/amazeui#709]
**问题描述**

轮播图加载图片后 调用jq减少轮播时间失效。不加载图片是jq调用轮播减少时间是正常的

**产生环境**

- 设备：手机
- 操作系统及版本：
- 浏览器及版本：微信浏览器
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36
```

**Comment by minwe** [comment]
Flexslider 貌似没有动态更新参数的接口吧，你可以参考一下另外 这两个插件：

https://github.com/amazeui/slick
https://github.com/amazeui/swiper

**Comment by minwe** [comment]
另外，请给出使用 jQuery 减少轮播时间的代码。

**Comment by hrcyx** [comment]
css  jq js都引用没问题..代码如下   

<div class="am-slider am-slider-a1 am-slider-defalut">
        <ul class="am-slides" style="position:relative；">
          
            <li>
                <a href="http://angelslike.com/product.html?id=920">
                    <img src="/vote/Public/images/tianshilike.jpg">
                </a>
                <div class="indexImg am-text-center">点击查看</div>
            </li>
             <li>
                <a href="http://mp.weixin.qq.com/s?__biz=MzAwNzA1NjI0OA==&mid=207286457&idx=1&sn=6f3a4d0df7c31870dc8f7b5d87644d7c#rd">
                    <img src="/vote/Public/images/heitang.jpg">
                </a>
                <div class="indexImg am-text-center">点击查看</div>
            </li>
            <li>
                <a href="http://u.eqxiu.com/s/hn5rcsf7">
                    <img src="/vote/Public/images/free.jpg">
                </a>
                <div class="indexImg am-text-center">点击查看</div>
            </li>
        <li>
                <a href="http://wando.me/mobile/pages/goods.html?id=174">
                    <img src="/vote/Public/images/banner6.jpg">
                </a>
                <div class="indexImg am-text-center">点击查看</div>
            </li>

        </ul>

    </div>

<script type="text/javascript">  
            $(function(){  
                $('.am-slider').flexslider({  
                    playAfterPaused: 3000,  
                    animation: "fade",  
                    animationLoop: true,  
                    smoothHeight: true,             
             slideshowSpeed: 1000,
                  animationSpeed: 1000
                });  
            });   
        </script>

**Comment by hrcyx** [comment]
css  jq js都引用没问题..代码如下   

<div class="am-slider am-slider-a1 am-slider-defalut">
        <ul class="am-slides" style="position:relative；">
          
            <li>
                <a href="http://angelslike.com/product.html?id=920">
                    <img src="/vote/Public/images/tianshilike.jpg">
                </a>
                <div class="indexImg am-text-center">点击查看</div>
            </li>
             <li>
                <a href="http://mp.weixin.qq.com/s?__biz=MzAwNzA1NjI0OA==&mid=207286457&idx=1&sn=6f3a4d0df7c31870dc8f7b5d87644d7c#rd">
                    <img src="/vote/Public/images/heitang.jpg">
                </a>
                <div class="indexImg am-text-center">点击查看</div>
            </li>
            <li>
                <a href="http://u.eqxiu.com/s/hn5rcsf7">
                    <img src="/vote/Public/images/free.jpg">
                </a>
                <div class="indexImg am-text-center">点击查看</div>
            </li>
        <li>
                <a href="http://wando.me/mobile/pages/goods.html?id=174">
                    <img src="/vote/Public/images/banner6.jpg">
                </a>
                <div class="indexImg am-text-center">点击查看</div>
            </li>

        </ul>

    </div>

<script type="text/javascript">  
            $(function(){  
                $('.am-slider').flexslider({  
                    playAfterPaused: 3000,  
                    animation: "fade",  
                    animationLoop: true,  
                    smoothHeight: true,             
             slideshowSpeed: 1000,
                  animationSpeed: 1000
                });  
            });   
        </script>

**Comment by minwe** [comment]
使用 iPhone 微信试了一下，这个时间间隔是有效的。这一秒的间隔也太快了吧。
代码：http://bin.amazeui.org/rupezi/edit?html,output

你用的什么手机？可以试试。

![image](https://cloud.githubusercontent.com/assets/4370770/9267501/bb631052-4282-11e5-9e76-653c0ab08512.png)

**Comment by hrcyx** [comment]
用的是安卓..1S是为了检测能否成功，昨天我也在妹子群和人交流了下，他也说不行，不过之前版本是可以的....还是谢谢你的解答

**Comment by minwe** [comment]
拿同事安卓 5.0、微信 6.2 试了一下，没发现你说的问题。

会忽略 JS  初始化参数的只有两种情形：

- 容器上有 `data-am-flexslider` 属性；
- 容器上有 `[data-am-widget="slider"]` 属性。

**Comment by hrcyx** [comment]
好，我有时间的时候在测试下

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://pograniczelubuskie.pl/cabinet.php?krdz>

 

Again_moon@sohu.com
