### ISSUE TITLE
Bug: Edge浏览器中Modal显示异常(错位)

### ISSUE THREAD

**Issue by abc612008** [allmobilize/amazeui#712]
**问题描述**
Win10下EDGE浏览器弹出交互窗口时窗口大小会 正常-缩小-（重新渲染后）正常
缩小的时候显示还会错位，但是实际的按钮等触发区域是正常的。重新渲染（例如最小化后重打开）后正常，并且再次打开后也不会发生错位。

**产生环境**

- 操作系统及版本：Windows 10
- 浏览器及版本：Microsoft Edge 20.10240.16384.0
- 演示地址：http://amazeui.org/javascript/modal   （其中的大部分按钮都会错位）

**复现步奏**

1. 点击按钮（发生错位）
2. 最小化浏览器，然后再点开浏览器（恢复正常）
3. 关掉交互窗口，再打开（正常）

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://radioblueair.nl/english.php?l9>

 

Again_moon@sohu.com
