### ISSUE TITLE
Scrollbar 推荐

### ISSUE THREAD

**Issue by xfworld** [allmobilize/amazeui#717]
https://github.com/malihu/malihu-custom-scrollbar-plugin

@minwe 这个Scrollbar 还不错，而且也是MIT的许可；是否可以考虑加入到amazeui中？

**Comment by minwe** [comment]
这个不是刚性需求的东西，有需要的用户自己下载使用就行。它也发布到 NPM 了，使用也很方便。

Amaze UI 的主 JS 已经比较大了，一般不考虑再往里面加东西了。

**Comment by xfworld** [comment]
嗯，了解
