### ISSUE TITLE
日期控件疑问

### ISSUE THREAD

**Issue by xfworld** [allmobilize/amazeui#720]
@minwe  目前amazeui提供的日期控件只能支持到天级别，datetimepicker是可以支持到分秒级别，但是不能选择所有的秒，而且界面不够直观；选择天后，会跳页后在选择分秒；
不知道后续针对这块的任何有没有更新计划，来支持一下易用性；

我这边只能考虑使用折中的办法，一个input用来支持days的选择，另外一个input来支持小时、分、秒的选择；

**Comment by minwe** [comment]
可以看下这个
- http://eonasdan.github.io/bootstrap-datetimepicker/
- http://trentrichardson.com/examples/timepicker/

**Comment by xfworld** [comment]
赶紧移植个....现有的太搓了...

**Comment by xfworld** [comment]
http://trentrichardson.com/examples/timepicker/ 
这个好用点...
