### ISSUE TITLE
使用百度地图时标注图标不显示

### ISSUE THREAD

**Issue by xiazhujie** [allmobilize/amazeui#722]
使用amazeUI的页面里使用百度地图的话,标注图标不显示.
我改用iframe的方式图标出来了,但是设置的弹跳样式确实静止的.

不知道和amazeUI有没有关系?

详情:http://www.weihailan.com/artical/242

**Comment by minwe** [comment]
你发的链接打开是 404。

**Comment by xiazhujie** [comment]
连接能打开呀,主要是这个问题怎么解决?

**Comment by minwe** [comment]
请给出能直接演示的代码的，以便更快更准确解决问题。

**Comment by xiazhujie** [comment]
使用百度地图生成器生成的地图代码.比如把下面的代码放到amazeui的am-article-bd里:  

<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=Uv7IQu7h2un32PLn8DBsAkkM"></script>

<div id="map" style="width:100%;height:500px;border:#ccc solid 1px;font-size:12px">&nbsp;</div>
<script type="text/javascript">
    //创建和初始化地图函数：
    function initMap(){
      createMap();//创建地图
      setMapEvent();//设置地图事件
      addMapControl();//向地图添加控件
      addMapOverlay();//向地图添加覆盖物
    }
    function createMap(){ 
      map = new BMap.Map("map"); 
      map.centerAndZoom(new BMap.Point(122.384666,36.859591),15);
    }
    function setMapEvent(){
      map.enableScrollWheelZoom();
      map.enableKeyboard();
      map.enableDragging();
      map.enableDoubleClickZoom()
    }
    function addClickHandler(target,window){
      target.addEventListener("click",function(){
        target.openInfoWindow(window);
      });
    }
    function addMapOverlay(){
      var markers = [
        {content:"电话：0631-7955609",title:"<span style='color:#2182e0;font-size:18px;font-weight:700'>人和集团</span>",imageOffset: {width:-23,height:-21},position:{lat:36.85858,lng:122.381235}},
      ];
      for(var index = 0; index < markers.length; index++ ){
        var point = new BMap.Point(markers[index].position.lng,markers[index].position.lat);
        var marker = new BMap.Marker(point,{icon:new BMap.Icon("http://api.map.baidu.com/lbsapi/createmap/images/icon.png",new BMap.Size(20,25),{
          imageOffset: new BMap.Size(markers[index].imageOffset.width,markers[index].imageOffset.height)
        })});
        //var label = new BMap.Label(markers[index].title,{offset: new BMap.Size(25,5)});
        var label_opts = {
          position : point,    // 指定文本标注所在的地理位置
          offset   : new BMap.Size(25, 5)    //设置文本偏移量
        }
        var label = new BMap.Label(markers[index].title, label_opts);  // 创建文本标注对象
		label.setStyle({
			 color : "red",
			 fontSize : "12px",
			 height : "20px",
			 lineHeight : "20px",
			 fontFamily:"微软雅黑",
             border:"#888888 1px solid"
		 });
        
        var opts = {
          width: 200,
          title: markers[index].title,
          enableMessage: false
        };
        
        marker.setLabel(label);
        //map.addOverlay(label);

        var infoWindow = new BMap.InfoWindow(markers[index].content,opts);

        //        不好使
        addClickHandler(label,infoWindow);    //添加点击 label 也弹出 infoWindow
    
        addClickHandler(marker,infoWindow);
        map.addOverlay(marker);
        
        marker.setAnimation(BMAP_ANIMATION_BOUNCE); //跳动的动画
      };
    }
    //向地图添加控件
    function addMapControl(){
      var scaleControl = new BMap.ScaleControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT});
      scaleControl.setUnit(BMAP_UNIT_IMPERIAL);
      map.addControl(scaleControl);
      var navControl = new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_LEFT,type:BMAP_NAVIGATION_CONTROL_LARGE});
      map.addControl(navControl);
      var overviewControl = new BMap.OverviewMapControl({anchor:BMAP_ANCHOR_BOTTOM_RIGHT,isOpen:true});
      map.addControl(overviewControl);
    }
    var map;
      initMap();
  </script>
