### ISSUE TITLE
Amaze UI 有无接受捐赠的帐户？

### ISSUE THREAD

**Issue by JasonGaoG** [allmobilize/amazeui#723]
**问题描述**

有个家伙在群里面说想给你们捐钱，但是找不到爱妹子的公益账户，把这个公开到官网上吧。

**产生环境**

- 设备：（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：
- 演示地址：

**复现步奏**

1. 有个家伙在群里面说想给你们捐钱，但是找不到爱妹子的公益账户，把这个公开到官网上吧。
2. 有个家伙在群里面说想给你们捐钱，但是找不到爱妹子的公益账户，把这个公开到官网上吧。
...

**Comment by minwe** [comment]
谢谢关注！
Amaze UI 目前为公司运营，暂无接受捐赠的渠道。

我们会考虑一下是否能通过捐赠所得来鼓励第三方贡献代码的开发者。

**Comment by xfworld** [comment]
@minwe 第三方的开发者怎么参与阿...我比较关注这个

**Comment by minwe** [comment]
@xfworld 提意见建议、反馈 Bug 就是参与，更进一步的可以贡献代码。
