### ISSUE TITLE
在线定制工具：http://www.hyyyp.com/amaze.html 

### ISSUE THREAD

**Issue by hyyyp** [allmobilize/amazeui#728]
## 通过我对妹子的需求定制发现  日期 与 CheckBox 无效

ui.ucheck 单/多选框

ui.datepicker 日期组件

两组件均无效果

**Comment by minwe** [comment]
示例代码？

**Comment by hyyyp** [comment]
额 木有演示代码   你可以定制 这两个组件  调用就发现  没效果了

**Comment by minwe** [comment]
你是说按 http://amazeui.org/customize 这个定制的？

**Comment by hyyyp** [comment]
yeye

**Comment by hyyyp** [comment]
https://github.com/hyyyp/amazeui-customize

**Comment by minwe** [comment]
<img width="454" alt="2015-09-11 11 25 53" src="https://cloud.githubusercontent.com/assets/4370770/9806512/fd58cef6-5877-11e5-9a82-769130fa8b46.png">

从这 http://www.hyyyp.com/amaze.html 勾选 `ucheck` 和 `datepicker` 下载的文件执行效果如上图。

- `ucheck` 没什么问题；
- `datepicker` 依赖 CSS 依赖不全，我这边调整一下。

**Comment by hyyyp** [comment]
我不是单独定制这两个组件
但现在已经忘记我勾选了什么

下次遇到再说


还有就是  css的字体图标 URL

有被墙了

**Comment by hyyyp** [comment]
定制 增加   ui.scrollspynav     JS文件没生成

**Comment by minwe** [comment]
字体是放在 七牛 上的，你的网络有问题吧？你可以改成本地路径的。

**Comment by hyyyp** [comment]
dn-staticfile.qbox.me/font-awesome/4.3.0/fonts/fontawesome-webfont.eot?v=4.3.0

返回 

{"error":"Document not found"}

**Comment by minwe** [comment]
你这是什么时候的版本了，更新一下 Amaze UI 的源码。

**Comment by hyyyp** [comment]
好吧。。。  是该更新下

**Comment by minwe** [comment]
更新源码后你说的那些问题有可能就都不存在了。有的组件是后加的，老的源码里面可能没有。

**Comment by hyyyp** [comment]
已更新源码，ui.scrollspynav 依然存在， 
全选所有定制  除 ui.scrollspynav 外 均正常定制，
勾选ui.scrollspynav  JS不生成

**Comment by minwe** [comment]
选择模块的那个静态页面也需要更新一下。

下载配置文件本地执行 `gulp customize` 没出现 `ui.scrollspynav` 没打包进去的问题。

你那个定制服务器里下载的有的时候只有 CSS，没有 JS 文件。Gulp 是异步任务不，不知道是不是你用 C++ 调用的时候 gulp 执行完了没有。

**Comment by hyyyp** [comment]
线程异步的  并且定制目录都会独立分开  不会出现同时定制路劲冲突的
我定制了很多次 并没发现没有JS文件
只有选择了ui.scrollspynav 才出现 没有JS

**Comment by minwe** [comment]
你更新一下 amaze.html 这个页面应该就没问题了，原来的页面提交的依赖数据有点问题。

**Comment by hyyyp** [comment]
OK 完美解决

**Comment by minwe** [comment]
我看你这个 JS 打包这步速度还挺快，做了什么处理吗？

**Comment by hyyyp** [comment]
没有

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://simple-branding.co.uk/comprehensive.php?6gdp>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://jjmobilenetwork.com/add.php?8r5>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://tuvanketoanal.com/continued.php?h1g>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://media-shop.16mb.com/sign.php?rial>

 

Again_moon@sohu.com

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://jjmobilenetwork.com/himself.php?eqja>

 

Again_moon@sohu.com
