### ISSUE TITLE
IE10 select动态添加option不显示

### ISSUE THREAD

**Issue by xfworld** [allmobilize/amazeui#732]
![qq 20150914165723](https://cloud.githubusercontent.com/assets/5020771/9846531/4be09e84-5b05-11e5-8065-91fce7f21b1a.png)

见图，实际上option已经加入到了dom，但是页面死活不展示，吐血了.....

**Comment by minwe** [comment]
http://amazeui.org/javascript/selected#js-cao-zuo-select

IE10 需要手动触发事件：

```js
// 不支持 MutationObserver 的浏览器使用 JS 操作 select 以后需要手动触发 `changed.selected.amui` 事件
    if (!$.AMUI.support.mutationobserver) {
      $selected.trigger('changed.selected.amui');
    }
```

**Comment by xfworld** [comment]
这个事件我加了，但是没启作用；
如果我在外面增加了一个add的status【参考的demo】，那么这个时候就被触发了...
页面上就会出现所有的option...

怎么解？@minwe

**Comment by xfworld** [comment]
我理解错了，这个方法应该在domready的时候就执行，或者在加载select之前执行。我明天在试试

**Comment by minwe** [comment]
你每次添加 option 以后都需要触发 `changed.selected.amui` 事件以刷新下拉列表。

**Comment by xfworld** [comment]
<pre><code>
/**
	 * 展示动态新增的数据
	 * @param content 数据内容
	 * 
	 */
	function _showSelectData(content){
		$('#'+defaults.itemSelectID).append(content);
		 // 不支持 MutationObserver 的浏览器使用 JS 操作 select 以后需要手动触发 `changed.selected.amui` 事件
		if (!$.AMUI.support.mutationobserver) 
		{
			$('#'+defaults.itemSelectID).trigger('changed.selected.amui');
		}
	};
</code</pre>

总算搞定了....
