### ISSUE TITLE
Question ：fastClick

### ISSUE THREAD

**Issue by xfworld** [allmobilize/amazeui#739]
最近发现在移动端发生点击事件时，响应速度比较慢；我看到了fastClick这个解决方案，同时在应用的API说描述了2.4版已经移除了这个，
那现在如果要使用fastClick，需要注意些什么？免得出现其他的冲突；

**Comment by minwe** [comment]
http://amazeui.org/javascript/fastclick#chang-jian-wen-ti 除了里面写的，别的也不好说。

可能比较好的方式是只对特定的链接应用，而不是整个页面应用。
