### ISSUE TITLE
调试log没删掉

### ISSUE THREAD

**Issue by zcoding** [allmobilize/amazeui#741]
![image](https://cloud.githubusercontent.com/assets/4773646/10096158/ec3f2f0e-63a1-11e5-8902-141fa12c7cae.png)
如图，下载的是新版，使用的是压缩版本，使用modal的onConfirm的时候有log

**Comment by lndj** [comment]
偷偷告诉你 我很早就发现了～

**Comment by minwe** [comment]
#725 1dee75b3903c27c2d98fd55cf00000babe13460a
