### ISSUE TITLE
小白问个关于页面使用json数据

### ISSUE THREAD

**Issue by BigDuck** [allmobilize/amazeui#742]
```    
{{>header header}} 
```

就像这种的数据，首先假设页面数据蛮多的有个这样需要从服务端获取数据的组件，那么问题，怎么样的加载方法最好呢，因为这个是页面初始化的时候加载的，我曾试过使用ajax的异步加载过数据虽然能展示但是页面的效果全没了，比如折叠面板无法折叠其它的一样，应该是异步导致没加载完整就页面完成了，但是我把生成的代码直接复制到HTML里，效果是有的。能不能说其实已经加载完成了，但是为什么没法显示效果呢？第二，因为我觉得是异步问题，所以改成了同步，果然这样就可以了，但是问题也摆在那里数据多的话同步加载可能会影响用户体验。

只是小白，希望有空可以回答下，指条明路，谢谢

**Comment by minwe** [comment]
你可以按照这个页面的方式处理
- https://github.com/allmobilize/amazeui/blob/master/docs/examples/widget.html#L48-L49
- https://github.com/allmobilize/amazeui/blob/master/docs/examples/widget.html#L379-L381

具体就是：

1. 把模板放到标签里面；
2. Ajax 请求数据，数据请求成功以后渲染数据，然后插入到文档中。

**Comment by BigDuck** [comment]
虽然不想打扰你但是我还是有点不明白，我保证最后一个问题,这是我加载的方法，    其他地方一样，可是async为true的时候互动就无效
  
#  $(function() {
        $.ajax({
            url:"../json/header.json",
            cache : false,
            async:false,
            type : "get",
            dataType:"json",
            success:function(data){
                var $tpl = $('#my-tpl'),
                        tpl = $tpl.text(),
                        template = Handlebars.compile(tpl),
                        html = template(data);
                $tpl.before(html);
            }
        });
    });

**Comment by minwe** [comment]
异步加载的插入以后需要手动执行初始化：

```
...
$tpl.before(html);

// 假如插入的是 gallery
var module = $.AMUI.gallery;

module && module.init && module.init();
```
