### ISSUE TITLE
modal 的width 如何动态控制？

### ISSUE THREAD

**Issue by yhhwpp** [allmobilize/amazeui#743]
小白请教个问题，modal 的width 如何动态控制？因为我每次弹出之前需要计算modal的宽度重新赋值，而不是定死的

**Comment by minwe** [comment]
http://amazeui.org/javascript/modal#can-shu-shuo-ming

看看这，只能在初始化以前设置宽度，暂时没有动态改变宽度的接口。

你可以通过下面的方式实现：

```js
$('#modal').css({
  width: '1000px',
  marginLeft: '-500px'
});
```

`margin-left` 的值为负的宽度一半即可。

**Comment by yhhwpp** [comment]
好的，3q
