### ISSUE TITLE
select下拉框应可以支持输入值

### ISSUE THREAD

**Issue by 2070019559ysh** [allmobilize/amazeui#744]
虽说下拉框是直接选择进行输入，但还是有输入和选择共同进行的输入方式的需求的

**Comment by hainuo** [comment]
你这个是不是跟select2那种风格的 或者chosen那种风格的？

**Comment by minwe** [comment]
可以把 select 和 https://github.com/amazeui/tagsinput 结合使用，下拉框选中以后把值自动同步到 tagsinput 里面。如果需要用户直接输入的，就在 tagsinput 里面输入。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://watersedgemedia.com/landmark.php?zhnie>

 

Again_moon@sohu.com
