### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by schooljenry** [allmobilize/amazeui#745]
**问题描述**

我开发的项目在iphone的浏览器中，无法弹出左边的菜单栏。这个兼容性问题如何解决？

**产生环境**

- 设备：iphone6（手机、平板等移动设备时填写此项）
- 操作系统及版本：
- 浏览器及版本：内置浏览器，微信中的浏览器
- 演示地址：

**复现步奏**

1. 
2. 
... 
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Maxthon/4.4.6.2000 Chrome/30.0.1599.101 Safari/537.36
```

**Comment by minwe** [comment]
左边菜单是什么？没有可以查看的演示，无法确定问题出在哪。
