### ISSUE TITLE
CSS图标:期待更多图标加入

### ISSUE THREAD

**Issue by enzozhong** [allmobilize/amazeui#746]
# 图标中居然没有EMAIL和MSN

**Comment by enzozhong** [comment]
外贸网站经常用到,例如DHL,FedEx,TNT,UPS,WETERN UNION这些图标,期待

**Comment by minwe** [comment]
直接使用的 FortAwesome，你可以到上面发需求：

https://github.com/FortAwesome/Font-Awesome/blob/master/CONTRIBUTING.md#requesting-new-icons

或者使用 http://iconfont.cn/ 生成自己常用的图标
