### ISSUE TITLE
Bug: Amaze UI v2.4.2 源码 模态窗口测试代码未清除

### ISSUE THREAD

**Issue by anjia0532** [allmobilize/amazeui#748]
**问题描述**
在 http://cdn.amazeui.org/amazeui/2.4.2/js/amazeui.js 第5140行会输出'sdafdf'改行代码为console.log('sdafdf'); 
属于无意义的程序员左手常按键盘字母。而且在不支持console对象的浏览器会报错。
 
**UA:** 
```
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
```
![1](https://cloud.githubusercontent.com/assets/15098916/10444236/c3642b86-7196-11e5-83ea-59a2b54efadc.png)

**Comment by minwe** [comment]
#725 1dee75b
