### ISSUE TITLE
关于自定义 Tooltip 表单验证问题

### ISSUE THREAD

**Issue by shaohao2014** [allmobilize/amazeui#750]
我在官网http://amazeui.org/javascript/validator的 Tooltip的demo中增加了两个元素：
1、添加textarea，post时textarea能变红（说明验证起作用），但不显示错误提示信息。
2、添加select，post后没有任何反应（说明不起作用），已经添加required。
3、我在validator()里边添加了：validateOnSubmit: true, textareaMaxlenthKeyup: true
4、在$form.on里边添加了：'focusin focusout',  '.am-form-error input', function(e)...
5、另外 form 里还有两个input text控件，都能正常被验证并显示错误提示。
我的问题是：如何让上面两个元素被validator验证并显示正确提示呢？
从什么地方入手呢？textarea,select
官网截图如下：
![Uploading QQ截图20151015085322.png…]()

**Comment by minwe** [comment]
merge to #754
