### ISSUE TITLE
select组件导致isFormValid()返回错误的值

### ISSUE THREAD

**Issue by ucando** [allmobilize/amazeui#751]
当select没有选项时，isFormValid()仍旧返回true。不使用select组件则能正常提示验证结果

**Comment by minwe** [comment]
浏览器默认选中 `<select>` 的第一个值，写插件的时候保持跟浏览器的行为一致。

回头看一下能不能增加一个保留空值的选项。

与 #749 其实是一个问题，合并到 #749 处理。
