### ISSUE TITLE
csdn极客头条最热榜那个单页是不是用react开发的？

### ISSUE THREAD

**Issue by shaohao2014** [allmobilize/amazeui#752]
csdn极客头条最热榜  网站地址：http://geek.csdn.net/hotest
我想开发一个类似的页面，用什么框架好呢？

**Comment by minwe** [comment]
不是 React 开发的。

不需要什么框架。只要监听滚到到底部时 ajax 请求数据插入页面就行。

可以使用 https://github.com/infinite-scroll/infinite-scroll 这个插件，也可以自己写。

**Comment by shaohao2014** [comment]
谢兄弟

**Comment by shaohao2014** [comment]
还有个textarea和select验证的问题想问：
我在官网http://amazeui.org/javascript/validator的 Tooltip的demo中增加了两个元素：
1、添加textarea，post时textarea能变红（说明验证起作用），但不显示错误提示信息。
2、添加select，post后没有任何反应（说明不起作用），已经添加required。
3、我在validator()里边添加了：validateOnSubmit: true, textareaMaxlenthKeyup: true
4、在$form.on里边添加了：'focusin focusout', '.am-form-error input', function(e)...
5、另外 form 里还有两个input text控件，都能正常被验证并显示错误提示。
我的问题是：如何让上面两个元素被validator验证并显示正确提示呢？
从什么地方入手呢？textarea,select
官网截图如下：
![qq 20151015085322](https://cloud.githubusercontent.com/assets/6380120/10534136/67beffd2-7406-11e5-88e4-ef61014d0659.png)

**Comment by minwe** [comment]
http://bin.amazeui.org/wenozu/edit?html,console,output  有问题都到 #754 说吧。
