### ISSUE TITLE
textarea怎么无法验证提示?

### ISSUE THREAD

**Issue by shaohao2014** [allmobilize/amazeui#753]
textarea怎么无法验证提示?

**Comment by shaohao2014** [comment]
难道focusout和focusin对textarea不起作用？

**Comment by shaohao2014** [comment]
怎么把focusout和focusin两个事件绑定到textarea上呢？

**Comment by minwe** [comment]
http://amazeui.org/javascript/validator#js-biao-dan-yan-zheng

http://bin.amazeui.org/wenozu/edit?html,console,output

**Comment by minwe** [comment]
merge to #754

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://roniy.ru/compete.php?8>

 

Again_moon@sohu.com
