### ISSUE TITLE
怎么把focusout和focusin两个事件绑定到textarea上呢？

### ISSUE THREAD

**Issue by shaohao2014** [allmobilize/amazeui#754]
怎么把focusout和focusin两个事件绑定到textarea上呢？
我试了这样：
$form.on('focusin focusout', '.am-form-error textarea', function(e) {}
结果不行。
但是input绑定focusout和focusin的话可以，
如：$form.on('focusin focusout', '.am-form-error input', function(e) {}

**Comment by minwe** [comment]
验证没有通过的时候才会有 `am-form-error` 这个 class。

http://bin.amazeui.org/wenozu/edit?html,console,output

**Comment by minwe** [comment]
遇到问题尽量给出能执行的演示代码，不然别人也没办法准确理解你想表达什么。

**Comment by minwe** [comment]
http://bin.amazeui.org/wenozu/edit?html,console,output 这里的演示都是从文档里复制的代码，都是正常工作的。

遇到问题可能是你的选择符有问题，没有选择到相应的元素。

**Comment by shaohao2014** [comment]
问题就出在这里了，我的代码是 $form.on('focusin focusout', '.am-form-error input textarea')，我是想当然地直接在input后边加textarea，应该是这样：$form.on('focusin focusout', '.am-form-error input, .am-form-error textarea')。看来我是没好好看$.on()的API说明。谢谢啦兄弟，我差点放弃妹子验证改用jquery-validation，这个验证不成我只好昨天把jquery-validation研究的差不多了，哎，今天没想到看到你的答案，一字之差误事不少啊，效率低啊。建议amaze整理出个完整的API文档出来，让我们这些菜鸟好好学习一下，毕竟光有Demo不够用啊，也不至于我直接看妹子源码去研究妹子API的使用了。

**Comment by shaohao2014** [comment]
还有个问题：select验证不管用的问题，我的代码：
js部分：
`$form.on('focusin focusout', '.am-form-error select', function(e) {...}`
html部分：
`<select id="class_id"  data-am-selected="{btnWidth: '60%', maxHeight: 200, placeholder: ''} required>
			    	 <option value=""></option>
					  <optgroup label="请选择一项">
					    <option value="1">选项一...</option>
					    <option value="1">选项二...</option>
					  </optgroup>
</select>`
如果select代码更改为如下，则可以通过验证，正常提示错误信息：
 `<select id="doc-select-1-1" required>
        <option value="">-=请选择一项=-</option>
        <option value="option1">选项一...</option>
        <option value="option2">选项二.....</option>
 </select>`
为啥？
