### ISSUE TITLE
取消默认的点击按钮关闭窗口的行为

### ISSUE THREAD

**Issue by wufeng87** [allmobilize/amazeui#758]
$('.redownloadBtn.am-modal-btn').off('click.close.modal.amui').click(function(){
})

这样做点击这个按钮，默认还是会关闭模态窗口。

**Comment by wufeng87** [comment]
自己的执行顺序问题。

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://xn--80aikhnbcffy.xn--p1ai/finally.php?ptewx>

 

Again_moon@sohu.com
