### ISSUE TITLE
amaze的等分网格(am-*)为什么要自带padding，非常影响使用

### ISSUE THREAD

**Issue by feichangtutu** [allmobilize/amazeui#760]
如题

或者，想去掉padding，除了我手动修正，有什么amaze自带的样式可以去掉padding的设定么

**Comment by minwe** [comment]
http://amazeui.org/css/grid#yi-chu-lie-nei-bian-ju

```html
<div class="am-g am-g-collapse">
  <div class="am-u-sm-6">.am-u-sm-6</div>
  <div class="am-u-sm-6">.am-u-sm-6</div>
</div>
```

**Comment by againshao** [comment]
Hello!

 

You have a new message, please read <http://orto-magazin.com/couple.php?p0c>

 

Again_moon@sohu.com
