### ISSUE TITLE
这个项目好久不更新了，麻烦问一下还有在维护吗？

### ISSUE THREAD

**Issue by zchking** [allmobilize/amazeui#763]
这个项目好久不更新了，麻烦问一下还有在维护吗？谢谢：）

我们前端选型，很重要：）

**Comment by xfworld** [comment]
大奖赛呢

**Comment by minwe** [comment]
在维护。

前三个月精力放在 https://github.com/amazeui/amazeui-touch 开发上了。

本月会处理一些细节问题并更新。

**Comment by freechen** [comment]
希望继续维护，我们在生产环境中在使用

**Comment by minwe** [comment]
在更新维护的。谢谢关注！
